// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: indexer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latest known masterchain info, or "None" if the node is not ready yet.
	McStateInfo *McStateInfo `protobuf:"bytes,1,opt,name=mcStateInfo,proto3,oneof" json:"mcStateInfo,omitempty"`
	// Local server unix timestamp in milliseconds.
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Blockchain zerostate id.
	ZerostateRootHash []byte `protobuf:"bytes,3,opt,name=zerostateRootHash,proto3" json:"zerostateRootHash,omitempty"`
	// Blockchain zerostate id.
	ZerostateFileHash []byte `protobuf:"bytes,4,opt,name=zerostateFileHash,proto3" json:"zerostateFileHash,omitempty"`
	// From which masterchain block the node started working.
	InitBlockSeqno uint32 `protobuf:"varint,5,opt,name=initBlockSeqno,proto3" json:"initBlockSeqno,omitempty"`
	// Node version (encoded as octets, e.g. version 1.2.3 will be 0x00010203)
	Version       uint32 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetMcStateInfo() *McStateInfo {
	if x != nil {
		return x.McStateInfo
	}
	return nil
}

func (x *GetStatusResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetStatusResponse) GetZerostateRootHash() []byte {
	if x != nil {
		return x.ZerostateRootHash
	}
	return nil
}

func (x *GetStatusResponse) GetZerostateFileHash() []byte {
	if x != nil {
		return x.ZerostateFileHash
	}
	return nil
}

func (x *GetStatusResponse) GetInitBlockSeqno() uint32 {
	if x != nil {
		return x.InitBlockSeqno
	}
	return 0
}

func (x *GetStatusResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type WatchBlockIdsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Seqno of the first masterchain block event to send.
	// If the seqno is too far in the past, "range-skipped" event is sent.
	SinceMcSeqno  uint32 `protobuf:"varint,1,opt,name=sinceMcSeqno,proto3" json:"sinceMcSeqno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchBlockIdsRequest) Reset() {
	*x = WatchBlockIdsRequest{}
	mi := &file_indexer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchBlockIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchBlockIdsRequest) ProtoMessage() {}

func (x *WatchBlockIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchBlockIdsRequest.ProtoReflect.Descriptor instead.
func (*WatchBlockIdsRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{2}
}

func (x *WatchBlockIdsRequest) GetSinceMcSeqno() uint32 {
	if x != nil {
		return x.SinceMcSeqno
	}
	return 0
}

type WatchBlockIdsEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*WatchBlockIdsEvent_RangeSkipped
	//	*WatchBlockIdsEvent_NewMcBlock
	Event         isWatchBlockIdsEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchBlockIdsEvent) Reset() {
	*x = WatchBlockIdsEvent{}
	mi := &file_indexer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchBlockIdsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchBlockIdsEvent) ProtoMessage() {}

func (x *WatchBlockIdsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchBlockIdsEvent.ProtoReflect.Descriptor instead.
func (*WatchBlockIdsEvent) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{3}
}

func (x *WatchBlockIdsEvent) GetEvent() isWatchBlockIdsEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WatchBlockIdsEvent) GetRangeSkipped() *BlocksRangeSkipped {
	if x != nil {
		if x, ok := x.Event.(*WatchBlockIdsEvent_RangeSkipped); ok {
			return x.RangeSkipped
		}
	}
	return nil
}

func (x *WatchBlockIdsEvent) GetNewMcBlock() *NewMasterchainBlock {
	if x != nil {
		if x, ok := x.Event.(*WatchBlockIdsEvent_NewMcBlock); ok {
			return x.NewMcBlock
		}
	}
	return nil
}

type isWatchBlockIdsEvent_Event interface {
	isWatchBlockIdsEvent_Event()
}

type WatchBlockIdsEvent_RangeSkipped struct {
	RangeSkipped *BlocksRangeSkipped `protobuf:"bytes,1,opt,name=rangeSkipped,proto3,oneof"`
}

type WatchBlockIdsEvent_NewMcBlock struct {
	NewMcBlock *NewMasterchainBlock `protobuf:"bytes,2,opt,name=newMcBlock,proto3,oneof"`
}

func (*WatchBlockIdsEvent_RangeSkipped) isWatchBlockIdsEvent_Event() {}

func (*WatchBlockIdsEvent_NewMcBlock) isWatchBlockIdsEvent_Event() {}

type BlocksRangeSkipped struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Brief masterchain info at the moment of accessing the state.
	McStateInfo *McStateInfo `protobuf:"bytes,1,opt,name=mcStateInfo,proto3" json:"mcStateInfo,omitempty"`
	// Seqno of the first masterchain block in the skipped range (included).
	From uint32 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	// Seqno of the last masterchain block in the skipped range (included).
	To            uint32 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlocksRangeSkipped) Reset() {
	*x = BlocksRangeSkipped{}
	mi := &file_indexer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocksRangeSkipped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocksRangeSkipped) ProtoMessage() {}

func (x *BlocksRangeSkipped) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocksRangeSkipped.ProtoReflect.Descriptor instead.
func (*BlocksRangeSkipped) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{4}
}

func (x *BlocksRangeSkipped) GetMcStateInfo() *McStateInfo {
	if x != nil {
		return x.McStateInfo
	}
	return nil
}

func (x *BlocksRangeSkipped) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *BlocksRangeSkipped) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

type NewMasterchainBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Brief masterchain info at the moment of accessing the state.
	McStateInfo *McStateInfo `protobuf:"bytes,1,opt,name=mcStateInfo,proto3" json:"mcStateInfo,omitempty"`
	// The id of the masterchain block.
	McBlockId *BlockId `protobuf:"bytes,2,opt,name=mcBlockId,proto3" json:"mcBlockId,omitempty"`
	// Brief info for all shards in all workchains other than masterchain.
	ShardDescription []*ShardDescription `protobuf:"bytes,3,rep,name=shardDescription,proto3" json:"shardDescription,omitempty"`
	// All shard block ids since the previous masterchain block.
	// (can be empty if no new shard blocks were produced).
	ShardBlockIds []*BlockId `protobuf:"bytes,4,rep,name=shardBlockIds,proto3" json:"shardBlockIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMasterchainBlock) Reset() {
	*x = NewMasterchainBlock{}
	mi := &file_indexer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMasterchainBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMasterchainBlock) ProtoMessage() {}

func (x *NewMasterchainBlock) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMasterchainBlock.ProtoReflect.Descriptor instead.
func (*NewMasterchainBlock) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{5}
}

func (x *NewMasterchainBlock) GetMcStateInfo() *McStateInfo {
	if x != nil {
		return x.McStateInfo
	}
	return nil
}

func (x *NewMasterchainBlock) GetMcBlockId() *BlockId {
	if x != nil {
		return x.McBlockId
	}
	return nil
}

func (x *NewMasterchainBlock) GetShardDescription() []*ShardDescription {
	if x != nil {
		return x.ShardDescription
	}
	return nil
}

func (x *NewMasterchainBlock) GetShardBlockIds() []*BlockId {
	if x != nil {
		return x.ShardBlockIds
	}
	return nil
}

type ShardDescription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the latest block in that shard.
	LatestBlockId *BlockId `protobuf:"bytes,1,opt,name=latestBlockId,proto3" json:"latestBlockId,omitempty"`
	// LT of the latest block in that shard.
	EndLt uint64 `protobuf:"varint,2,opt,name=endLt,proto3" json:"endLt,omitempty"`
	// Unix timestamp when the latest block was generated.
	Utime uint32 `protobuf:"varint,3,opt,name=utime,proto3" json:"utime,omitempty"`
	// The latest known masterchain block at the time of shard generation.
	RegMcSeqno    uint32 `protobuf:"varint,4,opt,name=regMcSeqno,proto3" json:"regMcSeqno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardDescription) Reset() {
	*x = ShardDescription{}
	mi := &file_indexer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardDescription) ProtoMessage() {}

func (x *ShardDescription) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardDescription.ProtoReflect.Descriptor instead.
func (*ShardDescription) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{6}
}

func (x *ShardDescription) GetLatestBlockId() *BlockId {
	if x != nil {
		return x.LatestBlockId
	}
	return nil
}

func (x *ShardDescription) GetEndLt() uint64 {
	if x != nil {
		return x.EndLt
	}
	return 0
}

func (x *ShardDescription) GetUtime() uint32 {
	if x != nil {
		return x.Utime
	}
	return 0
}

func (x *ShardDescription) GetRegMcSeqno() uint32 {
	if x != nil {
		return x.RegMcSeqno
	}
	return 0
}

type GetBlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Query:
	//
	//	*GetBlockRequest_BySeqno
	//	*GetBlockRequest_ById
	Query         isGetBlockRequest_Query `protobuf_oneof:"query"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_indexer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlockRequest) GetQuery() isGetBlockRequest_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *GetBlockRequest) GetBySeqno() *BlockBySeqno {
	if x != nil {
		if x, ok := x.Query.(*GetBlockRequest_BySeqno); ok {
			return x.BySeqno
		}
	}
	return nil
}

func (x *GetBlockRequest) GetById() *BlockById {
	if x != nil {
		if x, ok := x.Query.(*GetBlockRequest_ById); ok {
			return x.ById
		}
	}
	return nil
}

type isGetBlockRequest_Query interface {
	isGetBlockRequest_Query()
}

type GetBlockRequest_BySeqno struct {
	// Searches for a block by seqno.
	BySeqno *BlockBySeqno `protobuf:"bytes,1,opt,name=bySeqno,proto3,oneof"`
}

type GetBlockRequest_ById struct {
	// Searches for a block by its id.
	ById *BlockById `protobuf:"bytes,2,opt,name=byId,proto3,oneof"`
}

func (*GetBlockRequest_BySeqno) isGetBlockRequest_Query() {}

func (*GetBlockRequest_ById) isGetBlockRequest_Query() {}

type GetBlockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GetBlockResponse_NotFound
	//	*GetBlockResponse_Found
	//	*GetBlockResponse_Chunk
	Msg           isGetBlockResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_indexer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{8}
}

func (x *GetBlockResponse) GetMsg() isGetBlockResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GetBlockResponse) GetNotFound() *BlockNotFound {
	if x != nil {
		if x, ok := x.Msg.(*GetBlockResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *GetBlockResponse) GetFound() *BlockFound {
	if x != nil {
		if x, ok := x.Msg.(*GetBlockResponse_Found); ok {
			return x.Found
		}
	}
	return nil
}

func (x *GetBlockResponse) GetChunk() *BlockChunk {
	if x != nil {
		if x, ok := x.Msg.(*GetBlockResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isGetBlockResponse_Msg interface {
	isGetBlockResponse_Msg()
}

type GetBlockResponse_NotFound struct {
	// First and last message in stream if not found.
	NotFound *BlockNotFound `protobuf:"bytes,1,opt,name=notFound,proto3,oneof"`
}

type GetBlockResponse_Found struct {
	// First message in stream if found.
	Found *BlockFound `protobuf:"bytes,2,opt,name=found,proto3,oneof"`
}

type GetBlockResponse_Chunk struct {
	// Subsequent messages in stream if it didn't fit into one chunk.
	Chunk *BlockChunk `protobuf:"bytes,3,opt,name=chunk,proto3,oneof"`
}

func (*GetBlockResponse_NotFound) isGetBlockResponse_Msg() {}

func (*GetBlockResponse_Found) isGetBlockResponse_Msg() {}

func (*GetBlockResponse_Chunk) isGetBlockResponse_Msg() {}

type BlockNotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McStateInfo   *McStateInfo           `protobuf:"bytes,1,opt,name=mcStateInfo,proto3" json:"mcStateInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockNotFound) Reset() {
	*x = BlockNotFound{}
	mi := &file_indexer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockNotFound) ProtoMessage() {}

func (x *BlockNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockNotFound.ProtoReflect.Descriptor instead.
func (*BlockNotFound) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{9}
}

func (x *BlockNotFound) GetMcStateInfo() *McStateInfo {
	if x != nil {
		return x.McStateInfo
	}
	return nil
}

type BlockFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McStateInfo   *McStateInfo           `protobuf:"bytes,1,opt,name=mcStateInfo,proto3" json:"mcStateInfo,omitempty"`
	TotalSize     uint64                 `protobuf:"varint,2,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	MaxChunkSize  uint64                 `protobuf:"varint,3,opt,name=maxChunkSize,proto3" json:"maxChunkSize,omitempty"`
	FirstChunk    *BlockChunk            `protobuf:"bytes,4,opt,name=firstChunk,proto3" json:"firstChunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockFound) Reset() {
	*x = BlockFound{}
	mi := &file_indexer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockFound) ProtoMessage() {}

func (x *BlockFound) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockFound.ProtoReflect.Descriptor instead.
func (*BlockFound) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{10}
}

func (x *BlockFound) GetMcStateInfo() *McStateInfo {
	if x != nil {
		return x.McStateInfo
	}
	return nil
}

func (x *BlockFound) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *BlockFound) GetMaxChunkSize() uint64 {
	if x != nil {
		return x.MaxChunkSize
	}
	return 0
}

func (x *BlockFound) GetFirstChunk() *BlockChunk {
	if x != nil {
		return x.FirstChunk
	}
	return nil
}

type BlockChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockChunk) Reset() {
	*x = BlockChunk{}
	mi := &file_indexer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockChunk) ProtoMessage() {}

func (x *BlockChunk) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockChunk.ProtoReflect.Descriptor instead.
func (*BlockChunk) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{11}
}

func (x *BlockChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BlockChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetShardAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workchain part of the address (int8 actually).
	Workchain int32 `protobuf:"varint,1,opt,name=workchain,proto3" json:"workchain,omitempty"`
	// 32 bytes of the hash part of the address.
	Address []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Whether to compute a separate proof that account state is included into a shard state.
	WithProof bool `protobuf:"varint,3,opt,name=withProof,proto3" json:"withProof,omitempty"`
	// Find account state at the time of a specific block
	//
	// Types that are valid to be assigned to AtBlock:
	//
	//	*GetShardAccountRequest_Latest
	//	*GetShardAccountRequest_BySeqno
	//	*GetShardAccountRequest_ById
	AtBlock       isGetShardAccountRequest_AtBlock `protobuf_oneof:"atBlock"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardAccountRequest) Reset() {
	*x = GetShardAccountRequest{}
	mi := &file_indexer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardAccountRequest) ProtoMessage() {}

func (x *GetShardAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardAccountRequest.ProtoReflect.Descriptor instead.
func (*GetShardAccountRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{12}
}

func (x *GetShardAccountRequest) GetWorkchain() int32 {
	if x != nil {
		return x.Workchain
	}
	return 0
}

func (x *GetShardAccountRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GetShardAccountRequest) GetWithProof() bool {
	if x != nil {
		return x.WithProof
	}
	return false
}

func (x *GetShardAccountRequest) GetAtBlock() isGetShardAccountRequest_AtBlock {
	if x != nil {
		return x.AtBlock
	}
	return nil
}

func (x *GetShardAccountRequest) GetLatest() *LatestBlock {
	if x != nil {
		if x, ok := x.AtBlock.(*GetShardAccountRequest_Latest); ok {
			return x.Latest
		}
	}
	return nil
}

func (x *GetShardAccountRequest) GetBySeqno() *BlockBySeqno {
	if x != nil {
		if x, ok := x.AtBlock.(*GetShardAccountRequest_BySeqno); ok {
			return x.BySeqno
		}
	}
	return nil
}

func (x *GetShardAccountRequest) GetById() *BlockById {
	if x != nil {
		if x, ok := x.AtBlock.(*GetShardAccountRequest_ById); ok {
			return x.ById
		}
	}
	return nil
}

type isGetShardAccountRequest_AtBlock interface {
	isGetShardAccountRequest_AtBlock()
}

type GetShardAccountRequest_Latest struct {
	// Uses the latest states "edge".
	Latest *LatestBlock `protobuf:"bytes,4,opt,name=latest,proto3,oneof"`
}

type GetShardAccountRequest_BySeqno struct {
	// Searches for a block by seqno.
	BySeqno *BlockBySeqno `protobuf:"bytes,5,opt,name=bySeqno,proto3,oneof"`
}

type GetShardAccountRequest_ById struct {
	// Searches for a block by its id.
	ById *BlockById `protobuf:"bytes,6,opt,name=byId,proto3,oneof"`
}

func (*GetShardAccountRequest_Latest) isGetShardAccountRequest_AtBlock() {}

func (*GetShardAccountRequest_BySeqno) isGetShardAccountRequest_AtBlock() {}

func (*GetShardAccountRequest_ById) isGetShardAccountRequest_AtBlock() {}

type GetShardAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Account:
	//
	//	*GetShardAccountResponse_BlockNotFound
	//	*GetShardAccountResponse_Accessed
	Account       isGetShardAccountResponse_Account `protobuf_oneof:"account"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardAccountResponse) Reset() {
	*x = GetShardAccountResponse{}
	mi := &file_indexer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardAccountResponse) ProtoMessage() {}

func (x *GetShardAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardAccountResponse.ProtoReflect.Descriptor instead.
func (*GetShardAccountResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{13}
}

func (x *GetShardAccountResponse) GetAccount() isGetShardAccountResponse_Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *GetShardAccountResponse) GetBlockNotFound() *BlockNotFound {
	if x != nil {
		if x, ok := x.Account.(*GetShardAccountResponse_BlockNotFound); ok {
			return x.BlockNotFound
		}
	}
	return nil
}

func (x *GetShardAccountResponse) GetAccessed() *ShardAccount {
	if x != nil {
		if x, ok := x.Account.(*GetShardAccountResponse_Accessed); ok {
			return x.Accessed
		}
	}
	return nil
}

type isGetShardAccountResponse_Account interface {
	isGetShardAccountResponse_Account()
}

type GetShardAccountResponse_BlockNotFound struct {
	// Specified block not found.
	BlockNotFound *BlockNotFound `protobuf:"bytes,1,opt,name=blockNotFound,proto3,oneof"`
}

type GetShardAccountResponse_Accessed struct {
	// Shard account info.
	Accessed *ShardAccount `protobuf:"bytes,2,opt,name=accessed,proto3,oneof"`
}

func (*GetShardAccountResponse_BlockNotFound) isGetShardAccountResponse_Account() {}

func (*GetShardAccountResponse_Accessed) isGetShardAccountResponse_Account() {}

type ShardAccountNotFound struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Brief masterchain info at the moment of accessing the state.
	McStateInfo   *McStateInfo `protobuf:"bytes,1,opt,name=mcStateInfo,proto3" json:"mcStateInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardAccountNotFound) Reset() {
	*x = ShardAccountNotFound{}
	mi := &file_indexer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardAccountNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardAccountNotFound) ProtoMessage() {}

func (x *ShardAccountNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardAccountNotFound.ProtoReflect.Descriptor instead.
func (*ShardAccountNotFound) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{14}
}

func (x *ShardAccountNotFound) GetMcStateInfo() *McStateInfo {
	if x != nil {
		return x.McStateInfo
	}
	return nil
}

type ShardAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Brief masterchain info at the moment of accessing the state.
	McStateInfo *McStateInfo `protobuf:"bytes,1,opt,name=mcStateInfo,proto3" json:"mcStateInfo,omitempty"`
	// BOC-encoded `ShardAccount` (if found).
	AccountState []byte `protobuf:"bytes,2,opt,name=accountState,proto3,oneof" json:"accountState,omitempty"`
	// BOC-encoded collection of proofs. Consists of two roots,
	// the first one is shard state root proof cell
	// and the second is account-in-state proof.
	Proof []byte `protobuf:"bytes,3,opt,name=proof,proto3,oneof" json:"proof,omitempty"`
	// The latest known transaction at the time of accessing the state (if any).
	// Can be used instead of `proof` if only something like LT is needed.
	LastTransaction *TransactionId `protobuf:"bytes,4,opt,name=lastTransaction,proto3,oneof" json:"lastTransaction,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShardAccount) Reset() {
	*x = ShardAccount{}
	mi := &file_indexer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardAccount) ProtoMessage() {}

func (x *ShardAccount) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardAccount.ProtoReflect.Descriptor instead.
func (*ShardAccount) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{15}
}

func (x *ShardAccount) GetMcStateInfo() *McStateInfo {
	if x != nil {
		return x.McStateInfo
	}
	return nil
}

func (x *ShardAccount) GetAccountState() []byte {
	if x != nil {
		return x.AccountState
	}
	return nil
}

func (x *ShardAccount) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *ShardAccount) GetLastTransaction() *TransactionId {
	if x != nil {
		return x.LastTransaction
	}
	return nil
}

type TransactionId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical time of transaction.
	Lt uint64 `protobuf:"varint,1,opt,name=lt,proto3" json:"lt,omitempty"`
	// 32 bytes of the transaction hash.
	Hash          []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionId) Reset() {
	*x = TransactionId{}
	mi := &file_indexer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionId) ProtoMessage() {}

func (x *TransactionId) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionId.ProtoReflect.Descriptor instead.
func (*TransactionId) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{16}
}

func (x *TransactionId) GetLt() uint64 {
	if x != nil {
		return x.Lt
	}
	return 0
}

func (x *TransactionId) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type GetLibraryCellRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32 bytes of the library cell root hash.
	Hash          []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibraryCellRequest) Reset() {
	*x = GetLibraryCellRequest{}
	mi := &file_indexer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibraryCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibraryCellRequest) ProtoMessage() {}

func (x *GetLibraryCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibraryCellRequest.ProtoReflect.Descriptor instead.
func (*GetLibraryCellRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{17}
}

func (x *GetLibraryCellRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type GetLibraryCellResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Library:
	//
	//	*GetLibraryCellResponse_NotFound
	//	*GetLibraryCellResponse_Found
	Library       isGetLibraryCellResponse_Library `protobuf_oneof:"library"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibraryCellResponse) Reset() {
	*x = GetLibraryCellResponse{}
	mi := &file_indexer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibraryCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibraryCellResponse) ProtoMessage() {}

func (x *GetLibraryCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibraryCellResponse.ProtoReflect.Descriptor instead.
func (*GetLibraryCellResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{18}
}

func (x *GetLibraryCellResponse) GetLibrary() isGetLibraryCellResponse_Library {
	if x != nil {
		return x.Library
	}
	return nil
}

func (x *GetLibraryCellResponse) GetNotFound() *LibraryCellNotFound {
	if x != nil {
		if x, ok := x.Library.(*GetLibraryCellResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *GetLibraryCellResponse) GetFound() *LibraryCellFound {
	if x != nil {
		if x, ok := x.Library.(*GetLibraryCellResponse_Found); ok {
			return x.Found
		}
	}
	return nil
}

type isGetLibraryCellResponse_Library interface {
	isGetLibraryCellResponse_Library()
}

type GetLibraryCellResponse_NotFound struct {
	NotFound *LibraryCellNotFound `protobuf:"bytes,1,opt,name=notFound,proto3,oneof"`
}

type GetLibraryCellResponse_Found struct {
	Found *LibraryCellFound `protobuf:"bytes,2,opt,name=found,proto3,oneof"`
}

func (*GetLibraryCellResponse_NotFound) isGetLibraryCellResponse_Library() {}

func (*GetLibraryCellResponse_Found) isGetLibraryCellResponse_Library() {}

type LibraryCellNotFound struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Brief masterchain info at the moment of accessing the state.
	McStateInfo   *McStateInfo `protobuf:"bytes,1,opt,name=mcStateInfo,proto3" json:"mcStateInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryCellNotFound) Reset() {
	*x = LibraryCellNotFound{}
	mi := &file_indexer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryCellNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryCellNotFound) ProtoMessage() {}

func (x *LibraryCellNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryCellNotFound.ProtoReflect.Descriptor instead.
func (*LibraryCellNotFound) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{19}
}

func (x *LibraryCellNotFound) GetMcStateInfo() *McStateInfo {
	if x != nil {
		return x.McStateInfo
	}
	return nil
}

type LibraryCellFound struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Brief masterchain info at the moment of accessing the state.
	McStateInfo *McStateInfo `protobuf:"bytes,1,opt,name=mcStateInfo,proto3" json:"mcStateInfo,omitempty"`
	// BOC-encoded library code.
	Cell          []byte `protobuf:"bytes,2,opt,name=cell,proto3" json:"cell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryCellFound) Reset() {
	*x = LibraryCellFound{}
	mi := &file_indexer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryCellFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryCellFound) ProtoMessage() {}

func (x *LibraryCellFound) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryCellFound.ProtoReflect.Descriptor instead.
func (*LibraryCellFound) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{20}
}

func (x *LibraryCellFound) GetMcStateInfo() *McStateInfo {
	if x != nil {
		return x.McStateInfo
	}
	return nil
}

func (x *LibraryCellFound) GetCell() []byte {
	if x != nil {
		return x.Cell
	}
	return nil
}

type GetLibraryCellsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An array of library root hashes (as 32 bytes).
	// NOTE: All non-unique entries are deduplicated.
	Hashes        [][]byte `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibraryCellsRequest) Reset() {
	*x = GetLibraryCellsRequest{}
	mi := &file_indexer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibraryCellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibraryCellsRequest) ProtoMessage() {}

func (x *GetLibraryCellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibraryCellsRequest.ProtoReflect.Descriptor instead.
func (*GetLibraryCellsRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{21}
}

func (x *GetLibraryCellsRequest) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type GetLibraryCellsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Brief masterchain info at the moment of accessing the state.
	McStateInfo *McStateInfo `protobuf:"bytes,1,opt,name=mcStateInfo,proto3" json:"mcStateInfo,omitempty"`
	// List of found libraries. Non-existing libraries are not included into this list.
	Entries       []*LibraryCellsBatchEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibraryCellsResponse) Reset() {
	*x = GetLibraryCellsResponse{}
	mi := &file_indexer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibraryCellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibraryCellsResponse) ProtoMessage() {}

func (x *GetLibraryCellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibraryCellsResponse.ProtoReflect.Descriptor instead.
func (*GetLibraryCellsResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{22}
}

func (x *GetLibraryCellsResponse) GetMcStateInfo() *McStateInfo {
	if x != nil {
		return x.McStateInfo
	}
	return nil
}

func (x *GetLibraryCellsResponse) GetEntries() []*LibraryCellsBatchEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LibraryCellsBatchEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32 bytes of the library cell root hash.
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// BOC-encoded library code.
	Cell          []byte `protobuf:"bytes,2,opt,name=cell,proto3" json:"cell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryCellsBatchEntry) Reset() {
	*x = LibraryCellsBatchEntry{}
	mi := &file_indexer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryCellsBatchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryCellsBatchEntry) ProtoMessage() {}

func (x *LibraryCellsBatchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryCellsBatchEntry.ProtoReflect.Descriptor instead.
func (*LibraryCellsBatchEntry) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{23}
}

func (x *LibraryCellsBatchEntry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *LibraryCellsBatchEntry) GetCell() []byte {
	if x != nil {
		return x.Cell
	}
	return nil
}

type SendMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BOC-encoded `Message`.
	Message       []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_indexer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{24}
}

func (x *SendMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of nodes this message was successfully delivered to.
	DeliveredTo   uint32 `protobuf:"varint,1,opt,name=deliveredTo,proto3" json:"deliveredTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_indexer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{25}
}

func (x *SendMessageResponse) GetDeliveredTo() uint32 {
	if x != nil {
		return x.DeliveredTo
	}
	return 0
}

type McStateInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Masterchain block seqno.
	McSeqno uint32 `protobuf:"varint,1,opt,name=mcSeqno,proto3" json:"mcSeqno,omitempty"`
	// Masterchain LT (end_lt).
	Lt uint64 `protobuf:"varint,2,opt,name=lt,proto3" json:"lt,omitempty"`
	// Masterchain unix timestamp.
	Utime         uint32 `protobuf:"varint,3,opt,name=utime,proto3" json:"utime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McStateInfo) Reset() {
	*x = McStateInfo{}
	mi := &file_indexer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McStateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McStateInfo) ProtoMessage() {}

func (x *McStateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McStateInfo.ProtoReflect.Descriptor instead.
func (*McStateInfo) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{26}
}

func (x *McStateInfo) GetMcSeqno() uint32 {
	if x != nil {
		return x.McSeqno
	}
	return 0
}

func (x *McStateInfo) GetLt() uint64 {
	if x != nil {
		return x.Lt
	}
	return 0
}

func (x *McStateInfo) GetUtime() uint32 {
	if x != nil {
		return x.Utime
	}
	return 0
}

type BlockBySeqno struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workchain     int32                  `protobuf:"varint,1,opt,name=workchain,proto3" json:"workchain,omitempty"`
	Shard         uint64                 `protobuf:"varint,2,opt,name=shard,proto3" json:"shard,omitempty"`
	Seqno         uint32                 `protobuf:"varint,3,opt,name=seqno,proto3" json:"seqno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockBySeqno) Reset() {
	*x = BlockBySeqno{}
	mi := &file_indexer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockBySeqno) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockBySeqno) ProtoMessage() {}

func (x *BlockBySeqno) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockBySeqno.ProtoReflect.Descriptor instead.
func (*BlockBySeqno) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{27}
}

func (x *BlockBySeqno) GetWorkchain() int32 {
	if x != nil {
		return x.Workchain
	}
	return 0
}

func (x *BlockBySeqno) GetShard() uint64 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *BlockBySeqno) GetSeqno() uint32 {
	if x != nil {
		return x.Seqno
	}
	return 0
}

type BlockById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *BlockId               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockById) Reset() {
	*x = BlockById{}
	mi := &file_indexer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockById) ProtoMessage() {}

func (x *BlockById) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockById.ProtoReflect.Descriptor instead.
func (*BlockById) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{28}
}

func (x *BlockById) GetId() *BlockId {
	if x != nil {
		return x.Id
	}
	return nil
}

type LatestBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestBlock) Reset() {
	*x = LatestBlock{}
	mi := &file_indexer_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestBlock) ProtoMessage() {}

func (x *LatestBlock) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestBlock.ProtoReflect.Descriptor instead.
func (*LatestBlock) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{29}
}

type BlockId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workchain     int32                  `protobuf:"varint,1,opt,name=workchain,proto3" json:"workchain,omitempty"`
	Shard         uint64                 `protobuf:"varint,2,opt,name=shard,proto3" json:"shard,omitempty"`
	Seqno         uint32                 `protobuf:"varint,3,opt,name=seqno,proto3" json:"seqno,omitempty"`
	RootHash      []byte                 `protobuf:"bytes,4,opt,name=rootHash,proto3" json:"rootHash,omitempty"`
	FileHash      []byte                 `protobuf:"bytes,5,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockId) Reset() {
	*x = BlockId{}
	mi := &file_indexer_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockId) ProtoMessage() {}

func (x *BlockId) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockId.ProtoReflect.Descriptor instead.
func (*BlockId) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{30}
}

func (x *BlockId) GetWorkchain() int32 {
	if x != nil {
		return x.Workchain
	}
	return 0
}

func (x *BlockId) GetShard() uint64 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *BlockId) GetSeqno() uint32 {
	if x != nil {
		return x.Seqno
	}
	return 0
}

func (x *BlockId) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *BlockId) GetFileHash() []byte {
	if x != nil {
		return x.FileHash
	}
	return nil
}

var File_indexer_proto protoreflect.FileDescriptor

const file_indexer_proto_rawDesc = "" +
	"\n" +
	"\rindexer.proto\x12\aindexer\"\x12\n" +
	"\x10GetStatusRequest\"\x9c\x02\n" +
	"\x11GetStatusResponse\x12;\n" +
	"\vmcStateInfo\x18\x01 \x01(\v2\x14.indexer.McStateInfoH\x00R\vmcStateInfo\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12,\n" +
	"\x11zerostateRootHash\x18\x03 \x01(\fR\x11zerostateRootHash\x12,\n" +
	"\x11zerostateFileHash\x18\x04 \x01(\fR\x11zerostateFileHash\x12&\n" +
	"\x0einitBlockSeqno\x18\x05 \x01(\rR\x0einitBlockSeqno\x12\x18\n" +
	"\aversion\x18\x06 \x01(\rR\aversionB\x0e\n" +
	"\f_mcStateInfo\":\n" +
	"\x14WatchBlockIdsRequest\x12\"\n" +
	"\fsinceMcSeqno\x18\x01 \x01(\rR\fsinceMcSeqno\"\xa0\x01\n" +
	"\x12WatchBlockIdsEvent\x12A\n" +
	"\frangeSkipped\x18\x01 \x01(\v2\x1b.indexer.BlocksRangeSkippedH\x00R\frangeSkipped\x12>\n" +
	"\n" +
	"newMcBlock\x18\x02 \x01(\v2\x1c.indexer.NewMasterchainBlockH\x00R\n" +
	"newMcBlockB\a\n" +
	"\x05event\"p\n" +
	"\x12BlocksRangeSkipped\x126\n" +
	"\vmcStateInfo\x18\x01 \x01(\v2\x14.indexer.McStateInfoR\vmcStateInfo\x12\x12\n" +
	"\x04from\x18\x02 \x01(\rR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\rR\x02to\"\xfc\x01\n" +
	"\x13NewMasterchainBlock\x126\n" +
	"\vmcStateInfo\x18\x01 \x01(\v2\x14.indexer.McStateInfoR\vmcStateInfo\x12.\n" +
	"\tmcBlockId\x18\x02 \x01(\v2\x10.indexer.BlockIdR\tmcBlockId\x12E\n" +
	"\x10shardDescription\x18\x03 \x03(\v2\x19.indexer.ShardDescriptionR\x10shardDescription\x126\n" +
	"\rshardBlockIds\x18\x04 \x03(\v2\x10.indexer.BlockIdR\rshardBlockIds\"\x96\x01\n" +
	"\x10ShardDescription\x126\n" +
	"\rlatestBlockId\x18\x01 \x01(\v2\x10.indexer.BlockIdR\rlatestBlockId\x12\x14\n" +
	"\x05endLt\x18\x02 \x01(\x04R\x05endLt\x12\x14\n" +
	"\x05utime\x18\x03 \x01(\rR\x05utime\x12\x1e\n" +
	"\n" +
	"regMcSeqno\x18\x04 \x01(\rR\n" +
	"regMcSeqno\"w\n" +
	"\x0fGetBlockRequest\x121\n" +
	"\abySeqno\x18\x01 \x01(\v2\x15.indexer.BlockBySeqnoH\x00R\abySeqno\x12(\n" +
	"\x04byId\x18\x02 \x01(\v2\x12.indexer.BlockByIdH\x00R\x04byIdB\a\n" +
	"\x05query\"\xa9\x01\n" +
	"\x10GetBlockResponse\x124\n" +
	"\bnotFound\x18\x01 \x01(\v2\x16.indexer.BlockNotFoundH\x00R\bnotFound\x12+\n" +
	"\x05found\x18\x02 \x01(\v2\x13.indexer.BlockFoundH\x00R\x05found\x12+\n" +
	"\x05chunk\x18\x03 \x01(\v2\x13.indexer.BlockChunkH\x00R\x05chunkB\x05\n" +
	"\x03msg\"G\n" +
	"\rBlockNotFound\x126\n" +
	"\vmcStateInfo\x18\x01 \x01(\v2\x14.indexer.McStateInfoR\vmcStateInfo\"\xbb\x01\n" +
	"\n" +
	"BlockFound\x126\n" +
	"\vmcStateInfo\x18\x01 \x01(\v2\x14.indexer.McStateInfoR\vmcStateInfo\x12\x1c\n" +
	"\ttotalSize\x18\x02 \x01(\x04R\ttotalSize\x12\"\n" +
	"\fmaxChunkSize\x18\x03 \x01(\x04R\fmaxChunkSize\x123\n" +
	"\n" +
	"firstChunk\x18\x04 \x01(\v2\x13.indexer.BlockChunkR\n" +
	"firstChunk\"8\n" +
	"\n" +
	"BlockChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x86\x02\n" +
	"\x16GetShardAccountRequest\x12\x1c\n" +
	"\tworkchain\x18\x01 \x01(\x05R\tworkchain\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12\x1c\n" +
	"\twithProof\x18\x03 \x01(\bR\twithProof\x12.\n" +
	"\x06latest\x18\x04 \x01(\v2\x14.indexer.LatestBlockH\x00R\x06latest\x121\n" +
	"\abySeqno\x18\x05 \x01(\v2\x15.indexer.BlockBySeqnoH\x00R\abySeqno\x12(\n" +
	"\x04byId\x18\x06 \x01(\v2\x12.indexer.BlockByIdH\x00R\x04byIdB\t\n" +
	"\aatBlock\"\x99\x01\n" +
	"\x17GetShardAccountResponse\x12>\n" +
	"\rblockNotFound\x18\x01 \x01(\v2\x16.indexer.BlockNotFoundH\x00R\rblockNotFound\x123\n" +
	"\baccessed\x18\x02 \x01(\v2\x15.indexer.ShardAccountH\x00R\baccessedB\t\n" +
	"\aaccount\"N\n" +
	"\x14ShardAccountNotFound\x126\n" +
	"\vmcStateInfo\x18\x01 \x01(\v2\x14.indexer.McStateInfoR\vmcStateInfo\"\x80\x02\n" +
	"\fShardAccount\x126\n" +
	"\vmcStateInfo\x18\x01 \x01(\v2\x14.indexer.McStateInfoR\vmcStateInfo\x12'\n" +
	"\faccountState\x18\x02 \x01(\fH\x00R\faccountState\x88\x01\x01\x12\x19\n" +
	"\x05proof\x18\x03 \x01(\fH\x01R\x05proof\x88\x01\x01\x12E\n" +
	"\x0flastTransaction\x18\x04 \x01(\v2\x16.indexer.TransactionIdH\x02R\x0flastTransaction\x88\x01\x01B\x0f\n" +
	"\r_accountStateB\b\n" +
	"\x06_proofB\x12\n" +
	"\x10_lastTransaction\"3\n" +
	"\rTransactionId\x12\x0e\n" +
	"\x02lt\x18\x01 \x01(\x04R\x02lt\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"+\n" +
	"\x15GetLibraryCellRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"\x92\x01\n" +
	"\x16GetLibraryCellResponse\x12:\n" +
	"\bnotFound\x18\x01 \x01(\v2\x1c.indexer.LibraryCellNotFoundH\x00R\bnotFound\x121\n" +
	"\x05found\x18\x02 \x01(\v2\x19.indexer.LibraryCellFoundH\x00R\x05foundB\t\n" +
	"\alibrary\"M\n" +
	"\x13LibraryCellNotFound\x126\n" +
	"\vmcStateInfo\x18\x01 \x01(\v2\x14.indexer.McStateInfoR\vmcStateInfo\"^\n" +
	"\x10LibraryCellFound\x126\n" +
	"\vmcStateInfo\x18\x01 \x01(\v2\x14.indexer.McStateInfoR\vmcStateInfo\x12\x12\n" +
	"\x04cell\x18\x02 \x01(\fR\x04cell\"0\n" +
	"\x16GetLibraryCellsRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\fR\x06hashes\"\x8c\x01\n" +
	"\x17GetLibraryCellsResponse\x126\n" +
	"\vmcStateInfo\x18\x01 \x01(\v2\x14.indexer.McStateInfoR\vmcStateInfo\x129\n" +
	"\aentries\x18\x02 \x03(\v2\x1f.indexer.LibraryCellsBatchEntryR\aentries\"@\n" +
	"\x16LibraryCellsBatchEntry\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04cell\x18\x02 \x01(\fR\x04cell\".\n" +
	"\x12SendMessageRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\"7\n" +
	"\x13SendMessageResponse\x12 \n" +
	"\vdeliveredTo\x18\x01 \x01(\rR\vdeliveredTo\"M\n" +
	"\vMcStateInfo\x12\x18\n" +
	"\amcSeqno\x18\x01 \x01(\rR\amcSeqno\x12\x0e\n" +
	"\x02lt\x18\x02 \x01(\x04R\x02lt\x12\x14\n" +
	"\x05utime\x18\x03 \x01(\rR\x05utime\"X\n" +
	"\fBlockBySeqno\x12\x1c\n" +
	"\tworkchain\x18\x01 \x01(\x05R\tworkchain\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\x04R\x05shard\x12\x14\n" +
	"\x05seqno\x18\x03 \x01(\rR\x05seqno\"-\n" +
	"\tBlockById\x12 \n" +
	"\x02id\x18\x01 \x01(\v2\x10.indexer.BlockIdR\x02id\"\r\n" +
	"\vLatestBlock\"\x8b\x01\n" +
	"\aBlockId\x12\x1c\n" +
	"\tworkchain\x18\x01 \x01(\x05R\tworkchain\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\x04R\x05shard\x12\x14\n" +
	"\x05seqno\x18\x03 \x01(\rR\x05seqno\x12\x1a\n" +
	"\brootHash\x18\x04 \x01(\fR\brootHash\x12\x1a\n" +
	"\bfileHash\x18\x05 \x01(\fR\bfileHash2\xad\x04\n" +
	"\fTychoIndexer\x12B\n" +
	"\tGetStatus\x12\x19.indexer.GetStatusRequest\x1a\x1a.indexer.GetStatusResponse\x12M\n" +
	"\rWatchBlockIds\x12\x1d.indexer.WatchBlockIdsRequest\x1a\x1b.indexer.WatchBlockIdsEvent0\x01\x12A\n" +
	"\bGetBlock\x12\x18.indexer.GetBlockRequest\x1a\x19.indexer.GetBlockResponse0\x01\x12T\n" +
	"\x0fGetShardAccount\x12\x1f.indexer.GetShardAccountRequest\x1a .indexer.GetShardAccountResponse\x12Q\n" +
	"\x0eGetLibraryCell\x12\x1e.indexer.GetLibraryCellRequest\x1a\x1f.indexer.GetLibraryCellResponse\x12T\n" +
	"\x0fGetLibraryCells\x12\x1f.indexer.GetLibraryCellsRequest\x1a .indexer.GetLibraryCellsResponse\x12H\n" +
	"\vSendMessage\x12\x1b.indexer.SendMessageRequest\x1a\x1c.indexer.SendMessageResponseB\tZ\a./protob\x06proto3"

var (
	file_indexer_proto_rawDescOnce sync.Once
	file_indexer_proto_rawDescData []byte
)

func file_indexer_proto_rawDescGZIP() []byte {
	file_indexer_proto_rawDescOnce.Do(func() {
		file_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)))
	})
	return file_indexer_proto_rawDescData
}

var file_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_indexer_proto_goTypes = []any{
	(*GetStatusRequest)(nil),        // 0: indexer.GetStatusRequest
	(*GetStatusResponse)(nil),       // 1: indexer.GetStatusResponse
	(*WatchBlockIdsRequest)(nil),    // 2: indexer.WatchBlockIdsRequest
	(*WatchBlockIdsEvent)(nil),      // 3: indexer.WatchBlockIdsEvent
	(*BlocksRangeSkipped)(nil),      // 4: indexer.BlocksRangeSkipped
	(*NewMasterchainBlock)(nil),     // 5: indexer.NewMasterchainBlock
	(*ShardDescription)(nil),        // 6: indexer.ShardDescription
	(*GetBlockRequest)(nil),         // 7: indexer.GetBlockRequest
	(*GetBlockResponse)(nil),        // 8: indexer.GetBlockResponse
	(*BlockNotFound)(nil),           // 9: indexer.BlockNotFound
	(*BlockFound)(nil),              // 10: indexer.BlockFound
	(*BlockChunk)(nil),              // 11: indexer.BlockChunk
	(*GetShardAccountRequest)(nil),  // 12: indexer.GetShardAccountRequest
	(*GetShardAccountResponse)(nil), // 13: indexer.GetShardAccountResponse
	(*ShardAccountNotFound)(nil),    // 14: indexer.ShardAccountNotFound
	(*ShardAccount)(nil),            // 15: indexer.ShardAccount
	(*TransactionId)(nil),           // 16: indexer.TransactionId
	(*GetLibraryCellRequest)(nil),   // 17: indexer.GetLibraryCellRequest
	(*GetLibraryCellResponse)(nil),  // 18: indexer.GetLibraryCellResponse
	(*LibraryCellNotFound)(nil),     // 19: indexer.LibraryCellNotFound
	(*LibraryCellFound)(nil),        // 20: indexer.LibraryCellFound
	(*GetLibraryCellsRequest)(nil),  // 21: indexer.GetLibraryCellsRequest
	(*GetLibraryCellsResponse)(nil), // 22: indexer.GetLibraryCellsResponse
	(*LibraryCellsBatchEntry)(nil),  // 23: indexer.LibraryCellsBatchEntry
	(*SendMessageRequest)(nil),      // 24: indexer.SendMessageRequest
	(*SendMessageResponse)(nil),     // 25: indexer.SendMessageResponse
	(*McStateInfo)(nil),             // 26: indexer.McStateInfo
	(*BlockBySeqno)(nil),            // 27: indexer.BlockBySeqno
	(*BlockById)(nil),               // 28: indexer.BlockById
	(*LatestBlock)(nil),             // 29: indexer.LatestBlock
	(*BlockId)(nil),                 // 30: indexer.BlockId
}
var file_indexer_proto_depIdxs = []int32{
	26, // 0: indexer.GetStatusResponse.mcStateInfo:type_name -> indexer.McStateInfo
	4,  // 1: indexer.WatchBlockIdsEvent.rangeSkipped:type_name -> indexer.BlocksRangeSkipped
	5,  // 2: indexer.WatchBlockIdsEvent.newMcBlock:type_name -> indexer.NewMasterchainBlock
	26, // 3: indexer.BlocksRangeSkipped.mcStateInfo:type_name -> indexer.McStateInfo
	26, // 4: indexer.NewMasterchainBlock.mcStateInfo:type_name -> indexer.McStateInfo
	30, // 5: indexer.NewMasterchainBlock.mcBlockId:type_name -> indexer.BlockId
	6,  // 6: indexer.NewMasterchainBlock.shardDescription:type_name -> indexer.ShardDescription
	30, // 7: indexer.NewMasterchainBlock.shardBlockIds:type_name -> indexer.BlockId
	30, // 8: indexer.ShardDescription.latestBlockId:type_name -> indexer.BlockId
	27, // 9: indexer.GetBlockRequest.bySeqno:type_name -> indexer.BlockBySeqno
	28, // 10: indexer.GetBlockRequest.byId:type_name -> indexer.BlockById
	9,  // 11: indexer.GetBlockResponse.notFound:type_name -> indexer.BlockNotFound
	10, // 12: indexer.GetBlockResponse.found:type_name -> indexer.BlockFound
	11, // 13: indexer.GetBlockResponse.chunk:type_name -> indexer.BlockChunk
	26, // 14: indexer.BlockNotFound.mcStateInfo:type_name -> indexer.McStateInfo
	26, // 15: indexer.BlockFound.mcStateInfo:type_name -> indexer.McStateInfo
	11, // 16: indexer.BlockFound.firstChunk:type_name -> indexer.BlockChunk
	29, // 17: indexer.GetShardAccountRequest.latest:type_name -> indexer.LatestBlock
	27, // 18: indexer.GetShardAccountRequest.bySeqno:type_name -> indexer.BlockBySeqno
	28, // 19: indexer.GetShardAccountRequest.byId:type_name -> indexer.BlockById
	9,  // 20: indexer.GetShardAccountResponse.blockNotFound:type_name -> indexer.BlockNotFound
	15, // 21: indexer.GetShardAccountResponse.accessed:type_name -> indexer.ShardAccount
	26, // 22: indexer.ShardAccountNotFound.mcStateInfo:type_name -> indexer.McStateInfo
	26, // 23: indexer.ShardAccount.mcStateInfo:type_name -> indexer.McStateInfo
	16, // 24: indexer.ShardAccount.lastTransaction:type_name -> indexer.TransactionId
	19, // 25: indexer.GetLibraryCellResponse.notFound:type_name -> indexer.LibraryCellNotFound
	20, // 26: indexer.GetLibraryCellResponse.found:type_name -> indexer.LibraryCellFound
	26, // 27: indexer.LibraryCellNotFound.mcStateInfo:type_name -> indexer.McStateInfo
	26, // 28: indexer.LibraryCellFound.mcStateInfo:type_name -> indexer.McStateInfo
	26, // 29: indexer.GetLibraryCellsResponse.mcStateInfo:type_name -> indexer.McStateInfo
	23, // 30: indexer.GetLibraryCellsResponse.entries:type_name -> indexer.LibraryCellsBatchEntry
	30, // 31: indexer.BlockById.id:type_name -> indexer.BlockId
	0,  // 32: indexer.TychoIndexer.GetStatus:input_type -> indexer.GetStatusRequest
	2,  // 33: indexer.TychoIndexer.WatchBlockIds:input_type -> indexer.WatchBlockIdsRequest
	7,  // 34: indexer.TychoIndexer.GetBlock:input_type -> indexer.GetBlockRequest
	12, // 35: indexer.TychoIndexer.GetShardAccount:input_type -> indexer.GetShardAccountRequest
	17, // 36: indexer.TychoIndexer.GetLibraryCell:input_type -> indexer.GetLibraryCellRequest
	21, // 37: indexer.TychoIndexer.GetLibraryCells:input_type -> indexer.GetLibraryCellsRequest
	24, // 38: indexer.TychoIndexer.SendMessage:input_type -> indexer.SendMessageRequest
	1,  // 39: indexer.TychoIndexer.GetStatus:output_type -> indexer.GetStatusResponse
	3,  // 40: indexer.TychoIndexer.WatchBlockIds:output_type -> indexer.WatchBlockIdsEvent
	8,  // 41: indexer.TychoIndexer.GetBlock:output_type -> indexer.GetBlockResponse
	13, // 42: indexer.TychoIndexer.GetShardAccount:output_type -> indexer.GetShardAccountResponse
	18, // 43: indexer.TychoIndexer.GetLibraryCell:output_type -> indexer.GetLibraryCellResponse
	22, // 44: indexer.TychoIndexer.GetLibraryCells:output_type -> indexer.GetLibraryCellsResponse
	25, // 45: indexer.TychoIndexer.SendMessage:output_type -> indexer.SendMessageResponse
	39, // [39:46] is the sub-list for method output_type
	32, // [32:39] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_indexer_proto_init() }
func file_indexer_proto_init() {
	if File_indexer_proto != nil {
		return
	}
	file_indexer_proto_msgTypes[1].OneofWrappers = []any{}
	file_indexer_proto_msgTypes[3].OneofWrappers = []any{
		(*WatchBlockIdsEvent_RangeSkipped)(nil),
		(*WatchBlockIdsEvent_NewMcBlock)(nil),
	}
	file_indexer_proto_msgTypes[7].OneofWrappers = []any{
		(*GetBlockRequest_BySeqno)(nil),
		(*GetBlockRequest_ById)(nil),
	}
	file_indexer_proto_msgTypes[8].OneofWrappers = []any{
		(*GetBlockResponse_NotFound)(nil),
		(*GetBlockResponse_Found)(nil),
		(*GetBlockResponse_Chunk)(nil),
	}
	file_indexer_proto_msgTypes[12].OneofWrappers = []any{
		(*GetShardAccountRequest_Latest)(nil),
		(*GetShardAccountRequest_BySeqno)(nil),
		(*GetShardAccountRequest_ById)(nil),
	}
	file_indexer_proto_msgTypes[13].OneofWrappers = []any{
		(*GetShardAccountResponse_BlockNotFound)(nil),
		(*GetShardAccountResponse_Accessed)(nil),
	}
	file_indexer_proto_msgTypes[15].OneofWrappers = []any{}
	file_indexer_proto_msgTypes[18].OneofWrappers = []any{
		(*GetLibraryCellResponse_NotFound)(nil),
		(*GetLibraryCellResponse_Found)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexer_proto_goTypes,
		DependencyIndexes: file_indexer_proto_depIdxs,
		MessageInfos:      file_indexer_proto_msgTypes,
	}.Build()
	File_indexer_proto = out.File
	file_indexer_proto_goTypes = nil
	file_indexer_proto_depIdxs = nil
}
