// Code generated - DO NOT EDIT.

package abiCocoon

const (
	CocoonAddModelTypeMsgOp                        = "CocoonAddModelType"
	CocoonAddProxyTypeMsgOp                        = "CocoonAddProxyType"
	CocoonAddWorkerTypeMsgOp                       = "CocoonAddWorkerType"
	CocoonChangeFeesMsgOp                          = "CocoonChangeFees"
	CocoonChangeOwnerMsgOp                         = "CocoonChangeOwner"
	CocoonChangeParamsMsgOp                        = "CocoonChangeParams"
	CocoonClientProxyRequestMsgOp                  = "CocoonClientProxyRequest"
	CocoonDelModelTypeMsgOp                        = "CocoonDelModelType"
	CocoonDelProxyTypeMsgOp                        = "CocoonDelProxyType"
	CocoonDelWorkerTypeMsgOp                       = "CocoonDelWorkerType"
	CocoonExtClientChargeSignedMsgOp               = "CocoonExtClientChargeSigned"
	CocoonExtClientGrantRefundSignedMsgOp          = "CocoonExtClientGrantRefundSigned"
	CocoonExtClientTopUpMsgOp                      = "CocoonExtClientTopUp"
	CocoonExtProxyCloseCompleteRequestSignedMsgOp  = "CocoonExtProxyCloseCompleteRequestSigned"
	CocoonExtProxyCloseRequestSignedMsgOp          = "CocoonExtProxyCloseRequestSigned"
	CocoonExtProxyIncreaseStakeMsgOp               = "CocoonExtProxyIncreaseStake"
	CocoonExtProxyPayoutRequestMsgOp               = "CocoonExtProxyPayoutRequest"
	CocoonOwnerClientChangeSecretHashMsgOp         = "CocoonOwnerClientChangeSecretHash"
	CocoonOwnerClientChangeSecretHashAndTopUpMsgOp = "CocoonOwnerClientChangeSecretHashAndTopUp"
	CocoonOwnerClientIncreaseStakeMsgOp            = "CocoonOwnerClientIncreaseStake"
	CocoonOwnerClientRegisterMsgOp                 = "CocoonOwnerClientRegister"
	CocoonOwnerClientRequestRefundMsgOp            = "CocoonOwnerClientRequestRefund"
	CocoonOwnerClientWithdrawMsgOp                 = "CocoonOwnerClientWithdraw"
	CocoonOwnerProxyCloseMsgOp                     = "CocoonOwnerProxyClose"
	CocoonOwnerWalletSendMessageMsgOp              = "CocoonOwnerWalletSendMessage"
	CocoonPayoutMsgOp                              = "CocoonPayout"
	CocoonRegisterProxyMsgOp                       = "CocoonRegisterProxy"
	CocoonResetRootMsgOp                           = "CocoonResetRoot"
	CocoonReturnExcessesBackMsgOp                  = "CocoonReturnExcessesBack"
	CocoonTextCmdMsgOp                             = "CocoonTextCmd"
	CocoonTextCommandMsgOp                         = "CocoonTextCommand"
	CocoonUnregisterProxyMsgOp                     = "CocoonUnregisterProxy"
	CocoonUpdateProxyMsgOp                         = "CocoonUpdateProxy"
	CocoonUpgradeCodeMsgOp                         = "CocoonUpgradeCode"
	CocoonUpgradeContractsMsgOp                    = "CocoonUpgradeContracts"
	CocoonUpgradeFullMsgOp                         = "CocoonUpgradeFull"
	CocoonWorkerProxyRequestMsgOp                  = "CocoonWorkerProxyRequest"
)
