// Code generated - DO NOT EDIT.

package abiEvaa

const (
	EvaaAddNewTokenBodyMsgOp                       = "EvaaAddNewTokenBody"
	EvaaAddToReserveBodyMsgOp                      = "EvaaAddToReserveBody"
	EvaaCancelUpgradeBodyMsgOp                     = "EvaaCancelUpgradeBody"
	EvaaClaimAssetReservesBodyMsgOp                = "EvaaClaimAssetReservesBody"
	EvaaDisableContractForUpgradeBodyMsgOp         = "EvaaDisableContractForUpgradeBody"
	EvaaDoDataChecksBodyMsgOp                      = "EvaaDoDataChecksBody"
	EvaaForceDisableContractBodyMsgOp              = "EvaaForceDisableContractBody"
	EvaaForceEnableBodyMsgOp                       = "EvaaForceEnableBody"
	EvaaGetStoreBodyMsgOp                          = "EvaaGetStoreBody"
	EvaaIdleMasterBodyMsgOp                        = "EvaaIdleMasterBody"
	EvaaIdleUserBodyMsgOp                          = "EvaaIdleUserBody"
	EvaaInitMasterBodyMsgOp                        = "EvaaInitMasterBody"
	EvaaInitUpgradeBodyMsgOp                       = "EvaaInitUpgradeBody"
	EvaaLiquidateFailBodyMsgOp                     = "EvaaLiquidateFailBody"
	EvaaLiquidateSatisfiedBodyMsgOp                = "EvaaLiquidateSatisfiedBody"
	EvaaLiquidateSuccessBodyMsgOp                  = "EvaaLiquidateSuccessBody"
	EvaaLiquidateUnsatisfiedBodyMsgOp              = "EvaaLiquidateUnsatisfiedBody"
	EvaaLiquidateUserBodyMsgOp                     = "EvaaLiquidateUserBody"
	EvaaRevertCallBodyMsgOp                        = "EvaaRevertCallBody"
	EvaaSetNewSupervisorBodyMsgOp                  = "EvaaSetNewSupervisorBody"
	EvaaSubmitUpgradeBodyMsgOp                     = "EvaaSubmitUpgradeBody"
	EvaaSupplyFailBodyMsgOp                        = "EvaaSupplyFailBody"
	EvaaSupplyMasterBodyMsgOp                      = "EvaaSupplyMasterBody"
	EvaaSupplySuccessBodyMsgOp                     = "EvaaSupplySuccessBody"
	EvaaSupplyUserBodyMsgOp                        = "EvaaSupplyUserBody"
	EvaaSupplyWithdrawFailBodyMsgOp                = "EvaaSupplyWithdrawFailBody"
	EvaaSupplyWithdrawMasterWithoutPricesBodyMsgOp = "EvaaSupplyWithdrawMasterWithoutPricesBody"
	EvaaSupplyWithdrawSatisfiedBodyMsgOp           = "EvaaSupplyWithdrawSatisfiedBody"
	EvaaSupplyWithdrawSuccessBodyMsgOp             = "EvaaSupplyWithdrawSuccessBody"
	EvaaSupplyWithdrawUnsatisfiedBodyMsgOp         = "EvaaSupplyWithdrawUnsatisfiedBody"
	EvaaSupplyWithdrawUserBodyMsgOp                = "EvaaSupplyWithdrawUserBody"
	EvaaUpdateConfigBodyMsgOp                      = "EvaaUpdateConfigBody"
	EvaaUserDoDataChecksBodyMsgOp                  = "EvaaUserDoDataChecksBody"
	EvaaUserGetStoreBodyMsgOp                      = "EvaaUserGetStoreBody"
)
