package abi

// Code autogenerated. DO NOT EDIT.

import (
	"github.com/tonkeeper/tongo/tlb"
)

var (
	// 0x00000000
	decodeFuncTonCocoonTextCmdMsgBody = decodeMsg(tlb.Tag{Val: 0x00000000, Len: 32}, TonCocoonTextCmdMsgOp, TonCocoonTextCmdMsgBody{})
	// 0x00000000
	decodeFuncTonCocoonTextCommandMsgBody = decodeMsg(tlb.Tag{Val: 0x00000000, Len: 32}, TonCocoonTextCommandMsgOp, TonCocoonTextCommandMsgBody{})
	// 0x00000003
	decodeFuncTonTep74ChangeMinterAdminMsgBody = decodeMsg(tlb.Tag{Val: 0x00000003, Len: 32}, TonTep74ChangeMinterAdminMsgOp, TonTep74ChangeMinterAdminMsgBody{})
	// 0x00000004
	decodeFuncTonTep74ChangeMinterContentMsgBody = decodeMsg(tlb.Tag{Val: 0x00000004, Len: 32}, TonTep74ChangeMinterContentMsgOp, TonTep74ChangeMinterContentMsgBody{})
	// 0x00000015
	decodeFuncTonTep74MintNewJettonsMsgBody = decodeMsg(tlb.Tag{Val: 0x00000015, Len: 32}, TonTep74MintNewJettonsMsgOp, TonTep74MintNewJettonsMsgBody{})
	// 0x022fa189
	decodeFuncTonCocoonChangeParamsMsgBody = decodeMsg(tlb.Tag{Val: 0x022fa189, Len: 32}, TonCocoonChangeParamsMsgOp, TonCocoonChangeParamsMsgBody{})
	// 0x0f8a7ea5
	decodeFuncTonTep74AskToTransferMsgBody = decodeMsg(tlb.Tag{Val: 0x0f8a7ea5, Len: 32}, TonTep74AskToTransferMsgOp, TonTep74AskToTransferMsgBody{})
	// 0x11aefd51
	decodeFuncTonCocoonUpgradeCodeMsgBody = decodeMsg(tlb.Tag{Val: 0x11aefd51, Len: 32}, TonCocoonUpgradeCodeMsgOp, TonCocoonUpgradeCodeMsgBody{})
	// 0x178d4519
	decodeFuncTonTep74InternalTransferStepMsgBody = decodeMsg(tlb.Tag{Val: 0x178d4519, Len: 32}, TonTep74InternalTransferStepMsgOp, TonTep74InternalTransferStepMsgBody{})
	// 0x26ed7f65
	decodeFuncTonCocoonOwnerWorkerRegisterMsgBody = decodeMsg(tlb.Tag{Val: 0x26ed7f65, Len: 32}, TonCocoonOwnerWorkerRegisterMsgOp, TonCocoonOwnerWorkerRegisterMsgBody{})
	// 0x2c76b973
	decodeFuncTonTep74RequestWalletAddressMsgBody = decodeMsg(tlb.Tag{Val: 0x2c76b973, Len: 32}, TonTep74RequestWalletAddressMsgOp, TonTep74RequestWalletAddressMsgBody{})
	// 0x3c41d0b2
	decodeFuncTonCocoonDelProxyTypeMsgBody = decodeMsg(tlb.Tag{Val: 0x3c41d0b2, Len: 32}, TonCocoonDelProxyTypeMsgOp, TonCocoonDelProxyTypeMsgBody{})
	// 0x4d725d2c
	decodeFuncTonCocoonWorkerProxyRequestMsgBody = decodeMsg(tlb.Tag{Val: 0x4d725d2c, Len: 32}, TonCocoonWorkerProxyRequestMsgOp, TonCocoonWorkerProxyRequestMsgBody{})
	// 0x4f7c5789
	decodeFuncTonCocoonUpgradeFullMsgBody = decodeMsg(tlb.Tag{Val: 0x4f7c5789, Len: 32}, TonCocoonUpgradeFullMsgOp, TonCocoonUpgradeFullMsgBody{})
	// 0x563c1d96
	decodeFuncTonCocoonResetRootMsgBody = decodeMsg(tlb.Tag{Val: 0x563c1d96, Len: 32}, TonCocoonResetRootMsgOp, TonCocoonResetRootMsgBody{})
	// 0x595f07bc
	decodeFuncTonTep74AskToBurnMsgBody = decodeMsg(tlb.Tag{Val: 0x595f07bc, Len: 32}, TonTep74AskToBurnMsgOp, TonTep74AskToBurnMsgBody{})
	// 0x636a4391
	decodeFuncTonCocoonExtProxyCloseRequestSignedMsgBody = decodeMsg(tlb.Tag{Val: 0x636a4391, Len: 32}, TonCocoonExtProxyCloseRequestSignedMsgOp, TonCocoonExtProxyCloseRequestSignedMsgBody{})
	// 0x65448ff4
	decodeFuncTonCocoonClientProxyRequestMsgBody = decodeMsg(tlb.Tag{Val: 0x65448ff4, Len: 32}, TonCocoonClientProxyRequestMsgOp, TonCocoonClientProxyRequestMsgBody{})
	// 0x6a1f6a60
	decodeFuncTonCocoonOwnerClientIncreaseStakeMsgBody = decodeMsg(tlb.Tag{Val: 0x6a1f6a60, Len: 32}, TonCocoonOwnerClientIncreaseStakeMsgOp, TonCocoonOwnerClientIncreaseStakeMsgBody{})
	// 0x6d49eaf2
	decodeFuncTonCocoonUnregisterProxyMsgBody = decodeMsg(tlb.Tag{Val: 0x6d49eaf2, Len: 32}, TonCocoonUnregisterProxyMsgOp, TonCocoonUnregisterProxyMsgBody{})
	// 0x71860e80
	decodeFuncTonCocoonAddProxyTypeMsgBody = decodeMsg(tlb.Tag{Val: 0x71860e80, Len: 32}, TonCocoonAddProxyTypeMsgOp, TonCocoonAddProxyTypeMsgBody{})
	// 0x7362d09c
	decodeFuncTonTep74TransferNotificationForRecipientMsgBody = decodeMsg(tlb.Tag{Val: 0x7362d09c, Len: 32}, TonTep74TransferNotificationForRecipientMsgOp, TonTep74TransferNotificationForRecipientMsgBody{})
	// 0x7610e6eb
	decodeFuncTonCocoonExtProxyPayoutRequestMsgBody = decodeMsg(tlb.Tag{Val: 0x7610e6eb, Len: 32}, TonCocoonExtProxyPayoutRequestMsgOp, TonCocoonExtProxyPayoutRequestMsgBody{})
	// 0x7bdd97de
	decodeFuncTonTep74BurnNotificationForMinterMsgBody = decodeMsg(tlb.Tag{Val: 0x7bdd97de, Len: 32}, TonTep74BurnNotificationForMinterMsgOp, TonTep74BurnNotificationForMinterMsgBody{})
	// 0x8473b408
	decodeFuncTonCocoonOwnerClientChangeSecretHashAndTopUpMsgBody = decodeMsg(tlb.Tag{Val: 0x8473b408, Len: 32}, TonCocoonOwnerClientChangeSecretHashAndTopUpMsgOp, TonCocoonOwnerClientChangeSecretHashAndTopUpMsgBody{})
	// 0x8d94a79a
	decodeFuncTonCocoonDelWorkerTypeMsgBody = decodeMsg(tlb.Tag{Val: 0x8d94a79a, Len: 32}, TonCocoonDelWorkerTypeMsgOp, TonCocoonDelWorkerTypeMsgBody{})
	// 0x927c7cb5
	decodeFuncTonCocoonRegisterProxyMsgBody = decodeMsg(tlb.Tag{Val: 0x927c7cb5, Len: 32}, TonCocoonRegisterProxyMsgOp, TonCocoonRegisterProxyMsgBody{})
	// 0x92b11c18
	decodeFuncTonCocoonDelModelTypeMsgBody = decodeMsg(tlb.Tag{Val: 0x92b11c18, Len: 32}, TonCocoonDelModelTypeMsgOp, TonCocoonDelModelTypeMsgBody{})
	// 0x9713f187
	decodeFuncTonCocoonExtProxyIncreaseStakeMsgBody = decodeMsg(tlb.Tag{Val: 0x9713f187, Len: 32}, TonCocoonExtProxyIncreaseStakeMsgOp, TonCocoonExtProxyIncreaseStakeMsgBody{})
	// 0x9c69f376
	decodeFuncTonCocoonOwnerWalletSendMessageMsgBody = decodeMsg(tlb.Tag{Val: 0x9c69f376, Len: 32}, TonCocoonOwnerWalletSendMessageMsgOp, TonCocoonOwnerWalletSendMessageMsgBody{})
	// 0x9c7924ba
	decodeFuncTonCocoonUpdateProxyMsgBody = decodeMsg(tlb.Tag{Val: 0x9c7924ba, Len: 32}, TonCocoonUpdateProxyMsgOp, TonCocoonUpdateProxyMsgBody{})
	// 0xa040ad28
	decodeFuncTonCocoonExtWorkerPayoutRequestSignedMsgBody = decodeMsg(tlb.Tag{Val: 0xa040ad28, Len: 32}, TonCocoonExtWorkerPayoutRequestSignedMsgOp, TonCocoonExtWorkerPayoutRequestSignedMsgBody{})
	// 0xa2370f61
	decodeFuncTonCocoonUpgradeContractsMsgBody = decodeMsg(tlb.Tag{Val: 0xa2370f61, Len: 32}, TonCocoonUpgradeContractsMsgOp, TonCocoonUpgradeContractsMsgBody{})
	// 0xa9357034
	decodeFuncTonCocoonOwnerClientChangeSecretHashMsgBody = decodeMsg(tlb.Tag{Val: 0xa9357034, Len: 32}, TonCocoonOwnerClientChangeSecretHashMsgOp, TonCocoonOwnerClientChangeSecretHashMsgBody{})
	// 0xb51d5a01
	decodeFuncTonCocoonOwnerProxyCloseMsgBody = decodeMsg(tlb.Tag{Val: 0xb51d5a01, Len: 32}, TonCocoonOwnerProxyCloseMsgOp, TonCocoonOwnerProxyCloseMsgBody{})
	// 0xbb63ff93
	decodeFuncTonCocoonExtClientChargeSignedMsgBody = decodeMsg(tlb.Tag{Val: 0xbb63ff93, Len: 32}, TonCocoonExtClientChargeSignedMsgOp, TonCocoonExtClientChargeSignedMsgBody{})
	// 0xc146134d
	decodeFuncTonCocoonAddModelTypeMsgBody = decodeMsg(tlb.Tag{Val: 0xc146134d, Len: 32}, TonCocoonAddModelTypeMsgOp, TonCocoonAddModelTypeMsgBody{})
	// 0xc45f9f3b
	decodeFuncTonCocoonOwnerClientRegisterMsgBody = decodeMsg(tlb.Tag{Val: 0xc45f9f3b, Len: 32}, TonCocoonOwnerClientRegisterMsgOp, TonCocoonOwnerClientRegisterMsgBody{})
	// 0xc4a1ae54
	decodeFuncTonCocoonChangeOwnerMsgBody = decodeMsg(tlb.Tag{Val: 0xc4a1ae54, Len: 32}, TonCocoonChangeOwnerMsgOp, TonCocoonChangeOwnerMsgBody{})
	// 0xc52ed8d4
	decodeFuncTonCocoonChangeFeesMsgBody = decodeMsg(tlb.Tag{Val: 0xc52ed8d4, Len: 32}, TonCocoonChangeFeesMsgOp, TonCocoonChangeFeesMsgBody{})
	// 0xc59a7cd3
	decodeFuncTonCocoonPayoutMsgBody = decodeMsg(tlb.Tag{Val: 0xc59a7cd3, Len: 32}, TonCocoonPayoutMsgOp, TonCocoonPayoutMsgBody{})
	// 0xd1735400
	decodeFuncTonTep74ResponseWalletAddressMsgBody = decodeMsg(tlb.Tag{Val: 0xd1735400, Len: 32}, TonTep74ResponseWalletAddressMsgOp, TonTep74ResponseWalletAddressMsgBody{})
	// 0xd53276db
	decodeFuncTonCocoonReturnExcessesBackMsgBody = decodeMsg(tlb.Tag{Val: 0xd53276db, Len: 32}, TonCocoonReturnExcessesBackMsgOp, TonCocoonReturnExcessesBackMsgBody{})
	// 0xd53276db
	decodeFuncTonTep74ReturnExcessesBackMsgBody = decodeMsg(tlb.Tag{Val: 0xd53276db, Len: 32}, TonTep74ReturnExcessesBackMsgOp, TonTep74ReturnExcessesBackMsgBody{})
	// 0xd53276db
	decodeFuncTonTep74AboaLisaMsgBody = decodeMsg(tlb.Tag{Val: 0xd53276db, Len: 32}, TonTep74AboaLisaMsgOp, TonTep74AboaLisaMsgBody{})
	// 0xda068e78
	decodeFuncTonCocoonOwnerClientWithdrawMsgBody = decodeMsg(tlb.Tag{Val: 0xda068e78, Len: 32}, TonCocoonOwnerClientWithdrawMsgOp, TonCocoonOwnerClientWithdrawMsgBody{})
	// 0xe34b1c60
	decodeFuncTonCocoonAddWorkerTypeMsgBody = decodeMsg(tlb.Tag{Val: 0xe34b1c60, Len: 32}, TonCocoonAddWorkerTypeMsgOp, TonCocoonAddWorkerTypeMsgBody{})
	// 0xe511abc7
	decodeFuncTonCocoonExtProxyCloseCompleteRequestSignedMsgBody = decodeMsg(tlb.Tag{Val: 0xe511abc7, Len: 32}, TonCocoonExtProxyCloseCompleteRequestSignedMsgOp, TonCocoonExtProxyCloseCompleteRequestSignedMsgBody{})
	// 0xefd711e1
	decodeFuncTonCocoonExtClientGrantRefundSignedMsgBody = decodeMsg(tlb.Tag{Val: 0xefd711e1, Len: 32}, TonCocoonExtClientGrantRefundSignedMsgOp, TonCocoonExtClientGrantRefundSignedMsgBody{})
	// 0xf172e6c2
	decodeFuncTonCocoonExtClientTopUpMsgBody = decodeMsg(tlb.Tag{Val: 0xf172e6c2, Len: 32}, TonCocoonExtClientTopUpMsgOp, TonCocoonExtClientTopUpMsgBody{})
	// 0xf5f26a36
	decodeFuncTonCocoonExtWorkerLastPayoutRequestSignedMsgBody = decodeMsg(tlb.Tag{Val: 0xf5f26a36, Len: 32}, TonCocoonExtWorkerLastPayoutRequestSignedMsgOp, TonCocoonExtWorkerLastPayoutRequestSignedMsgBody{})
	// 0xfafa6cc1
	decodeFuncTonCocoonOwnerClientRequestRefundMsgBody = decodeMsg(tlb.Tag{Val: 0xfafa6cc1, Len: 32}, TonCocoonOwnerClientRequestRefundMsgOp, TonCocoonOwnerClientRequestRefundMsgBody{})
)

var opcodedMsgInDecodeFunctions = map[uint32]msgDecoderFunc{

	//TonCocoonTextCmd, TonCocoonTextCommand,
	0x00000000: decodeMultipleMsgs([]msgDecoderFunc{
		decodeFuncTonCocoonTextCmdMsgBody,
		decodeFuncTonCocoonTextCommandMsgBody},
		"0x00000000",
	),

	// 0x00000003
	TonTep74ChangeMinterAdminMsgOpCode: decodeFuncTonTep74ChangeMinterAdminMsgBody,

	// 0x00000004
	TonTep74ChangeMinterContentMsgOpCode: decodeFuncTonTep74ChangeMinterContentMsgBody,

	// 0x00000015
	TonTep74MintNewJettonsMsgOpCode: decodeFuncTonTep74MintNewJettonsMsgBody,

	// 0x022fa189
	TonCocoonChangeParamsMsgOpCode: decodeFuncTonCocoonChangeParamsMsgBody,

	// 0x0f8a7ea5
	TonTep74AskToTransferMsgOpCode: decodeFuncTonTep74AskToTransferMsgBody,

	// 0x11aefd51
	TonCocoonUpgradeCodeMsgOpCode: decodeFuncTonCocoonUpgradeCodeMsgBody,

	// 0x178d4519
	TonTep74InternalTransferStepMsgOpCode: decodeFuncTonTep74InternalTransferStepMsgBody,

	// 0x26ed7f65
	TonCocoonOwnerWorkerRegisterMsgOpCode: decodeFuncTonCocoonOwnerWorkerRegisterMsgBody,

	// 0x2c76b973
	TonTep74RequestWalletAddressMsgOpCode: decodeFuncTonTep74RequestWalletAddressMsgBody,

	// 0x3c41d0b2
	TonCocoonDelProxyTypeMsgOpCode: decodeFuncTonCocoonDelProxyTypeMsgBody,

	// 0x4d725d2c
	TonCocoonWorkerProxyRequestMsgOpCode: decodeFuncTonCocoonWorkerProxyRequestMsgBody,

	// 0x4f7c5789
	TonCocoonUpgradeFullMsgOpCode: decodeFuncTonCocoonUpgradeFullMsgBody,

	// 0x563c1d96
	TonCocoonResetRootMsgOpCode: decodeFuncTonCocoonResetRootMsgBody,

	// 0x595f07bc
	TonTep74AskToBurnMsgOpCode: decodeFuncTonTep74AskToBurnMsgBody,

	// 0x636a4391
	TonCocoonExtProxyCloseRequestSignedMsgOpCode: decodeFuncTonCocoonExtProxyCloseRequestSignedMsgBody,

	// 0x65448ff4
	TonCocoonClientProxyRequestMsgOpCode: decodeFuncTonCocoonClientProxyRequestMsgBody,

	// 0x6a1f6a60
	TonCocoonOwnerClientIncreaseStakeMsgOpCode: decodeFuncTonCocoonOwnerClientIncreaseStakeMsgBody,

	// 0x6d49eaf2
	TonCocoonUnregisterProxyMsgOpCode: decodeFuncTonCocoonUnregisterProxyMsgBody,

	// 0x71860e80
	TonCocoonAddProxyTypeMsgOpCode: decodeFuncTonCocoonAddProxyTypeMsgBody,

	// 0x7362d09c
	TonTep74TransferNotificationForRecipientMsgOpCode: decodeFuncTonTep74TransferNotificationForRecipientMsgBody,

	// 0x7610e6eb
	TonCocoonExtProxyPayoutRequestMsgOpCode: decodeFuncTonCocoonExtProxyPayoutRequestMsgBody,

	// 0x7bdd97de
	TonTep74BurnNotificationForMinterMsgOpCode: decodeFuncTonTep74BurnNotificationForMinterMsgBody,

	// 0x8473b408
	TonCocoonOwnerClientChangeSecretHashAndTopUpMsgOpCode: decodeFuncTonCocoonOwnerClientChangeSecretHashAndTopUpMsgBody,

	// 0x8d94a79a
	TonCocoonDelWorkerTypeMsgOpCode: decodeFuncTonCocoonDelWorkerTypeMsgBody,

	// 0x927c7cb5
	TonCocoonRegisterProxyMsgOpCode: decodeFuncTonCocoonRegisterProxyMsgBody,

	// 0x92b11c18
	TonCocoonDelModelTypeMsgOpCode: decodeFuncTonCocoonDelModelTypeMsgBody,

	// 0x9713f187
	TonCocoonExtProxyIncreaseStakeMsgOpCode: decodeFuncTonCocoonExtProxyIncreaseStakeMsgBody,

	// 0x9c69f376
	TonCocoonOwnerWalletSendMessageMsgOpCode: decodeFuncTonCocoonOwnerWalletSendMessageMsgBody,

	// 0x9c7924ba
	TonCocoonUpdateProxyMsgOpCode: decodeFuncTonCocoonUpdateProxyMsgBody,

	// 0xa040ad28
	TonCocoonExtWorkerPayoutRequestSignedMsgOpCode: decodeFuncTonCocoonExtWorkerPayoutRequestSignedMsgBody,

	// 0xa2370f61
	TonCocoonUpgradeContractsMsgOpCode: decodeFuncTonCocoonUpgradeContractsMsgBody,

	// 0xa9357034
	TonCocoonOwnerClientChangeSecretHashMsgOpCode: decodeFuncTonCocoonOwnerClientChangeSecretHashMsgBody,

	// 0xb51d5a01
	TonCocoonOwnerProxyCloseMsgOpCode: decodeFuncTonCocoonOwnerProxyCloseMsgBody,

	// 0xbb63ff93
	TonCocoonExtClientChargeSignedMsgOpCode: decodeFuncTonCocoonExtClientChargeSignedMsgBody,

	// 0xc146134d
	TonCocoonAddModelTypeMsgOpCode: decodeFuncTonCocoonAddModelTypeMsgBody,

	// 0xc45f9f3b
	TonCocoonOwnerClientRegisterMsgOpCode: decodeFuncTonCocoonOwnerClientRegisterMsgBody,

	// 0xc4a1ae54
	TonCocoonChangeOwnerMsgOpCode: decodeFuncTonCocoonChangeOwnerMsgBody,

	// 0xc52ed8d4
	TonCocoonChangeFeesMsgOpCode: decodeFuncTonCocoonChangeFeesMsgBody,

	// 0xc59a7cd3
	TonCocoonPayoutMsgOpCode: decodeFuncTonCocoonPayoutMsgBody,

	// 0xd1735400
	TonTep74ResponseWalletAddressMsgOpCode: decodeFuncTonTep74ResponseWalletAddressMsgBody,

	//TonCocoonReturnExcessesBack, TonTep74ReturnExcessesBack, TonTep74AboaLisa,
	0xd53276db: decodeMultipleMsgs([]msgDecoderFunc{
		decodeFuncTonCocoonReturnExcessesBackMsgBody,
		decodeFuncTonTep74ReturnExcessesBackMsgBody,
		decodeFuncTonTep74AboaLisaMsgBody},
		"0xd53276db",
	),

	// 0xda068e78
	TonCocoonOwnerClientWithdrawMsgOpCode: decodeFuncTonCocoonOwnerClientWithdrawMsgBody,

	// 0xe34b1c60
	TonCocoonAddWorkerTypeMsgOpCode: decodeFuncTonCocoonAddWorkerTypeMsgBody,

	// 0xe511abc7
	TonCocoonExtProxyCloseCompleteRequestSignedMsgOpCode: decodeFuncTonCocoonExtProxyCloseCompleteRequestSignedMsgBody,

	// 0xefd711e1
	TonCocoonExtClientGrantRefundSignedMsgOpCode: decodeFuncTonCocoonExtClientGrantRefundSignedMsgBody,

	// 0xf172e6c2
	TonCocoonExtClientTopUpMsgOpCode: decodeFuncTonCocoonExtClientTopUpMsgBody,

	// 0xf5f26a36
	TonCocoonExtWorkerLastPayoutRequestSignedMsgOpCode: decodeFuncTonCocoonExtWorkerLastPayoutRequestSignedMsgBody,

	// 0xfafa6cc1
	TonCocoonOwnerClientRequestRefundMsgOpCode: decodeFuncTonCocoonOwnerClientRequestRefundMsgBody,
}

const (
	TonCocoonTextCmdMsgOp                             MsgOpName = "TonCocoonTextCmd"
	TonCocoonTextCommandMsgOp                         MsgOpName = "TonCocoonTextCommand"
	TonTep74ChangeMinterAdminMsgOp                    MsgOpName = "TonTep74ChangeMinterAdmin"
	TonTep74ChangeMinterContentMsgOp                  MsgOpName = "TonTep74ChangeMinterContent"
	TonTep74MintNewJettonsMsgOp                       MsgOpName = "TonTep74MintNewJettons"
	TonCocoonChangeParamsMsgOp                        MsgOpName = "TonCocoonChangeParams"
	TonTep74AskToTransferMsgOp                        MsgOpName = "TonTep74AskToTransfer"
	TonCocoonUpgradeCodeMsgOp                         MsgOpName = "TonCocoonUpgradeCode"
	TonTep74InternalTransferStepMsgOp                 MsgOpName = "TonTep74InternalTransferStep"
	TonCocoonOwnerWorkerRegisterMsgOp                 MsgOpName = "TonCocoonOwnerWorkerRegister"
	TonTep74RequestWalletAddressMsgOp                 MsgOpName = "TonTep74RequestWalletAddress"
	TonCocoonDelProxyTypeMsgOp                        MsgOpName = "TonCocoonDelProxyType"
	TonCocoonWorkerProxyRequestMsgOp                  MsgOpName = "TonCocoonWorkerProxyRequest"
	TonCocoonUpgradeFullMsgOp                         MsgOpName = "TonCocoonUpgradeFull"
	TonCocoonResetRootMsgOp                           MsgOpName = "TonCocoonResetRoot"
	TonTep74AskToBurnMsgOp                            MsgOpName = "TonTep74AskToBurn"
	TonCocoonExtProxyCloseRequestSignedMsgOp          MsgOpName = "TonCocoonExtProxyCloseRequestSigned"
	TonCocoonClientProxyRequestMsgOp                  MsgOpName = "TonCocoonClientProxyRequest"
	TonCocoonOwnerClientIncreaseStakeMsgOp            MsgOpName = "TonCocoonOwnerClientIncreaseStake"
	TonCocoonUnregisterProxyMsgOp                     MsgOpName = "TonCocoonUnregisterProxy"
	TonCocoonAddProxyTypeMsgOp                        MsgOpName = "TonCocoonAddProxyType"
	TonTep74TransferNotificationForRecipientMsgOp     MsgOpName = "TonTep74TransferNotificationForRecipient"
	TonCocoonExtProxyPayoutRequestMsgOp               MsgOpName = "TonCocoonExtProxyPayoutRequest"
	TonTep74BurnNotificationForMinterMsgOp            MsgOpName = "TonTep74BurnNotificationForMinter"
	TonCocoonOwnerClientChangeSecretHashAndTopUpMsgOp MsgOpName = "TonCocoonOwnerClientChangeSecretHashAndTopUp"
	TonCocoonDelWorkerTypeMsgOp                       MsgOpName = "TonCocoonDelWorkerType"
	TonCocoonRegisterProxyMsgOp                       MsgOpName = "TonCocoonRegisterProxy"
	TonCocoonDelModelTypeMsgOp                        MsgOpName = "TonCocoonDelModelType"
	TonCocoonExtProxyIncreaseStakeMsgOp               MsgOpName = "TonCocoonExtProxyIncreaseStake"
	TonCocoonOwnerWalletSendMessageMsgOp              MsgOpName = "TonCocoonOwnerWalletSendMessage"
	TonCocoonUpdateProxyMsgOp                         MsgOpName = "TonCocoonUpdateProxy"
	TonCocoonExtWorkerPayoutRequestSignedMsgOp        MsgOpName = "TonCocoonExtWorkerPayoutRequestSigned"
	TonCocoonUpgradeContractsMsgOp                    MsgOpName = "TonCocoonUpgradeContracts"
	TonCocoonOwnerClientChangeSecretHashMsgOp         MsgOpName = "TonCocoonOwnerClientChangeSecretHash"
	TonCocoonOwnerProxyCloseMsgOp                     MsgOpName = "TonCocoonOwnerProxyClose"
	TonCocoonExtClientChargeSignedMsgOp               MsgOpName = "TonCocoonExtClientChargeSigned"
	TonCocoonAddModelTypeMsgOp                        MsgOpName = "TonCocoonAddModelType"
	TonCocoonOwnerClientRegisterMsgOp                 MsgOpName = "TonCocoonOwnerClientRegister"
	TonCocoonChangeOwnerMsgOp                         MsgOpName = "TonCocoonChangeOwner"
	TonCocoonChangeFeesMsgOp                          MsgOpName = "TonCocoonChangeFees"
	TonCocoonPayoutMsgOp                              MsgOpName = "TonCocoonPayout"
	TonTep74ResponseWalletAddressMsgOp                MsgOpName = "TonTep74ResponseWalletAddress"
	TonCocoonReturnExcessesBackMsgOp                  MsgOpName = "TonCocoonReturnExcessesBack"
	TonTep74ReturnExcessesBackMsgOp                   MsgOpName = "TonTep74ReturnExcessesBack"
	TonTep74AboaLisaMsgOp                             MsgOpName = "TonTep74AboaLisa"
	TonCocoonOwnerClientWithdrawMsgOp                 MsgOpName = "TonCocoonOwnerClientWithdraw"
	TonCocoonAddWorkerTypeMsgOp                       MsgOpName = "TonCocoonAddWorkerType"
	TonCocoonExtProxyCloseCompleteRequestSignedMsgOp  MsgOpName = "TonCocoonExtProxyCloseCompleteRequestSigned"
	TonCocoonExtClientGrantRefundSignedMsgOp          MsgOpName = "TonCocoonExtClientGrantRefundSigned"
	TonCocoonExtClientTopUpMsgOp                      MsgOpName = "TonCocoonExtClientTopUp"
	TonCocoonExtWorkerLastPayoutRequestSignedMsgOp    MsgOpName = "TonCocoonExtWorkerLastPayoutRequestSigned"
	TonCocoonOwnerClientRequestRefundMsgOp            MsgOpName = "TonCocoonOwnerClientRequestRefund"
)

const (
	TonCocoonTextCmdMsgOpCode                             MsgOpCode = 0x00000000
	TonCocoonTextCommandMsgOpCode                         MsgOpCode = 0x00000000
	TonTep74ChangeMinterAdminMsgOpCode                    MsgOpCode = 0x00000003
	TonTep74ChangeMinterContentMsgOpCode                  MsgOpCode = 0x00000004
	TonTep74MintNewJettonsMsgOpCode                       MsgOpCode = 0x00000015
	TonCocoonChangeParamsMsgOpCode                        MsgOpCode = 0x022fa189
	TonTep74AskToTransferMsgOpCode                        MsgOpCode = 0x0f8a7ea5
	TonCocoonUpgradeCodeMsgOpCode                         MsgOpCode = 0x11aefd51
	TonTep74InternalTransferStepMsgOpCode                 MsgOpCode = 0x178d4519
	TonCocoonOwnerWorkerRegisterMsgOpCode                 MsgOpCode = 0x26ed7f65
	TonTep74RequestWalletAddressMsgOpCode                 MsgOpCode = 0x2c76b973
	TonCocoonDelProxyTypeMsgOpCode                        MsgOpCode = 0x3c41d0b2
	TonCocoonWorkerProxyRequestMsgOpCode                  MsgOpCode = 0x4d725d2c
	TonCocoonUpgradeFullMsgOpCode                         MsgOpCode = 0x4f7c5789
	TonCocoonResetRootMsgOpCode                           MsgOpCode = 0x563c1d96
	TonTep74AskToBurnMsgOpCode                            MsgOpCode = 0x595f07bc
	TonCocoonExtProxyCloseRequestSignedMsgOpCode          MsgOpCode = 0x636a4391
	TonCocoonClientProxyRequestMsgOpCode                  MsgOpCode = 0x65448ff4
	TonCocoonOwnerClientIncreaseStakeMsgOpCode            MsgOpCode = 0x6a1f6a60
	TonCocoonUnregisterProxyMsgOpCode                     MsgOpCode = 0x6d49eaf2
	TonCocoonAddProxyTypeMsgOpCode                        MsgOpCode = 0x71860e80
	TonTep74TransferNotificationForRecipientMsgOpCode     MsgOpCode = 0x7362d09c
	TonCocoonExtProxyPayoutRequestMsgOpCode               MsgOpCode = 0x7610e6eb
	TonTep74BurnNotificationForMinterMsgOpCode            MsgOpCode = 0x7bdd97de
	TonCocoonOwnerClientChangeSecretHashAndTopUpMsgOpCode MsgOpCode = 0x8473b408
	TonCocoonDelWorkerTypeMsgOpCode                       MsgOpCode = 0x8d94a79a
	TonCocoonRegisterProxyMsgOpCode                       MsgOpCode = 0x927c7cb5
	TonCocoonDelModelTypeMsgOpCode                        MsgOpCode = 0x92b11c18
	TonCocoonExtProxyIncreaseStakeMsgOpCode               MsgOpCode = 0x9713f187
	TonCocoonOwnerWalletSendMessageMsgOpCode              MsgOpCode = 0x9c69f376
	TonCocoonUpdateProxyMsgOpCode                         MsgOpCode = 0x9c7924ba
	TonCocoonExtWorkerPayoutRequestSignedMsgOpCode        MsgOpCode = 0xa040ad28
	TonCocoonUpgradeContractsMsgOpCode                    MsgOpCode = 0xa2370f61
	TonCocoonOwnerClientChangeSecretHashMsgOpCode         MsgOpCode = 0xa9357034
	TonCocoonOwnerProxyCloseMsgOpCode                     MsgOpCode = 0xb51d5a01
	TonCocoonExtClientChargeSignedMsgOpCode               MsgOpCode = 0xbb63ff93
	TonCocoonAddModelTypeMsgOpCode                        MsgOpCode = 0xc146134d
	TonCocoonOwnerClientRegisterMsgOpCode                 MsgOpCode = 0xc45f9f3b
	TonCocoonChangeOwnerMsgOpCode                         MsgOpCode = 0xc4a1ae54
	TonCocoonChangeFeesMsgOpCode                          MsgOpCode = 0xc52ed8d4
	TonCocoonPayoutMsgOpCode                              MsgOpCode = 0xc59a7cd3
	TonTep74ResponseWalletAddressMsgOpCode                MsgOpCode = 0xd1735400
	TonCocoonReturnExcessesBackMsgOpCode                  MsgOpCode = 0xd53276db
	TonTep74ReturnExcessesBackMsgOpCode                   MsgOpCode = 0xd53276db
	TonTep74AboaLisaMsgOpCode                             MsgOpCode = 0xd53276db
	TonCocoonOwnerClientWithdrawMsgOpCode                 MsgOpCode = 0xda068e78
	TonCocoonAddWorkerTypeMsgOpCode                       MsgOpCode = 0xe34b1c60
	TonCocoonExtProxyCloseCompleteRequestSignedMsgOpCode  MsgOpCode = 0xe511abc7
	TonCocoonExtClientGrantRefundSignedMsgOpCode          MsgOpCode = 0xefd711e1
	TonCocoonExtClientTopUpMsgOpCode                      MsgOpCode = 0xf172e6c2
	TonCocoonExtWorkerLastPayoutRequestSignedMsgOpCode    MsgOpCode = 0xf5f26a36
	TonCocoonOwnerClientRequestRefundMsgOpCode            MsgOpCode = 0xfafa6cc1
)

type TonCocoonTextCmdMsgBody = TonCocoonTextCmd

type TonCocoonTextCommandMsgBody = TonCocoonTextCommand

type TonTep74ChangeMinterAdminMsgBody = TonTep74ChangeMinterAdmin

type TonTep74ChangeMinterContentMsgBody = TonTep74ChangeMinterContent

type TonTep74MintNewJettonsMsgBody = TonTep74MintNewJettons

type TonCocoonChangeParamsMsgBody = TonCocoonChangeParams

type TonTep74AskToTransferMsgBody = TonTep74AskToTransfer

type TonCocoonUpgradeCodeMsgBody = TonCocoonUpgradeCode

type TonTep74InternalTransferStepMsgBody = TonTep74InternalTransferStep

type TonCocoonOwnerWorkerRegisterMsgBody = TonCocoonOwnerWorkerRegister

type TonTep74RequestWalletAddressMsgBody = TonTep74RequestWalletAddress

type TonCocoonDelProxyTypeMsgBody = TonCocoonDelProxyType

type TonCocoonWorkerProxyRequestMsgBody = TonCocoonWorkerProxyRequest

type TonCocoonUpgradeFullMsgBody = TonCocoonUpgradeFull

type TonCocoonResetRootMsgBody = TonCocoonResetRoot

type TonTep74AskToBurnMsgBody = TonTep74AskToBurn

type TonCocoonExtProxyCloseRequestSignedMsgBody = TonCocoonExtProxyCloseRequestSigned

type TonCocoonClientProxyRequestMsgBody = TonCocoonClientProxyRequest

type TonCocoonOwnerClientIncreaseStakeMsgBody = TonCocoonOwnerClientIncreaseStake

type TonCocoonUnregisterProxyMsgBody = TonCocoonUnregisterProxy

type TonCocoonAddProxyTypeMsgBody = TonCocoonAddProxyType

type TonTep74TransferNotificationForRecipientMsgBody = TonTep74TransferNotificationForRecipient

type TonCocoonExtProxyPayoutRequestMsgBody = TonCocoonExtProxyPayoutRequest

type TonTep74BurnNotificationForMinterMsgBody = TonTep74BurnNotificationForMinter

type TonCocoonOwnerClientChangeSecretHashAndTopUpMsgBody = TonCocoonOwnerClientChangeSecretHashAndTopUp

type TonCocoonDelWorkerTypeMsgBody = TonCocoonDelWorkerType

type TonCocoonRegisterProxyMsgBody = TonCocoonRegisterProxy

type TonCocoonDelModelTypeMsgBody = TonCocoonDelModelType

type TonCocoonExtProxyIncreaseStakeMsgBody = TonCocoonExtProxyIncreaseStake

type TonCocoonOwnerWalletSendMessageMsgBody = TonCocoonOwnerWalletSendMessage

type TonCocoonUpdateProxyMsgBody = TonCocoonUpdateProxy

type TonCocoonExtWorkerPayoutRequestSignedMsgBody = TonCocoonExtWorkerPayoutRequestSigned

type TonCocoonUpgradeContractsMsgBody = TonCocoonUpgradeContracts

type TonCocoonOwnerClientChangeSecretHashMsgBody = TonCocoonOwnerClientChangeSecretHash

type TonCocoonOwnerProxyCloseMsgBody = TonCocoonOwnerProxyClose

type TonCocoonExtClientChargeSignedMsgBody = TonCocoonExtClientChargeSigned

type TonCocoonAddModelTypeMsgBody = TonCocoonAddModelType

type TonCocoonOwnerClientRegisterMsgBody = TonCocoonOwnerClientRegister

type TonCocoonChangeOwnerMsgBody = TonCocoonChangeOwner

type TonCocoonChangeFeesMsgBody = TonCocoonChangeFees

type TonCocoonPayoutMsgBody = TonCocoonPayout

type TonTep74ResponseWalletAddressMsgBody = TonTep74ResponseWalletAddress

type TonCocoonReturnExcessesBackMsgBody = TonCocoonReturnExcessesBack

type TonTep74ReturnExcessesBackMsgBody = TonTep74ReturnExcessesBack

type TonTep74AboaLisaMsgBody = TonTep74AboaLisa

type TonCocoonOwnerClientWithdrawMsgBody = TonCocoonOwnerClientWithdraw

type TonCocoonAddWorkerTypeMsgBody = TonCocoonAddWorkerType

type TonCocoonExtProxyCloseCompleteRequestSignedMsgBody = TonCocoonExtProxyCloseCompleteRequestSigned

type TonCocoonExtClientGrantRefundSignedMsgBody = TonCocoonExtClientGrantRefundSigned

type TonCocoonExtClientTopUpMsgBody = TonCocoonExtClientTopUp

type TonCocoonExtWorkerLastPayoutRequestSignedMsgBody = TonCocoonExtWorkerLastPayoutRequestSigned

type TonCocoonOwnerClientRequestRefundMsgBody = TonCocoonOwnerClientRequestRefund

var KnownMsgInTypes = map[string]any{
	TonCocoonTextCmdMsgOp:                             TonCocoonTextCmdMsgBody{},
	TonCocoonTextCommandMsgOp:                         TonCocoonTextCommandMsgBody{},
	TonTep74ChangeMinterAdminMsgOp:                    TonTep74ChangeMinterAdminMsgBody{},
	TonTep74ChangeMinterContentMsgOp:                  TonTep74ChangeMinterContentMsgBody{},
	TonTep74MintNewJettonsMsgOp:                       TonTep74MintNewJettonsMsgBody{},
	TonCocoonChangeParamsMsgOp:                        TonCocoonChangeParamsMsgBody{},
	TonTep74AskToTransferMsgOp:                        TonTep74AskToTransferMsgBody{},
	TonCocoonUpgradeCodeMsgOp:                         TonCocoonUpgradeCodeMsgBody{},
	TonTep74InternalTransferStepMsgOp:                 TonTep74InternalTransferStepMsgBody{},
	TonCocoonOwnerWorkerRegisterMsgOp:                 TonCocoonOwnerWorkerRegisterMsgBody{},
	TonTep74RequestWalletAddressMsgOp:                 TonTep74RequestWalletAddressMsgBody{},
	TonCocoonDelProxyTypeMsgOp:                        TonCocoonDelProxyTypeMsgBody{},
	TonCocoonWorkerProxyRequestMsgOp:                  TonCocoonWorkerProxyRequestMsgBody{},
	TonCocoonUpgradeFullMsgOp:                         TonCocoonUpgradeFullMsgBody{},
	TonCocoonResetRootMsgOp:                           TonCocoonResetRootMsgBody{},
	TonTep74AskToBurnMsgOp:                            TonTep74AskToBurnMsgBody{},
	TonCocoonExtProxyCloseRequestSignedMsgOp:          TonCocoonExtProxyCloseRequestSignedMsgBody{},
	TonCocoonClientProxyRequestMsgOp:                  TonCocoonClientProxyRequestMsgBody{},
	TonCocoonOwnerClientIncreaseStakeMsgOp:            TonCocoonOwnerClientIncreaseStakeMsgBody{},
	TonCocoonUnregisterProxyMsgOp:                     TonCocoonUnregisterProxyMsgBody{},
	TonCocoonAddProxyTypeMsgOp:                        TonCocoonAddProxyTypeMsgBody{},
	TonTep74TransferNotificationForRecipientMsgOp:     TonTep74TransferNotificationForRecipientMsgBody{},
	TonCocoonExtProxyPayoutRequestMsgOp:               TonCocoonExtProxyPayoutRequestMsgBody{},
	TonTep74BurnNotificationForMinterMsgOp:            TonTep74BurnNotificationForMinterMsgBody{},
	TonCocoonOwnerClientChangeSecretHashAndTopUpMsgOp: TonCocoonOwnerClientChangeSecretHashAndTopUpMsgBody{},
	TonCocoonDelWorkerTypeMsgOp:                       TonCocoonDelWorkerTypeMsgBody{},
	TonCocoonRegisterProxyMsgOp:                       TonCocoonRegisterProxyMsgBody{},
	TonCocoonDelModelTypeMsgOp:                        TonCocoonDelModelTypeMsgBody{},
	TonCocoonExtProxyIncreaseStakeMsgOp:               TonCocoonExtProxyIncreaseStakeMsgBody{},
	TonCocoonOwnerWalletSendMessageMsgOp:              TonCocoonOwnerWalletSendMessageMsgBody{},
	TonCocoonUpdateProxyMsgOp:                         TonCocoonUpdateProxyMsgBody{},
	TonCocoonExtWorkerPayoutRequestSignedMsgOp:        TonCocoonExtWorkerPayoutRequestSignedMsgBody{},
	TonCocoonUpgradeContractsMsgOp:                    TonCocoonUpgradeContractsMsgBody{},
	TonCocoonOwnerClientChangeSecretHashMsgOp:         TonCocoonOwnerClientChangeSecretHashMsgBody{},
	TonCocoonOwnerProxyCloseMsgOp:                     TonCocoonOwnerProxyCloseMsgBody{},
	TonCocoonExtClientChargeSignedMsgOp:               TonCocoonExtClientChargeSignedMsgBody{},
	TonCocoonAddModelTypeMsgOp:                        TonCocoonAddModelTypeMsgBody{},
	TonCocoonOwnerClientRegisterMsgOp:                 TonCocoonOwnerClientRegisterMsgBody{},
	TonCocoonChangeOwnerMsgOp:                         TonCocoonChangeOwnerMsgBody{},
	TonCocoonChangeFeesMsgOp:                          TonCocoonChangeFeesMsgBody{},
	TonCocoonPayoutMsgOp:                              TonCocoonPayoutMsgBody{},
	TonTep74ResponseWalletAddressMsgOp:                TonTep74ResponseWalletAddressMsgBody{},
	TonCocoonReturnExcessesBackMsgOp:                  TonCocoonReturnExcessesBackMsgBody{},
	TonTep74ReturnExcessesBackMsgOp:                   TonTep74ReturnExcessesBackMsgBody{},
	TonTep74AboaLisaMsgOp:                             TonTep74AboaLisaMsgBody{},
	TonCocoonOwnerClientWithdrawMsgOp:                 TonCocoonOwnerClientWithdrawMsgBody{},
	TonCocoonAddWorkerTypeMsgOp:                       TonCocoonAddWorkerTypeMsgBody{},
	TonCocoonExtProxyCloseCompleteRequestSignedMsgOp:  TonCocoonExtProxyCloseCompleteRequestSignedMsgBody{},
	TonCocoonExtClientGrantRefundSignedMsgOp:          TonCocoonExtClientGrantRefundSignedMsgBody{},
	TonCocoonExtClientTopUpMsgOp:                      TonCocoonExtClientTopUpMsgBody{},
	TonCocoonExtWorkerLastPayoutRequestSignedMsgOp:    TonCocoonExtWorkerLastPayoutRequestSignedMsgBody{},
	TonCocoonOwnerClientRequestRefundMsgOp:            TonCocoonOwnerClientRequestRefundMsgBody{},
}

var ()

var opcodedMsgExtInDecodeFunctions = map[uint32]msgDecoderFunc{}

const ()

const ()

var KnownMsgExtInTypes = map[string]any{}

var ()

var opcodedMsgExtOutDecodeFunctions = map[uint32]msgDecoderFunc{}

const ()

const ()

var KnownMsgExtOutTypes = map[string]any{}
