package abitolk

// Code autogenerated. DO NOT EDIT.

import (
	"github.com/tonkeeper/tongo/boc"
	"github.com/tonkeeper/tongo/tlb"
)

func decodeTonTolkTestsTextCommentJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsTextComment
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsTextCommentJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonTextCommandOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonTextCommandPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonTextCommandOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonTextCmdOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonTextCmdPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonTextCmdOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74ChangeMinterAdminOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74ChangeMinterAdminPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74ChangeMinterAdminOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74ChangeMinterContentOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74ChangeMinterContentPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74ChangeMinterContentOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74MintNewJettonsOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74MintNewJettonsPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74MintNewJettonsOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsTegroJettonSwapJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsTegroJettonSwap
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsTegroJettonSwapJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonChangeParamsOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonChangeParamsPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonChangeParamsOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsCoffeeStakingLockJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsCoffeeStakingLock
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsCoffeeStakingLockJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74AskToTransferOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74AskToTransferPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74AskToTransferOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonUpgradeCodeOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonUpgradeCodePayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonUpgradeCodeOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74InternalTransferStepOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74InternalTransferStepPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74InternalTransferStepOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCoffeeCrossDexResendOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCoffeeCrossDexResendPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCoffeeCrossDexResendOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsEncryptedTextCommentJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsEncryptedTextComment
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsEncryptedTextCommentJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonStonfiV1StonfiSwapJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonStonfiV1StonfiSwap
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonStonfiV1StonfiSwapJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonOwnerWorkerRegisterOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonOwnerWorkerRegisterPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonOwnerWorkerRegisterOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsTegroAddLiquidityJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsTegroAddLiquidity
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsTegroAddLiquidityJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74RequestWalletAddressOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74RequestWalletAddressPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74RequestWalletAddressOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonStonfiV2StonfiProvideLpV2JettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonStonfiV2StonfiProvideLpV2
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonStonfiV2StonfiProvideLpV2JettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonDelProxyTypeOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonDelProxyTypePayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonDelProxyTypeOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsBidaskProvideBothJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsBidaskProvideBoth
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsBidaskProvideBothJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsDedustDepositLiquidityJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsDedustDepositLiquidity
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsDedustDepositLiquidityJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsPoolFundAccountJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsPoolFundAccount
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsPoolFundAccountJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonStonfiV1StonfiSwapOkRefJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonStonfiV1StonfiSwapOkRef
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonStonfiV1StonfiSwapOkRefJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonWorkerProxyRequestOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonWorkerProxyRequestPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonWorkerProxyRequestOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsCoffeeCrossDexResendJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsCoffeeCrossDexResend
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsCoffeeCrossDexResendJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonUpgradeFullOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonUpgradeFullPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonUpgradeFullOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonResetRootOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonResetRootPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonResetRootOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74AskToBurnOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74AskToBurnPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74AskToBurnOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonExtProxyCloseRequestSignedOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonExtProxyCloseRequestSignedPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonExtProxyCloseRequestSignedOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsBidaskDammProvideJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsBidaskDammProvide
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsBidaskDammProvideJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonClientProxyRequestOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonClientProxyRequestPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonClientProxyRequestOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonStonfiV2StonfiSwapV2JettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonStonfiV2StonfiSwapV2
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonStonfiV2StonfiSwapV2JettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonOwnerClientIncreaseStakeOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonOwnerClientIncreaseStakePayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonOwnerClientIncreaseStakeOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonUnregisterProxyOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonUnregisterProxyPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonUnregisterProxyOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonAddProxyTypeOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonAddProxyTypePayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonAddProxyTypeOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsBidaskDammProvideOneSideJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsBidaskDammProvideOneSide
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsBidaskDammProvideOneSideJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74TransferNotificationForRecipientOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74TransferNotificationForRecipientPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74TransferNotificationForRecipientOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonExtProxyPayoutRequestOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonExtProxyPayoutRequestPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonExtProxyPayoutRequestOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsStormDepositJettonJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsStormDepositJetton
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsStormDepositJettonJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsInvoicePayloadJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsInvoicePayload
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsInvoicePayloadJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74BurnNotificationForMinterOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74BurnNotificationForMinterPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74BurnNotificationForMinterOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonOwnerClientChangeSecretHashAndTopUpOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonOwnerClientChangeSecretHashAndTopUpPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonOwnerClientChangeSecretHashAndTopUpOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsTonkeeperRelayerFeeJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsTonkeeperRelayerFee
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsTonkeeperRelayerFeeJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsBidaskSwapV2JettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsBidaskSwapV2
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsBidaskSwapV2JettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonDelWorkerTypeOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonDelWorkerTypePayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonDelWorkerTypeOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonRegisterProxyOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonRegisterProxyPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonRegisterProxyOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonDelModelTypeOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonDelModelTypePayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonDelModelTypeOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsMoonBoostPoolJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsMoonBoostPool
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsMoonBoostPoolJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsBidaskProvideJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsBidaskProvide
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsBidaskProvideJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonExtProxyIncreaseStakeOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonExtProxyIncreaseStakePayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonExtProxyIncreaseStakeOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsMoonFillOrderJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsMoonFillOrder
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsMoonFillOrderJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonOwnerWalletSendMessageOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonOwnerWalletSendMessagePayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonOwnerWalletSendMessageOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonUpdateProxyOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonUpdateProxyPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonUpdateProxyOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonExtWorkerPayoutRequestSignedOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonExtWorkerPayoutRequestSignedPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonExtWorkerPayoutRequestSignedOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonUpgradeContractsOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonUpgradeContractsPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonUpgradeContractsOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsBidaskDammProvideBothJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsBidaskDammProvideBoth
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsBidaskDammProvideBothJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonOwnerClientChangeSecretHashOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonOwnerClientChangeSecretHashPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonOwnerClientChangeSecretHashOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsMoonDepositLiquidityJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsMoonDepositLiquidity
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsMoonDepositLiquidityJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsMoonSwapJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsMoonSwap
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsMoonSwapJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonOwnerProxyCloseOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonOwnerProxyClosePayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonOwnerProxyCloseOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsCoffeeCrossDexFailureJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsCoffeeCrossDexFailure
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsCoffeeCrossDexFailureJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonExtClientChargeSignedOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonExtClientChargeSignedPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonExtClientChargeSignedOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsCoffeeSwapJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsCoffeeSwap
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsCoffeeSwapJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsCoffeeCreatePoolJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsCoffeeCreatePool
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsCoffeeCreatePoolJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsCoffeeDepositLiquidityJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsCoffeeDepositLiquidity
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsCoffeeDepositLiquidityJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsCoffeeNotificationJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsCoffeeNotification
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsCoffeeNotificationJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonAddModelTypeOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonAddModelTypePayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonAddModelTypeOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonOwnerClientRegisterOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonOwnerClientRegisterPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonOwnerClientRegisterOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsMoonSwapFailedJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsMoonSwapFailed
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsMoonSwapFailedJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonChangeOwnerOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonChangeOwnerPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonChangeOwnerOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonChangeFeesOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonChangeFeesPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonChangeFeesOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonPayoutOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonPayoutPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonPayoutOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonStonfiV2StonfiSwapOkJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonStonfiV2StonfiSwapOk
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonStonfiV2StonfiSwapOkJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsStormStakeJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsStormStake
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsStormStakeJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsWithdrawPayloadJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsWithdrawPayload
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsWithdrawPayloadJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsMoonSwapSucceedJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsMoonSwapSucceed
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsMoonSwapSucceedJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74ResponseWalletAddressOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74ResponseWalletAddressPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74ResponseWalletAddressOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74AboaLisaOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74AboaLisaPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74AboaLisaOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonReturnExcessesBackOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonReturnExcessesBackPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonReturnExcessesBackOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTep74ReturnExcessesBackOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTep74ReturnExcessesBackPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTep74ReturnExcessesBackOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsMoonCreateOrderJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsMoonCreateOrder
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsMoonCreateOrderJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonOwnerClientWithdrawOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonOwnerClientWithdrawPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonOwnerClientWithdrawOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsBidaskDammSwapJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsBidaskDammSwap
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsBidaskDammSwapJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonAddWorkerTypeOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonAddWorkerTypePayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonAddWorkerTypeOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsDedustSwapJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsDedustSwap
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsDedustSwapJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonExtProxyCloseCompleteRequestSignedOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonExtProxyCloseCompleteRequestSignedPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonExtProxyCloseCompleteRequestSignedOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsCoffeeMevProtectFailedSwapJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsCoffeeMevProtectFailedSwap
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsCoffeeMevProtectFailedSwapJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonExtClientGrantRefundSignedOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonExtClientGrantRefundSignedPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonExtClientGrantRefundSignedOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonExtClientTopUpOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonExtClientTopUpPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonExtClientTopUpOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsBidaskSwapJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsBidaskSwap
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsBidaskSwapJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonExtWorkerLastPayoutRequestSignedOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonExtWorkerLastPayoutRequestSignedPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonExtWorkerLastPayoutRequestSignedOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonTolkTestsDepositPayloadJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonTolkTestsDepositPayload
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonTolkTestsDepositPayloadJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonCocoonOwnerClientRequestRefundOpPayload(j *Payload, c *boc.Cell) error {
	var res TonCocoonOwnerClientRequestRefundPayloadBody
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonCocoonOwnerClientRequestRefundOp
		j.Value = res
		return nil
	}
	return err
}

func decodeTonStonfiV2StonfiProvideLiquidityJettonPayloadOpPayload(j *Payload, c *boc.Cell) error {
	var res TonStonfiV2StonfiProvideLiquidity
	err := tlb.Unmarshal(c, &res)
	if err == nil {
		j.SumType = TonStonfiV2StonfiProvideLiquidityJettonPayloadOp
		j.Value = res
		return nil
	}
	return err
}

const (
	TonTolkTestsTextCommentJettonPayloadOp                PayloadOpName = "TonTolkTestsTextCommentJettonPayload"
	TonCocoonTextCommandOp                                PayloadOpName = "TonCocoonTextCommand"
	TonCocoonTextCmdOp                                    PayloadOpName = "TonCocoonTextCmd"
	TonTep74ChangeMinterAdminOp                           PayloadOpName = "TonTep74ChangeMinterAdmin"
	TonTep74ChangeMinterContentOp                         PayloadOpName = "TonTep74ChangeMinterContent"
	TonTep74MintNewJettonsOp                              PayloadOpName = "TonTep74MintNewJettons"
	TonTolkTestsTegroJettonSwapJettonPayloadOp            PayloadOpName = "TonTolkTestsTegroJettonSwapJettonPayload"
	TonCocoonChangeParamsOp                               PayloadOpName = "TonCocoonChangeParams"
	TonTolkTestsCoffeeStakingLockJettonPayloadOp          PayloadOpName = "TonTolkTestsCoffeeStakingLockJettonPayload"
	TonTep74AskToTransferOp                               PayloadOpName = "TonTep74AskToTransfer"
	TonCocoonUpgradeCodeOp                                PayloadOpName = "TonCocoonUpgradeCode"
	TonTep74InternalTransferStepOp                        PayloadOpName = "TonTep74InternalTransferStep"
	TonCoffeeCrossDexResendOp                             PayloadOpName = "TonCoffeeCrossDexResend"
	TonTolkTestsEncryptedTextCommentJettonPayloadOp       PayloadOpName = "TonTolkTestsEncryptedTextCommentJettonPayload"
	TonStonfiV1StonfiSwapJettonPayloadOp                  PayloadOpName = "TonStonfiV1StonfiSwapJettonPayload"
	TonCocoonOwnerWorkerRegisterOp                        PayloadOpName = "TonCocoonOwnerWorkerRegister"
	TonTolkTestsTegroAddLiquidityJettonPayloadOp          PayloadOpName = "TonTolkTestsTegroAddLiquidityJettonPayload"
	TonTep74RequestWalletAddressOp                        PayloadOpName = "TonTep74RequestWalletAddress"
	TonStonfiV2StonfiProvideLpV2JettonPayloadOp           PayloadOpName = "TonStonfiV2StonfiProvideLpV2JettonPayload"
	TonCocoonDelProxyTypeOp                               PayloadOpName = "TonCocoonDelProxyType"
	TonTolkTestsBidaskProvideBothJettonPayloadOp          PayloadOpName = "TonTolkTestsBidaskProvideBothJettonPayload"
	TonTolkTestsDedustDepositLiquidityJettonPayloadOp     PayloadOpName = "TonTolkTestsDedustDepositLiquidityJettonPayload"
	TonTolkTestsPoolFundAccountJettonPayloadOp            PayloadOpName = "TonTolkTestsPoolFundAccountJettonPayload"
	TonStonfiV1StonfiSwapOkRefJettonPayloadOp             PayloadOpName = "TonStonfiV1StonfiSwapOkRefJettonPayload"
	TonCocoonWorkerProxyRequestOp                         PayloadOpName = "TonCocoonWorkerProxyRequest"
	TonTolkTestsCoffeeCrossDexResendJettonPayloadOp       PayloadOpName = "TonTolkTestsCoffeeCrossDexResendJettonPayload"
	TonCocoonUpgradeFullOp                                PayloadOpName = "TonCocoonUpgradeFull"
	TonCocoonResetRootOp                                  PayloadOpName = "TonCocoonResetRoot"
	TonTep74AskToBurnOp                                   PayloadOpName = "TonTep74AskToBurn"
	TonCocoonExtProxyCloseRequestSignedOp                 PayloadOpName = "TonCocoonExtProxyCloseRequestSigned"
	TonTolkTestsBidaskDammProvideJettonPayloadOp          PayloadOpName = "TonTolkTestsBidaskDammProvideJettonPayload"
	TonCocoonClientProxyRequestOp                         PayloadOpName = "TonCocoonClientProxyRequest"
	TonStonfiV2StonfiSwapV2JettonPayloadOp                PayloadOpName = "TonStonfiV2StonfiSwapV2JettonPayload"
	TonCocoonOwnerClientIncreaseStakeOp                   PayloadOpName = "TonCocoonOwnerClientIncreaseStake"
	TonCocoonUnregisterProxyOp                            PayloadOpName = "TonCocoonUnregisterProxy"
	TonCocoonAddProxyTypeOp                               PayloadOpName = "TonCocoonAddProxyType"
	TonTolkTestsBidaskDammProvideOneSideJettonPayloadOp   PayloadOpName = "TonTolkTestsBidaskDammProvideOneSideJettonPayload"
	TonTep74TransferNotificationForRecipientOp            PayloadOpName = "TonTep74TransferNotificationForRecipient"
	TonCocoonExtProxyPayoutRequestOp                      PayloadOpName = "TonCocoonExtProxyPayoutRequest"
	TonTolkTestsStormDepositJettonJettonPayloadOp         PayloadOpName = "TonTolkTestsStormDepositJettonJettonPayload"
	TonTolkTestsInvoicePayloadJettonPayloadOp             PayloadOpName = "TonTolkTestsInvoicePayloadJettonPayload"
	TonTep74BurnNotificationForMinterOp                   PayloadOpName = "TonTep74BurnNotificationForMinter"
	TonCocoonOwnerClientChangeSecretHashAndTopUpOp        PayloadOpName = "TonCocoonOwnerClientChangeSecretHashAndTopUp"
	TonTolkTestsTonkeeperRelayerFeeJettonPayloadOp        PayloadOpName = "TonTolkTestsTonkeeperRelayerFeeJettonPayload"
	TonTolkTestsBidaskSwapV2JettonPayloadOp               PayloadOpName = "TonTolkTestsBidaskSwapV2JettonPayload"
	TonCocoonDelWorkerTypeOp                              PayloadOpName = "TonCocoonDelWorkerType"
	TonCocoonRegisterProxyOp                              PayloadOpName = "TonCocoonRegisterProxy"
	TonCocoonDelModelTypeOp                               PayloadOpName = "TonCocoonDelModelType"
	TonTolkTestsMoonBoostPoolJettonPayloadOp              PayloadOpName = "TonTolkTestsMoonBoostPoolJettonPayload"
	TonTolkTestsBidaskProvideJettonPayloadOp              PayloadOpName = "TonTolkTestsBidaskProvideJettonPayload"
	TonCocoonExtProxyIncreaseStakeOp                      PayloadOpName = "TonCocoonExtProxyIncreaseStake"
	TonTolkTestsMoonFillOrderJettonPayloadOp              PayloadOpName = "TonTolkTestsMoonFillOrderJettonPayload"
	TonCocoonOwnerWalletSendMessageOp                     PayloadOpName = "TonCocoonOwnerWalletSendMessage"
	TonCocoonUpdateProxyOp                                PayloadOpName = "TonCocoonUpdateProxy"
	TonCocoonExtWorkerPayoutRequestSignedOp               PayloadOpName = "TonCocoonExtWorkerPayoutRequestSigned"
	TonCocoonUpgradeContractsOp                           PayloadOpName = "TonCocoonUpgradeContracts"
	TonTolkTestsBidaskDammProvideBothJettonPayloadOp      PayloadOpName = "TonTolkTestsBidaskDammProvideBothJettonPayload"
	TonCocoonOwnerClientChangeSecretHashOp                PayloadOpName = "TonCocoonOwnerClientChangeSecretHash"
	TonTolkTestsMoonDepositLiquidityJettonPayloadOp       PayloadOpName = "TonTolkTestsMoonDepositLiquidityJettonPayload"
	TonTolkTestsMoonSwapJettonPayloadOp                   PayloadOpName = "TonTolkTestsMoonSwapJettonPayload"
	TonCocoonOwnerProxyCloseOp                            PayloadOpName = "TonCocoonOwnerProxyClose"
	TonTolkTestsCoffeeCrossDexFailureJettonPayloadOp      PayloadOpName = "TonTolkTestsCoffeeCrossDexFailureJettonPayload"
	TonCocoonExtClientChargeSignedOp                      PayloadOpName = "TonCocoonExtClientChargeSigned"
	TonTolkTestsCoffeeSwapJettonPayloadOp                 PayloadOpName = "TonTolkTestsCoffeeSwapJettonPayload"
	TonTolkTestsCoffeeCreatePoolJettonPayloadOp           PayloadOpName = "TonTolkTestsCoffeeCreatePoolJettonPayload"
	TonTolkTestsCoffeeDepositLiquidityJettonPayloadOp     PayloadOpName = "TonTolkTestsCoffeeDepositLiquidityJettonPayload"
	TonTolkTestsCoffeeNotificationJettonPayloadOp         PayloadOpName = "TonTolkTestsCoffeeNotificationJettonPayload"
	TonCocoonAddModelTypeOp                               PayloadOpName = "TonCocoonAddModelType"
	TonCocoonOwnerClientRegisterOp                        PayloadOpName = "TonCocoonOwnerClientRegister"
	TonTolkTestsMoonSwapFailedJettonPayloadOp             PayloadOpName = "TonTolkTestsMoonSwapFailedJettonPayload"
	TonCocoonChangeOwnerOp                                PayloadOpName = "TonCocoonChangeOwner"
	TonCocoonChangeFeesOp                                 PayloadOpName = "TonCocoonChangeFees"
	TonCocoonPayoutOp                                     PayloadOpName = "TonCocoonPayout"
	TonStonfiV2StonfiSwapOkJettonPayloadOp                PayloadOpName = "TonStonfiV2StonfiSwapOkJettonPayload"
	TonTolkTestsStormStakeJettonPayloadOp                 PayloadOpName = "TonTolkTestsStormStakeJettonPayload"
	TonTolkTestsWithdrawPayloadJettonPayloadOp            PayloadOpName = "TonTolkTestsWithdrawPayloadJettonPayload"
	TonTolkTestsMoonSwapSucceedJettonPayloadOp            PayloadOpName = "TonTolkTestsMoonSwapSucceedJettonPayload"
	TonTep74ResponseWalletAddressOp                       PayloadOpName = "TonTep74ResponseWalletAddress"
	TonTep74AboaLisaOp                                    PayloadOpName = "TonTep74AboaLisa"
	TonCocoonReturnExcessesBackOp                         PayloadOpName = "TonCocoonReturnExcessesBack"
	TonTep74ReturnExcessesBackOp                          PayloadOpName = "TonTep74ReturnExcessesBack"
	TonTolkTestsMoonCreateOrderJettonPayloadOp            PayloadOpName = "TonTolkTestsMoonCreateOrderJettonPayload"
	TonCocoonOwnerClientWithdrawOp                        PayloadOpName = "TonCocoonOwnerClientWithdraw"
	TonTolkTestsBidaskDammSwapJettonPayloadOp             PayloadOpName = "TonTolkTestsBidaskDammSwapJettonPayload"
	TonCocoonAddWorkerTypeOp                              PayloadOpName = "TonCocoonAddWorkerType"
	TonTolkTestsDedustSwapJettonPayloadOp                 PayloadOpName = "TonTolkTestsDedustSwapJettonPayload"
	TonCocoonExtProxyCloseCompleteRequestSignedOp         PayloadOpName = "TonCocoonExtProxyCloseCompleteRequestSigned"
	TonTolkTestsCoffeeMevProtectFailedSwapJettonPayloadOp PayloadOpName = "TonTolkTestsCoffeeMevProtectFailedSwapJettonPayload"
	TonCocoonExtClientGrantRefundSignedOp                 PayloadOpName = "TonCocoonExtClientGrantRefundSigned"
	TonCocoonExtClientTopUpOp                             PayloadOpName = "TonCocoonExtClientTopUp"
	TonTolkTestsBidaskSwapJettonPayloadOp                 PayloadOpName = "TonTolkTestsBidaskSwapJettonPayload"
	TonCocoonExtWorkerLastPayoutRequestSignedOp           PayloadOpName = "TonCocoonExtWorkerLastPayoutRequestSigned"
	TonTolkTestsDepositPayloadJettonPayloadOp             PayloadOpName = "TonTolkTestsDepositPayloadJettonPayload"
	TonCocoonOwnerClientRequestRefundOp                   PayloadOpName = "TonCocoonOwnerClientRequestRefund"
	TonStonfiV2StonfiProvideLiquidityJettonPayloadOp      PayloadOpName = "TonStonfiV2StonfiProvideLiquidityJettonPayload"

	TonTolkTestsTextCommentJettonPayloadOpCode                PayloadOpCode = 0x00000000
	TonCocoonTextCommandOpCode                                PayloadOpCode = 0x00000000
	TonCocoonTextCmdOpCode                                    PayloadOpCode = 0x00000000
	TonTep74ChangeMinterAdminOpCode                           PayloadOpCode = 0x00000003
	TonTep74ChangeMinterContentOpCode                         PayloadOpCode = 0x00000004
	TonTep74MintNewJettonsOpCode                              PayloadOpCode = 0x00000015
	TonTolkTestsTegroJettonSwapJettonPayloadOpCode            PayloadOpCode = 0x01fb7a25
	TonCocoonChangeParamsOpCode                               PayloadOpCode = 0x022fa189
	TonTolkTestsCoffeeStakingLockJettonPayloadOpCode          PayloadOpCode = 0x0c0ffede
	TonTep74AskToTransferOpCode                               PayloadOpCode = 0x0f8a7ea5
	TonCocoonUpgradeCodeOpCode                                PayloadOpCode = 0x11aefd51
	TonTep74InternalTransferStepOpCode                        PayloadOpCode = 0x178d4519
	TonCoffeeCrossDexResendOpCode                             PayloadOpCode = 0x200f9086
	TonTolkTestsEncryptedTextCommentJettonPayloadOpCode       PayloadOpCode = 0x2167da4b
	TonStonfiV1StonfiSwapJettonPayloadOpCode                  PayloadOpCode = 0x25938561
	TonCocoonOwnerWorkerRegisterOpCode                        PayloadOpCode = 0x26ed7f65
	TonTolkTestsTegroAddLiquidityJettonPayloadOpCode          PayloadOpCode = 0x287e167a
	TonTep74RequestWalletAddressOpCode                        PayloadOpCode = 0x2c76b973
	TonStonfiV2StonfiProvideLpV2JettonPayloadOpCode           PayloadOpCode = 0x37c096df
	TonCocoonDelProxyTypeOpCode                               PayloadOpCode = 0x3c41d0b2
	TonTolkTestsBidaskProvideBothJettonPayloadOpCode          PayloadOpCode = 0x3ea0bafc
	TonTolkTestsDedustDepositLiquidityJettonPayloadOpCode     PayloadOpCode = 0x40e108d6
	TonTolkTestsPoolFundAccountJettonPayloadOpCode            PayloadOpCode = 0x4468de77
	TonStonfiV1StonfiSwapOkRefJettonPayloadOpCode             PayloadOpCode = 0x45078540
	TonCocoonWorkerProxyRequestOpCode                         PayloadOpCode = 0x4d725d2c
	TonTolkTestsCoffeeCrossDexResendJettonPayloadOpCode       PayloadOpCode = 0x4ee9b106
	TonCocoonUpgradeFullOpCode                                PayloadOpCode = 0x4f7c5789
	TonCocoonResetRootOpCode                                  PayloadOpCode = 0x563c1d96
	TonTep74AskToBurnOpCode                                   PayloadOpCode = 0x595f07bc
	TonCocoonExtProxyCloseRequestSignedOpCode                 PayloadOpCode = 0x636a4391
	TonTolkTestsBidaskDammProvideJettonPayloadOpCode          PayloadOpCode = 0x63ec24ae
	TonCocoonClientProxyRequestOpCode                         PayloadOpCode = 0x65448ff4
	TonStonfiV2StonfiSwapV2JettonPayloadOpCode                PayloadOpCode = 0x6664de2a
	TonCocoonOwnerClientIncreaseStakeOpCode                   PayloadOpCode = 0x6a1f6a60
	TonCocoonUnregisterProxyOpCode                            PayloadOpCode = 0x6d49eaf2
	TonCocoonAddProxyTypeOpCode                               PayloadOpCode = 0x71860e80
	TonTolkTestsBidaskDammProvideOneSideJettonPayloadOpCode   PayloadOpCode = 0x729c04c8
	TonTep74TransferNotificationForRecipientOpCode            PayloadOpCode = 0x7362d09c
	TonCocoonExtProxyPayoutRequestOpCode                      PayloadOpCode = 0x7610e6eb
	TonTolkTestsStormDepositJettonJettonPayloadOpCode         PayloadOpCode = 0x76840119
	TonTolkTestsInvoicePayloadJettonPayloadOpCode             PayloadOpCode = 0x7aa23eb5
	TonTep74BurnNotificationForMinterOpCode                   PayloadOpCode = 0x7bdd97de
	TonCocoonOwnerClientChangeSecretHashAndTopUpOpCode        PayloadOpCode = 0x8473b408
	TonTolkTestsTonkeeperRelayerFeeJettonPayloadOpCode        PayloadOpCode = 0x878da6e3
	TonTolkTestsBidaskSwapV2JettonPayloadOpCode               PayloadOpCode = 0x87d36990
	TonCocoonDelWorkerTypeOpCode                              PayloadOpCode = 0x8d94a79a
	TonCocoonRegisterProxyOpCode                              PayloadOpCode = 0x927c7cb5
	TonCocoonDelModelTypeOpCode                               PayloadOpCode = 0x92b11c18
	TonTolkTestsMoonBoostPoolJettonPayloadOpCode              PayloadOpCode = 0x96aa1586
	TonTolkTestsBidaskProvideJettonPayloadOpCode              PayloadOpCode = 0x96feef7b
	TonCocoonExtProxyIncreaseStakeOpCode                      PayloadOpCode = 0x9713f187
	TonTolkTestsMoonFillOrderJettonPayloadOpCode              PayloadOpCode = 0x99b49842
	TonCocoonOwnerWalletSendMessageOpCode                     PayloadOpCode = 0x9c69f376
	TonCocoonUpdateProxyOpCode                                PayloadOpCode = 0x9c7924ba
	TonCocoonExtWorkerPayoutRequestSignedOpCode               PayloadOpCode = 0xa040ad28
	TonCocoonUpgradeContractsOpCode                           PayloadOpCode = 0xa2370f61
	TonTolkTestsBidaskDammProvideBothJettonPayloadOpCode      PayloadOpCode = 0xa8904134
	TonCocoonOwnerClientChangeSecretHashOpCode                PayloadOpCode = 0xa9357034
	TonTolkTestsMoonDepositLiquidityJettonPayloadOpCode       PayloadOpCode = 0xb31db781
	TonTolkTestsMoonSwapJettonPayloadOpCode                   PayloadOpCode = 0xb37a900b
	TonCocoonOwnerProxyCloseOpCode                            PayloadOpCode = 0xb51d5a01
	TonTolkTestsCoffeeCrossDexFailureJettonPayloadOpCode      PayloadOpCode = 0xb902e61a
	TonCocoonExtClientChargeSignedOpCode                      PayloadOpCode = 0xbb63ff93
	TonTolkTestsCoffeeSwapJettonPayloadOpCode                 PayloadOpCode = 0xc0ffee10
	TonTolkTestsCoffeeCreatePoolJettonPayloadOpCode           PayloadOpCode = 0xc0ffee11
	TonTolkTestsCoffeeDepositLiquidityJettonPayloadOpCode     PayloadOpCode = 0xc0ffee12
	TonTolkTestsCoffeeNotificationJettonPayloadOpCode         PayloadOpCode = 0xc0ffee36
	TonCocoonAddModelTypeOpCode                               PayloadOpCode = 0xc146134d
	TonCocoonOwnerClientRegisterOpCode                        PayloadOpCode = 0xc45f9f3b
	TonTolkTestsMoonSwapFailedJettonPayloadOpCode             PayloadOpCode = 0xc47c1f57
	TonCocoonChangeOwnerOpCode                                PayloadOpCode = 0xc4a1ae54
	TonCocoonChangeFeesOpCode                                 PayloadOpCode = 0xc52ed8d4
	TonCocoonPayoutOpCode                                     PayloadOpCode = 0xc59a7cd3
	TonStonfiV2StonfiSwapOkJettonPayloadOpCode                PayloadOpCode = 0xc64370e5
	TonTolkTestsStormStakeJettonPayloadOpCode                 PayloadOpCode = 0xc89a3ee4
	TonTolkTestsWithdrawPayloadJettonPayloadOpCode            PayloadOpCode = 0xcb03bfaf
	TonTolkTestsMoonSwapSucceedJettonPayloadOpCode            PayloadOpCode = 0xcb7f38d6
	TonTep74ResponseWalletAddressOpCode                       PayloadOpCode = 0xd1735400
	TonTep74AboaLisaOpCode                                    PayloadOpCode = 0xd53276db
	TonCocoonReturnExcessesBackOpCode                         PayloadOpCode = 0xd53276db
	TonTep74ReturnExcessesBackOpCode                          PayloadOpCode = 0xd53276db
	TonTolkTestsMoonCreateOrderJettonPayloadOpCode            PayloadOpCode = 0xda067c19
	TonCocoonOwnerClientWithdrawOpCode                        PayloadOpCode = 0xda068e78
	TonTolkTestsBidaskDammSwapJettonPayloadOpCode             PayloadOpCode = 0xdd79732c
	TonCocoonAddWorkerTypeOpCode                              PayloadOpCode = 0xe34b1c60
	TonTolkTestsDedustSwapJettonPayloadOpCode                 PayloadOpCode = 0xe3a0d482
	TonCocoonExtProxyCloseCompleteRequestSignedOpCode         PayloadOpCode = 0xe511abc7
	TonTolkTestsCoffeeMevProtectFailedSwapJettonPayloadOpCode PayloadOpCode = 0xee51ce51
	TonCocoonExtClientGrantRefundSignedOpCode                 PayloadOpCode = 0xefd711e1
	TonCocoonExtClientTopUpOpCode                             PayloadOpCode = 0xf172e6c2
	TonTolkTestsBidaskSwapJettonPayloadOpCode                 PayloadOpCode = 0xf2ef6c1b
	TonCocoonExtWorkerLastPayoutRequestSignedOpCode           PayloadOpCode = 0xf5f26a36
	TonTolkTestsDepositPayloadJettonPayloadOpCode             PayloadOpCode = 0xf9471134
	TonCocoonOwnerClientRequestRefundOpCode                   PayloadOpCode = 0xfafa6cc1
	TonStonfiV2StonfiProvideLiquidityJettonPayloadOpCode      PayloadOpCode = 0xfcf9e58f
)

var KnownPayloadTypes = map[string]any{
	TonTolkTestsTextCommentJettonPayloadOp:                TonTolkTestsTextComment{},
	TonCocoonTextCommandOp:                                TonCocoonTextCommandPayloadBody{},
	TonCocoonTextCmdOp:                                    TonCocoonTextCmdPayloadBody{},
	TonTep74ChangeMinterAdminOp:                           TonTep74ChangeMinterAdminPayloadBody{},
	TonTep74ChangeMinterContentOp:                         TonTep74ChangeMinterContentPayloadBody{},
	TonTep74MintNewJettonsOp:                              TonTep74MintNewJettonsPayloadBody{},
	TonTolkTestsTegroJettonSwapJettonPayloadOp:            TonTolkTestsTegroJettonSwap{},
	TonCocoonChangeParamsOp:                               TonCocoonChangeParamsPayloadBody{},
	TonTolkTestsCoffeeStakingLockJettonPayloadOp:          TonTolkTestsCoffeeStakingLock{},
	TonTep74AskToTransferOp:                               TonTep74AskToTransferPayloadBody{},
	TonCocoonUpgradeCodeOp:                                TonCocoonUpgradeCodePayloadBody{},
	TonTep74InternalTransferStepOp:                        TonTep74InternalTransferStepPayloadBody{},
	TonCoffeeCrossDexResendOp:                             TonCoffeeCrossDexResendPayloadBody{},
	TonTolkTestsEncryptedTextCommentJettonPayloadOp:       TonTolkTestsEncryptedTextComment{},
	TonStonfiV1StonfiSwapJettonPayloadOp:                  TonStonfiV1StonfiSwap{},
	TonCocoonOwnerWorkerRegisterOp:                        TonCocoonOwnerWorkerRegisterPayloadBody{},
	TonTolkTestsTegroAddLiquidityJettonPayloadOp:          TonTolkTestsTegroAddLiquidity{},
	TonTep74RequestWalletAddressOp:                        TonTep74RequestWalletAddressPayloadBody{},
	TonStonfiV2StonfiProvideLpV2JettonPayloadOp:           TonStonfiV2StonfiProvideLpV2{},
	TonCocoonDelProxyTypeOp:                               TonCocoonDelProxyTypePayloadBody{},
	TonTolkTestsBidaskProvideBothJettonPayloadOp:          TonTolkTestsBidaskProvideBoth{},
	TonTolkTestsDedustDepositLiquidityJettonPayloadOp:     TonTolkTestsDedustDepositLiquidity{},
	TonTolkTestsPoolFundAccountJettonPayloadOp:            TonTolkTestsPoolFundAccount{},
	TonStonfiV1StonfiSwapOkRefJettonPayloadOp:             TonStonfiV1StonfiSwapOkRef{},
	TonCocoonWorkerProxyRequestOp:                         TonCocoonWorkerProxyRequestPayloadBody{},
	TonTolkTestsCoffeeCrossDexResendJettonPayloadOp:       TonTolkTestsCoffeeCrossDexResend{},
	TonCocoonUpgradeFullOp:                                TonCocoonUpgradeFullPayloadBody{},
	TonCocoonResetRootOp:                                  TonCocoonResetRootPayloadBody{},
	TonTep74AskToBurnOp:                                   TonTep74AskToBurnPayloadBody{},
	TonCocoonExtProxyCloseRequestSignedOp:                 TonCocoonExtProxyCloseRequestSignedPayloadBody{},
	TonTolkTestsBidaskDammProvideJettonPayloadOp:          TonTolkTestsBidaskDammProvide{},
	TonCocoonClientProxyRequestOp:                         TonCocoonClientProxyRequestPayloadBody{},
	TonStonfiV2StonfiSwapV2JettonPayloadOp:                TonStonfiV2StonfiSwapV2{},
	TonCocoonOwnerClientIncreaseStakeOp:                   TonCocoonOwnerClientIncreaseStakePayloadBody{},
	TonCocoonUnregisterProxyOp:                            TonCocoonUnregisterProxyPayloadBody{},
	TonCocoonAddProxyTypeOp:                               TonCocoonAddProxyTypePayloadBody{},
	TonTolkTestsBidaskDammProvideOneSideJettonPayloadOp:   TonTolkTestsBidaskDammProvideOneSide{},
	TonTep74TransferNotificationForRecipientOp:            TonTep74TransferNotificationForRecipientPayloadBody{},
	TonCocoonExtProxyPayoutRequestOp:                      TonCocoonExtProxyPayoutRequestPayloadBody{},
	TonTolkTestsStormDepositJettonJettonPayloadOp:         TonTolkTestsStormDepositJetton{},
	TonTolkTestsInvoicePayloadJettonPayloadOp:             TonTolkTestsInvoicePayload{},
	TonTep74BurnNotificationForMinterOp:                   TonTep74BurnNotificationForMinterPayloadBody{},
	TonCocoonOwnerClientChangeSecretHashAndTopUpOp:        TonCocoonOwnerClientChangeSecretHashAndTopUpPayloadBody{},
	TonTolkTestsTonkeeperRelayerFeeJettonPayloadOp:        TonTolkTestsTonkeeperRelayerFee{},
	TonTolkTestsBidaskSwapV2JettonPayloadOp:               TonTolkTestsBidaskSwapV2{},
	TonCocoonDelWorkerTypeOp:                              TonCocoonDelWorkerTypePayloadBody{},
	TonCocoonRegisterProxyOp:                              TonCocoonRegisterProxyPayloadBody{},
	TonCocoonDelModelTypeOp:                               TonCocoonDelModelTypePayloadBody{},
	TonTolkTestsMoonBoostPoolJettonPayloadOp:              TonTolkTestsMoonBoostPool{},
	TonTolkTestsBidaskProvideJettonPayloadOp:              TonTolkTestsBidaskProvide{},
	TonCocoonExtProxyIncreaseStakeOp:                      TonCocoonExtProxyIncreaseStakePayloadBody{},
	TonTolkTestsMoonFillOrderJettonPayloadOp:              TonTolkTestsMoonFillOrder{},
	TonCocoonOwnerWalletSendMessageOp:                     TonCocoonOwnerWalletSendMessagePayloadBody{},
	TonCocoonUpdateProxyOp:                                TonCocoonUpdateProxyPayloadBody{},
	TonCocoonExtWorkerPayoutRequestSignedOp:               TonCocoonExtWorkerPayoutRequestSignedPayloadBody{},
	TonCocoonUpgradeContractsOp:                           TonCocoonUpgradeContractsPayloadBody{},
	TonTolkTestsBidaskDammProvideBothJettonPayloadOp:      TonTolkTestsBidaskDammProvideBoth{},
	TonCocoonOwnerClientChangeSecretHashOp:                TonCocoonOwnerClientChangeSecretHashPayloadBody{},
	TonTolkTestsMoonDepositLiquidityJettonPayloadOp:       TonTolkTestsMoonDepositLiquidity{},
	TonTolkTestsMoonSwapJettonPayloadOp:                   TonTolkTestsMoonSwap{},
	TonCocoonOwnerProxyCloseOp:                            TonCocoonOwnerProxyClosePayloadBody{},
	TonTolkTestsCoffeeCrossDexFailureJettonPayloadOp:      TonTolkTestsCoffeeCrossDexFailure{},
	TonCocoonExtClientChargeSignedOp:                      TonCocoonExtClientChargeSignedPayloadBody{},
	TonTolkTestsCoffeeSwapJettonPayloadOp:                 TonTolkTestsCoffeeSwap{},
	TonTolkTestsCoffeeCreatePoolJettonPayloadOp:           TonTolkTestsCoffeeCreatePool{},
	TonTolkTestsCoffeeDepositLiquidityJettonPayloadOp:     TonTolkTestsCoffeeDepositLiquidity{},
	TonTolkTestsCoffeeNotificationJettonPayloadOp:         TonTolkTestsCoffeeNotification{},
	TonCocoonAddModelTypeOp:                               TonCocoonAddModelTypePayloadBody{},
	TonCocoonOwnerClientRegisterOp:                        TonCocoonOwnerClientRegisterPayloadBody{},
	TonTolkTestsMoonSwapFailedJettonPayloadOp:             TonTolkTestsMoonSwapFailed{},
	TonCocoonChangeOwnerOp:                                TonCocoonChangeOwnerPayloadBody{},
	TonCocoonChangeFeesOp:                                 TonCocoonChangeFeesPayloadBody{},
	TonCocoonPayoutOp:                                     TonCocoonPayoutPayloadBody{},
	TonStonfiV2StonfiSwapOkJettonPayloadOp:                TonStonfiV2StonfiSwapOk{},
	TonTolkTestsStormStakeJettonPayloadOp:                 TonTolkTestsStormStake{},
	TonTolkTestsWithdrawPayloadJettonPayloadOp:            TonTolkTestsWithdrawPayload{},
	TonTolkTestsMoonSwapSucceedJettonPayloadOp:            TonTolkTestsMoonSwapSucceed{},
	TonTep74ResponseWalletAddressOp:                       TonTep74ResponseWalletAddressPayloadBody{},
	TonTep74AboaLisaOp:                                    TonTep74AboaLisaPayloadBody{},
	TonCocoonReturnExcessesBackOp:                         TonCocoonReturnExcessesBackPayloadBody{},
	TonTep74ReturnExcessesBackOp:                          TonTep74ReturnExcessesBackPayloadBody{},
	TonTolkTestsMoonCreateOrderJettonPayloadOp:            TonTolkTestsMoonCreateOrder{},
	TonCocoonOwnerClientWithdrawOp:                        TonCocoonOwnerClientWithdrawPayloadBody{},
	TonTolkTestsBidaskDammSwapJettonPayloadOp:             TonTolkTestsBidaskDammSwap{},
	TonCocoonAddWorkerTypeOp:                              TonCocoonAddWorkerTypePayloadBody{},
	TonTolkTestsDedustSwapJettonPayloadOp:                 TonTolkTestsDedustSwap{},
	TonCocoonExtProxyCloseCompleteRequestSignedOp:         TonCocoonExtProxyCloseCompleteRequestSignedPayloadBody{},
	TonTolkTestsCoffeeMevProtectFailedSwapJettonPayloadOp: TonTolkTestsCoffeeMevProtectFailedSwap{},
	TonCocoonExtClientGrantRefundSignedOp:                 TonCocoonExtClientGrantRefundSignedPayloadBody{},
	TonCocoonExtClientTopUpOp:                             TonCocoonExtClientTopUpPayloadBody{},
	TonTolkTestsBidaskSwapJettonPayloadOp:                 TonTolkTestsBidaskSwap{},
	TonCocoonExtWorkerLastPayoutRequestSignedOp:           TonCocoonExtWorkerLastPayoutRequestSignedPayloadBody{},
	TonTolkTestsDepositPayloadJettonPayloadOp:             TonTolkTestsDepositPayload{},
	TonCocoonOwnerClientRequestRefundOp:                   TonCocoonOwnerClientRequestRefundPayloadBody{},
	TonStonfiV2StonfiProvideLiquidityJettonPayloadOp:      TonStonfiV2StonfiProvideLiquidity{},
}
var PayloadOpCodes = map[PayloadOpName]PayloadOpCode{
	TonTolkTestsTextCommentJettonPayloadOp:                TonTolkTestsTextCommentJettonPayloadOpCode,
	TonCocoonTextCommandOp:                                TonCocoonTextCommandOpCode,
	TonCocoonTextCmdOp:                                    TonCocoonTextCmdOpCode,
	TonTep74ChangeMinterAdminOp:                           TonTep74ChangeMinterAdminOpCode,
	TonTep74ChangeMinterContentOp:                         TonTep74ChangeMinterContentOpCode,
	TonTep74MintNewJettonsOp:                              TonTep74MintNewJettonsOpCode,
	TonTolkTestsTegroJettonSwapJettonPayloadOp:            TonTolkTestsTegroJettonSwapJettonPayloadOpCode,
	TonCocoonChangeParamsOp:                               TonCocoonChangeParamsOpCode,
	TonTolkTestsCoffeeStakingLockJettonPayloadOp:          TonTolkTestsCoffeeStakingLockJettonPayloadOpCode,
	TonTep74AskToTransferOp:                               TonTep74AskToTransferOpCode,
	TonCocoonUpgradeCodeOp:                                TonCocoonUpgradeCodeOpCode,
	TonTep74InternalTransferStepOp:                        TonTep74InternalTransferStepOpCode,
	TonCoffeeCrossDexResendOp:                             TonCoffeeCrossDexResendOpCode,
	TonTolkTestsEncryptedTextCommentJettonPayloadOp:       TonTolkTestsEncryptedTextCommentJettonPayloadOpCode,
	TonStonfiV1StonfiSwapJettonPayloadOp:                  TonStonfiV1StonfiSwapJettonPayloadOpCode,
	TonCocoonOwnerWorkerRegisterOp:                        TonCocoonOwnerWorkerRegisterOpCode,
	TonTolkTestsTegroAddLiquidityJettonPayloadOp:          TonTolkTestsTegroAddLiquidityJettonPayloadOpCode,
	TonTep74RequestWalletAddressOp:                        TonTep74RequestWalletAddressOpCode,
	TonStonfiV2StonfiProvideLpV2JettonPayloadOp:           TonStonfiV2StonfiProvideLpV2JettonPayloadOpCode,
	TonCocoonDelProxyTypeOp:                               TonCocoonDelProxyTypeOpCode,
	TonTolkTestsBidaskProvideBothJettonPayloadOp:          TonTolkTestsBidaskProvideBothJettonPayloadOpCode,
	TonTolkTestsDedustDepositLiquidityJettonPayloadOp:     TonTolkTestsDedustDepositLiquidityJettonPayloadOpCode,
	TonTolkTestsPoolFundAccountJettonPayloadOp:            TonTolkTestsPoolFundAccountJettonPayloadOpCode,
	TonStonfiV1StonfiSwapOkRefJettonPayloadOp:             TonStonfiV1StonfiSwapOkRefJettonPayloadOpCode,
	TonCocoonWorkerProxyRequestOp:                         TonCocoonWorkerProxyRequestOpCode,
	TonTolkTestsCoffeeCrossDexResendJettonPayloadOp:       TonTolkTestsCoffeeCrossDexResendJettonPayloadOpCode,
	TonCocoonUpgradeFullOp:                                TonCocoonUpgradeFullOpCode,
	TonCocoonResetRootOp:                                  TonCocoonResetRootOpCode,
	TonTep74AskToBurnOp:                                   TonTep74AskToBurnOpCode,
	TonCocoonExtProxyCloseRequestSignedOp:                 TonCocoonExtProxyCloseRequestSignedOpCode,
	TonTolkTestsBidaskDammProvideJettonPayloadOp:          TonTolkTestsBidaskDammProvideJettonPayloadOpCode,
	TonCocoonClientProxyRequestOp:                         TonCocoonClientProxyRequestOpCode,
	TonStonfiV2StonfiSwapV2JettonPayloadOp:                TonStonfiV2StonfiSwapV2JettonPayloadOpCode,
	TonCocoonOwnerClientIncreaseStakeOp:                   TonCocoonOwnerClientIncreaseStakeOpCode,
	TonCocoonUnregisterProxyOp:                            TonCocoonUnregisterProxyOpCode,
	TonCocoonAddProxyTypeOp:                               TonCocoonAddProxyTypeOpCode,
	TonTolkTestsBidaskDammProvideOneSideJettonPayloadOp:   TonTolkTestsBidaskDammProvideOneSideJettonPayloadOpCode,
	TonTep74TransferNotificationForRecipientOp:            TonTep74TransferNotificationForRecipientOpCode,
	TonCocoonExtProxyPayoutRequestOp:                      TonCocoonExtProxyPayoutRequestOpCode,
	TonTolkTestsStormDepositJettonJettonPayloadOp:         TonTolkTestsStormDepositJettonJettonPayloadOpCode,
	TonTolkTestsInvoicePayloadJettonPayloadOp:             TonTolkTestsInvoicePayloadJettonPayloadOpCode,
	TonTep74BurnNotificationForMinterOp:                   TonTep74BurnNotificationForMinterOpCode,
	TonCocoonOwnerClientChangeSecretHashAndTopUpOp:        TonCocoonOwnerClientChangeSecretHashAndTopUpOpCode,
	TonTolkTestsTonkeeperRelayerFeeJettonPayloadOp:        TonTolkTestsTonkeeperRelayerFeeJettonPayloadOpCode,
	TonTolkTestsBidaskSwapV2JettonPayloadOp:               TonTolkTestsBidaskSwapV2JettonPayloadOpCode,
	TonCocoonDelWorkerTypeOp:                              TonCocoonDelWorkerTypeOpCode,
	TonCocoonRegisterProxyOp:                              TonCocoonRegisterProxyOpCode,
	TonCocoonDelModelTypeOp:                               TonCocoonDelModelTypeOpCode,
	TonTolkTestsMoonBoostPoolJettonPayloadOp:              TonTolkTestsMoonBoostPoolJettonPayloadOpCode,
	TonTolkTestsBidaskProvideJettonPayloadOp:              TonTolkTestsBidaskProvideJettonPayloadOpCode,
	TonCocoonExtProxyIncreaseStakeOp:                      TonCocoonExtProxyIncreaseStakeOpCode,
	TonTolkTestsMoonFillOrderJettonPayloadOp:              TonTolkTestsMoonFillOrderJettonPayloadOpCode,
	TonCocoonOwnerWalletSendMessageOp:                     TonCocoonOwnerWalletSendMessageOpCode,
	TonCocoonUpdateProxyOp:                                TonCocoonUpdateProxyOpCode,
	TonCocoonExtWorkerPayoutRequestSignedOp:               TonCocoonExtWorkerPayoutRequestSignedOpCode,
	TonCocoonUpgradeContractsOp:                           TonCocoonUpgradeContractsOpCode,
	TonTolkTestsBidaskDammProvideBothJettonPayloadOp:      TonTolkTestsBidaskDammProvideBothJettonPayloadOpCode,
	TonCocoonOwnerClientChangeSecretHashOp:                TonCocoonOwnerClientChangeSecretHashOpCode,
	TonTolkTestsMoonDepositLiquidityJettonPayloadOp:       TonTolkTestsMoonDepositLiquidityJettonPayloadOpCode,
	TonTolkTestsMoonSwapJettonPayloadOp:                   TonTolkTestsMoonSwapJettonPayloadOpCode,
	TonCocoonOwnerProxyCloseOp:                            TonCocoonOwnerProxyCloseOpCode,
	TonTolkTestsCoffeeCrossDexFailureJettonPayloadOp:      TonTolkTestsCoffeeCrossDexFailureJettonPayloadOpCode,
	TonCocoonExtClientChargeSignedOp:                      TonCocoonExtClientChargeSignedOpCode,
	TonTolkTestsCoffeeSwapJettonPayloadOp:                 TonTolkTestsCoffeeSwapJettonPayloadOpCode,
	TonTolkTestsCoffeeCreatePoolJettonPayloadOp:           TonTolkTestsCoffeeCreatePoolJettonPayloadOpCode,
	TonTolkTestsCoffeeDepositLiquidityJettonPayloadOp:     TonTolkTestsCoffeeDepositLiquidityJettonPayloadOpCode,
	TonTolkTestsCoffeeNotificationJettonPayloadOp:         TonTolkTestsCoffeeNotificationJettonPayloadOpCode,
	TonCocoonAddModelTypeOp:                               TonCocoonAddModelTypeOpCode,
	TonCocoonOwnerClientRegisterOp:                        TonCocoonOwnerClientRegisterOpCode,
	TonTolkTestsMoonSwapFailedJettonPayloadOp:             TonTolkTestsMoonSwapFailedJettonPayloadOpCode,
	TonCocoonChangeOwnerOp:                                TonCocoonChangeOwnerOpCode,
	TonCocoonChangeFeesOp:                                 TonCocoonChangeFeesOpCode,
	TonCocoonPayoutOp:                                     TonCocoonPayoutOpCode,
	TonStonfiV2StonfiSwapOkJettonPayloadOp:                TonStonfiV2StonfiSwapOkJettonPayloadOpCode,
	TonTolkTestsStormStakeJettonPayloadOp:                 TonTolkTestsStormStakeJettonPayloadOpCode,
	TonTolkTestsWithdrawPayloadJettonPayloadOp:            TonTolkTestsWithdrawPayloadJettonPayloadOpCode,
	TonTolkTestsMoonSwapSucceedJettonPayloadOp:            TonTolkTestsMoonSwapSucceedJettonPayloadOpCode,
	TonTep74ResponseWalletAddressOp:                       TonTep74ResponseWalletAddressOpCode,
	TonTep74AboaLisaOp:                                    TonTep74AboaLisaOpCode,
	TonCocoonReturnExcessesBackOp:                         TonCocoonReturnExcessesBackOpCode,
	TonTep74ReturnExcessesBackOp:                          TonTep74ReturnExcessesBackOpCode,
	TonTolkTestsMoonCreateOrderJettonPayloadOp:            TonTolkTestsMoonCreateOrderJettonPayloadOpCode,
	TonCocoonOwnerClientWithdrawOp:                        TonCocoonOwnerClientWithdrawOpCode,
	TonTolkTestsBidaskDammSwapJettonPayloadOp:             TonTolkTestsBidaskDammSwapJettonPayloadOpCode,
	TonCocoonAddWorkerTypeOp:                              TonCocoonAddWorkerTypeOpCode,
	TonTolkTestsDedustSwapJettonPayloadOp:                 TonTolkTestsDedustSwapJettonPayloadOpCode,
	TonCocoonExtProxyCloseCompleteRequestSignedOp:         TonCocoonExtProxyCloseCompleteRequestSignedOpCode,
	TonTolkTestsCoffeeMevProtectFailedSwapJettonPayloadOp: TonTolkTestsCoffeeMevProtectFailedSwapJettonPayloadOpCode,
	TonCocoonExtClientGrantRefundSignedOp:                 TonCocoonExtClientGrantRefundSignedOpCode,
	TonCocoonExtClientTopUpOp:                             TonCocoonExtClientTopUpOpCode,
	TonTolkTestsBidaskSwapJettonPayloadOp:                 TonTolkTestsBidaskSwapJettonPayloadOpCode,
	TonCocoonExtWorkerLastPayoutRequestSignedOp:           TonCocoonExtWorkerLastPayoutRequestSignedOpCode,
	TonTolkTestsDepositPayloadJettonPayloadOp:             TonTolkTestsDepositPayloadJettonPayloadOpCode,
	TonCocoonOwnerClientRequestRefundOp:                   TonCocoonOwnerClientRequestRefundOpCode,
	TonStonfiV2StonfiProvideLiquidityJettonPayloadOp:      TonStonfiV2StonfiProvideLiquidityJettonPayloadOpCode,
}

func (c ContractInterface) Payloads() map[PayloadOpCode][]func(*Payload, *boc.Cell) error {
	switch c {
	case TonCocoonClient:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonCocoonClientProxyRequestOpCode:                  {decodeTonCocoonClientProxyRequestOpPayload},
			TonCocoonOwnerClientIncreaseStakeOpCode:            {decodeTonCocoonOwnerClientIncreaseStakeOpPayload},
			TonCocoonOwnerClientChangeSecretHashAndTopUpOpCode: {decodeTonCocoonOwnerClientChangeSecretHashAndTopUpOpPayload},
			TonCocoonOwnerClientChangeSecretHashOpCode:         {decodeTonCocoonOwnerClientChangeSecretHashOpPayload},
			TonCocoonExtClientChargeSignedOpCode:               {decodeTonCocoonExtClientChargeSignedOpPayload},
			TonCocoonOwnerClientRegisterOpCode:                 {decodeTonCocoonOwnerClientRegisterOpPayload},
			TonCocoonPayoutOpCode:                              {decodeTonCocoonPayoutOpPayload},
			TonCocoonReturnExcessesBackOpCode:                  {decodeTonCocoonReturnExcessesBackOpPayload},
			TonCocoonOwnerClientWithdrawOpCode:                 {decodeTonCocoonOwnerClientWithdrawOpPayload},
			TonCocoonExtClientGrantRefundSignedOpCode:          {decodeTonCocoonExtClientGrantRefundSignedOpPayload},
			TonCocoonExtClientTopUpOpCode:                      {decodeTonCocoonExtClientTopUpOpPayload},
			TonCocoonOwnerClientRequestRefundOpCode:            {decodeTonCocoonOwnerClientRequestRefundOpPayload},
		}
	case TonCocoonProxy:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonCocoonTextCmdOpCode:                            {decodeTonCocoonTextCmdOpPayload},
			TonCocoonWorkerProxyRequestOpCode:                 {decodeTonCocoonWorkerProxyRequestOpPayload},
			TonCocoonExtProxyCloseRequestSignedOpCode:         {decodeTonCocoonExtProxyCloseRequestSignedOpPayload},
			TonCocoonExtProxyPayoutRequestOpCode:              {decodeTonCocoonExtProxyPayoutRequestOpPayload},
			TonCocoonExtProxyIncreaseStakeOpCode:              {decodeTonCocoonExtProxyIncreaseStakeOpPayload},
			TonCocoonOwnerProxyCloseOpCode:                    {decodeTonCocoonOwnerProxyCloseOpPayload},
			TonCocoonExtProxyCloseCompleteRequestSignedOpCode: {decodeTonCocoonExtProxyCloseCompleteRequestSignedOpPayload},
		}
	case TonCocoonRoot:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonCocoonChangeParamsOpCode:     {decodeTonCocoonChangeParamsOpPayload},
			TonCocoonUpgradeCodeOpCode:      {decodeTonCocoonUpgradeCodeOpPayload},
			TonCocoonDelProxyTypeOpCode:     {decodeTonCocoonDelProxyTypeOpPayload},
			TonCocoonUpgradeFullOpCode:      {decodeTonCocoonUpgradeFullOpPayload},
			TonCocoonResetRootOpCode:        {decodeTonCocoonResetRootOpPayload},
			TonCocoonUnregisterProxyOpCode:  {decodeTonCocoonUnregisterProxyOpPayload},
			TonCocoonAddProxyTypeOpCode:     {decodeTonCocoonAddProxyTypeOpPayload},
			TonCocoonDelWorkerTypeOpCode:    {decodeTonCocoonDelWorkerTypeOpPayload},
			TonCocoonRegisterProxyOpCode:    {decodeTonCocoonRegisterProxyOpPayload},
			TonCocoonDelModelTypeOpCode:     {decodeTonCocoonDelModelTypeOpPayload},
			TonCocoonUpdateProxyOpCode:      {decodeTonCocoonUpdateProxyOpPayload},
			TonCocoonUpgradeContractsOpCode: {decodeTonCocoonUpgradeContractsOpPayload},
			TonCocoonAddModelTypeOpCode:     {decodeTonCocoonAddModelTypeOpPayload},
			TonCocoonChangeOwnerOpCode:      {decodeTonCocoonChangeOwnerOpPayload},
			TonCocoonChangeFeesOpCode:       {decodeTonCocoonChangeFeesOpPayload},
			TonCocoonAddWorkerTypeOpCode:    {decodeTonCocoonAddWorkerTypeOpPayload},
		}
	case TonCocoonWallet:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonCocoonTextCommandOpCode:            {decodeTonCocoonTextCommandOpPayload},
			TonCocoonOwnerWalletSendMessageOpCode: {decodeTonCocoonOwnerWalletSendMessageOpPayload},
		}
	case TonCocoonWorker:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonCocoonOwnerWorkerRegisterOpCode:              {decodeTonCocoonOwnerWorkerRegisterOpPayload},
			TonCocoonExtWorkerPayoutRequestSignedOpCode:     {decodeTonCocoonExtWorkerPayoutRequestSignedOpPayload},
			TonCocoonExtWorkerLastPayoutRequestSignedOpCode: {decodeTonCocoonExtWorkerLastPayoutRequestSignedOpPayload},
		}
	case TonCoffeePool:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonCoffeeCrossDexResendOpCode: {decodeTonCoffeeCrossDexResendOpPayload},
		}
	case TonStonfiV1Pool:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonStonfiV1StonfiSwapJettonPayloadOpCode:      {decodeTonStonfiV1StonfiSwapJettonPayloadOpPayload},
			TonStonfiV1StonfiSwapOkRefJettonPayloadOpCode: {decodeTonStonfiV1StonfiSwapOkRefJettonPayloadOpPayload},
		}
	case TonStonfiV2Pool:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonStonfiV2StonfiProvideLpV2JettonPayloadOpCode:      {decodeTonStonfiV2StonfiProvideLpV2JettonPayloadOpPayload},
			TonStonfiV2StonfiSwapV2JettonPayloadOpCode:           {decodeTonStonfiV2StonfiSwapV2JettonPayloadOpPayload},
			TonStonfiV2StonfiSwapOkJettonPayloadOpCode:           {decodeTonStonfiV2StonfiSwapOkJettonPayloadOpPayload},
			TonStonfiV2StonfiProvideLiquidityJettonPayloadOpCode: {decodeTonStonfiV2StonfiProvideLiquidityJettonPayloadOpPayload},
		}
	case TonStonfiV2PoolConstProduct:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonStonfiV2StonfiProvideLpV2JettonPayloadOpCode:      {decodeTonStonfiV2StonfiProvideLpV2JettonPayloadOpPayload},
			TonStonfiV2StonfiSwapV2JettonPayloadOpCode:           {decodeTonStonfiV2StonfiSwapV2JettonPayloadOpPayload},
			TonStonfiV2StonfiSwapOkJettonPayloadOpCode:           {decodeTonStonfiV2StonfiSwapOkJettonPayloadOpPayload},
			TonStonfiV2StonfiProvideLiquidityJettonPayloadOpCode: {decodeTonStonfiV2StonfiProvideLiquidityJettonPayloadOpPayload},
		}
	case TonStonfiV2PoolStableSwap:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonStonfiV2StonfiProvideLpV2JettonPayloadOpCode:      {decodeTonStonfiV2StonfiProvideLpV2JettonPayloadOpPayload},
			TonStonfiV2StonfiSwapV2JettonPayloadOpCode:           {decodeTonStonfiV2StonfiSwapV2JettonPayloadOpPayload},
			TonStonfiV2StonfiSwapOkJettonPayloadOpCode:           {decodeTonStonfiV2StonfiSwapOkJettonPayloadOpPayload},
			TonStonfiV2StonfiProvideLiquidityJettonPayloadOpCode: {decodeTonStonfiV2StonfiProvideLiquidityJettonPayloadOpPayload},
		}
	case TonStonfiV2PoolWeightedStableSwap:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonStonfiV2StonfiProvideLpV2JettonPayloadOpCode:      {decodeTonStonfiV2StonfiProvideLpV2JettonPayloadOpPayload},
			TonStonfiV2StonfiSwapV2JettonPayloadOpCode:           {decodeTonStonfiV2StonfiSwapV2JettonPayloadOpPayload},
			TonStonfiV2StonfiSwapOkJettonPayloadOpCode:           {decodeTonStonfiV2StonfiSwapOkJettonPayloadOpPayload},
			TonStonfiV2StonfiProvideLiquidityJettonPayloadOpCode: {decodeTonStonfiV2StonfiProvideLiquidityJettonPayloadOpPayload},
		}
	case TonTep74JettonMinter:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonTep74ChangeMinterAdminOpCode:         {decodeTonTep74ChangeMinterAdminOpPayload},
			TonTep74ChangeMinterContentOpCode:       {decodeTonTep74ChangeMinterContentOpPayload},
			TonTep74MintNewJettonsOpCode:            {decodeTonTep74MintNewJettonsOpPayload},
			TonTep74InternalTransferStepOpCode:      {decodeTonTep74InternalTransferStepOpPayload},
			TonTep74RequestWalletAddressOpCode:      {decodeTonTep74RequestWalletAddressOpPayload},
			TonTep74BurnNotificationForMinterOpCode: {decodeTonTep74BurnNotificationForMinterOpPayload},
			TonTep74ResponseWalletAddressOpCode:     {decodeTonTep74ResponseWalletAddressOpPayload},
			TonTep74ReturnExcessesBackOpCode:        {decodeTonTep74ReturnExcessesBackOpPayload},
		}
	case TonTep74JettonWallet:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonTep74AskToTransferOpCode:                    {decodeTonTep74AskToTransferOpPayload},
			TonTep74AskToBurnOpCode:                        {decodeTonTep74AskToBurnOpPayload},
			TonTep74TransferNotificationForRecipientOpCode: {decodeTonTep74TransferNotificationForRecipientOpPayload},
			TonTep74AboaLisaOpCode:                         {decodeTonTep74AboaLisaOpPayload},
		}
	case TonTolkTestsPayloads:
		return map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
			TonTolkTestsTextCommentJettonPayloadOpCode:                {decodeTonTolkTestsTextCommentJettonPayloadOpPayload},
			TonTolkTestsTegroJettonSwapJettonPayloadOpCode:            {decodeTonTolkTestsTegroJettonSwapJettonPayloadOpPayload},
			TonTolkTestsCoffeeStakingLockJettonPayloadOpCode:          {decodeTonTolkTestsCoffeeStakingLockJettonPayloadOpPayload},
			TonTolkTestsEncryptedTextCommentJettonPayloadOpCode:       {decodeTonTolkTestsEncryptedTextCommentJettonPayloadOpPayload},
			TonTolkTestsTegroAddLiquidityJettonPayloadOpCode:          {decodeTonTolkTestsTegroAddLiquidityJettonPayloadOpPayload},
			TonTolkTestsBidaskProvideBothJettonPayloadOpCode:          {decodeTonTolkTestsBidaskProvideBothJettonPayloadOpPayload},
			TonTolkTestsDedustDepositLiquidityJettonPayloadOpCode:     {decodeTonTolkTestsDedustDepositLiquidityJettonPayloadOpPayload},
			TonTolkTestsPoolFundAccountJettonPayloadOpCode:            {decodeTonTolkTestsPoolFundAccountJettonPayloadOpPayload},
			TonTolkTestsCoffeeCrossDexResendJettonPayloadOpCode:       {decodeTonTolkTestsCoffeeCrossDexResendJettonPayloadOpPayload},
			TonTolkTestsBidaskDammProvideJettonPayloadOpCode:          {decodeTonTolkTestsBidaskDammProvideJettonPayloadOpPayload},
			TonTolkTestsBidaskDammProvideOneSideJettonPayloadOpCode:   {decodeTonTolkTestsBidaskDammProvideOneSideJettonPayloadOpPayload},
			TonTolkTestsStormDepositJettonJettonPayloadOpCode:         {decodeTonTolkTestsStormDepositJettonJettonPayloadOpPayload},
			TonTolkTestsInvoicePayloadJettonPayloadOpCode:             {decodeTonTolkTestsInvoicePayloadJettonPayloadOpPayload},
			TonTolkTestsTonkeeperRelayerFeeJettonPayloadOpCode:        {decodeTonTolkTestsTonkeeperRelayerFeeJettonPayloadOpPayload},
			TonTolkTestsBidaskSwapV2JettonPayloadOpCode:               {decodeTonTolkTestsBidaskSwapV2JettonPayloadOpPayload},
			TonTolkTestsMoonBoostPoolJettonPayloadOpCode:              {decodeTonTolkTestsMoonBoostPoolJettonPayloadOpPayload},
			TonTolkTestsBidaskProvideJettonPayloadOpCode:              {decodeTonTolkTestsBidaskProvideJettonPayloadOpPayload},
			TonTolkTestsMoonFillOrderJettonPayloadOpCode:              {decodeTonTolkTestsMoonFillOrderJettonPayloadOpPayload},
			TonTolkTestsBidaskDammProvideBothJettonPayloadOpCode:      {decodeTonTolkTestsBidaskDammProvideBothJettonPayloadOpPayload},
			TonTolkTestsMoonDepositLiquidityJettonPayloadOpCode:       {decodeTonTolkTestsMoonDepositLiquidityJettonPayloadOpPayload},
			TonTolkTestsMoonSwapJettonPayloadOpCode:                   {decodeTonTolkTestsMoonSwapJettonPayloadOpPayload},
			TonTolkTestsCoffeeCrossDexFailureJettonPayloadOpCode:      {decodeTonTolkTestsCoffeeCrossDexFailureJettonPayloadOpPayload},
			TonTolkTestsCoffeeSwapJettonPayloadOpCode:                 {decodeTonTolkTestsCoffeeSwapJettonPayloadOpPayload},
			TonTolkTestsCoffeeCreatePoolJettonPayloadOpCode:           {decodeTonTolkTestsCoffeeCreatePoolJettonPayloadOpPayload},
			TonTolkTestsCoffeeDepositLiquidityJettonPayloadOpCode:     {decodeTonTolkTestsCoffeeDepositLiquidityJettonPayloadOpPayload},
			TonTolkTestsCoffeeNotificationJettonPayloadOpCode:         {decodeTonTolkTestsCoffeeNotificationJettonPayloadOpPayload},
			TonTolkTestsMoonSwapFailedJettonPayloadOpCode:             {decodeTonTolkTestsMoonSwapFailedJettonPayloadOpPayload},
			TonTolkTestsStormStakeJettonPayloadOpCode:                 {decodeTonTolkTestsStormStakeJettonPayloadOpPayload},
			TonTolkTestsWithdrawPayloadJettonPayloadOpCode:            {decodeTonTolkTestsWithdrawPayloadJettonPayloadOpPayload},
			TonTolkTestsMoonSwapSucceedJettonPayloadOpCode:            {decodeTonTolkTestsMoonSwapSucceedJettonPayloadOpPayload},
			TonTolkTestsMoonCreateOrderJettonPayloadOpCode:            {decodeTonTolkTestsMoonCreateOrderJettonPayloadOpPayload},
			TonTolkTestsBidaskDammSwapJettonPayloadOpCode:             {decodeTonTolkTestsBidaskDammSwapJettonPayloadOpPayload},
			TonTolkTestsDedustSwapJettonPayloadOpCode:                 {decodeTonTolkTestsDedustSwapJettonPayloadOpPayload},
			TonTolkTestsCoffeeMevProtectFailedSwapJettonPayloadOpCode: {decodeTonTolkTestsCoffeeMevProtectFailedSwapJettonPayloadOpPayload},
			TonTolkTestsBidaskSwapJettonPayloadOpCode:                 {decodeTonTolkTestsBidaskSwapJettonPayloadOpPayload},
			TonTolkTestsDepositPayloadJettonPayloadOpCode:             {decodeTonTolkTestsDepositPayloadJettonPayloadOpPayload},
		}
	default:
		return nil
	}
}

var funcPayloadDecodersMapping = map[PayloadOpCode][]func(*Payload, *boc.Cell) error{
	0: {
		decodeTonTolkTestsTextCommentJettonPayloadOpPayload,
		decodeTonCocoonTextCommandOpPayload,
		decodeTonCocoonTextCmdOpPayload,
	},
	TonTep74ChangeMinterAdminOpCode:                         {decodeTonTep74ChangeMinterAdminOpPayload},
	TonTep74ChangeMinterContentOpCode:                       {decodeTonTep74ChangeMinterContentOpPayload},
	TonTep74MintNewJettonsOpCode:                            {decodeTonTep74MintNewJettonsOpPayload},
	TonTolkTestsTegroJettonSwapJettonPayloadOpCode:          {decodeTonTolkTestsTegroJettonSwapJettonPayloadOpPayload},
	TonCocoonChangeParamsOpCode:                             {decodeTonCocoonChangeParamsOpPayload},
	TonTolkTestsCoffeeStakingLockJettonPayloadOpCode:        {decodeTonTolkTestsCoffeeStakingLockJettonPayloadOpPayload},
	TonTep74AskToTransferOpCode:                             {decodeTonTep74AskToTransferOpPayload},
	TonCocoonUpgradeCodeOpCode:                              {decodeTonCocoonUpgradeCodeOpPayload},
	TonTep74InternalTransferStepOpCode:                      {decodeTonTep74InternalTransferStepOpPayload},
	TonCoffeeCrossDexResendOpCode:                           {decodeTonCoffeeCrossDexResendOpPayload},
	TonTolkTestsEncryptedTextCommentJettonPayloadOpCode:     {decodeTonTolkTestsEncryptedTextCommentJettonPayloadOpPayload},
	TonStonfiV1StonfiSwapJettonPayloadOpCode:                {decodeTonStonfiV1StonfiSwapJettonPayloadOpPayload},
	TonCocoonOwnerWorkerRegisterOpCode:                      {decodeTonCocoonOwnerWorkerRegisterOpPayload},
	TonTolkTestsTegroAddLiquidityJettonPayloadOpCode:        {decodeTonTolkTestsTegroAddLiquidityJettonPayloadOpPayload},
	TonTep74RequestWalletAddressOpCode:                      {decodeTonTep74RequestWalletAddressOpPayload},
	TonStonfiV2StonfiProvideLpV2JettonPayloadOpCode:         {decodeTonStonfiV2StonfiProvideLpV2JettonPayloadOpPayload},
	TonCocoonDelProxyTypeOpCode:                             {decodeTonCocoonDelProxyTypeOpPayload},
	TonTolkTestsBidaskProvideBothJettonPayloadOpCode:        {decodeTonTolkTestsBidaskProvideBothJettonPayloadOpPayload},
	TonTolkTestsDedustDepositLiquidityJettonPayloadOpCode:   {decodeTonTolkTestsDedustDepositLiquidityJettonPayloadOpPayload},
	TonTolkTestsPoolFundAccountJettonPayloadOpCode:          {decodeTonTolkTestsPoolFundAccountJettonPayloadOpPayload},
	TonStonfiV1StonfiSwapOkRefJettonPayloadOpCode:           {decodeTonStonfiV1StonfiSwapOkRefJettonPayloadOpPayload},
	TonCocoonWorkerProxyRequestOpCode:                       {decodeTonCocoonWorkerProxyRequestOpPayload},
	TonTolkTestsCoffeeCrossDexResendJettonPayloadOpCode:     {decodeTonTolkTestsCoffeeCrossDexResendJettonPayloadOpPayload},
	TonCocoonUpgradeFullOpCode:                              {decodeTonCocoonUpgradeFullOpPayload},
	TonCocoonResetRootOpCode:                                {decodeTonCocoonResetRootOpPayload},
	TonTep74AskToBurnOpCode:                                 {decodeTonTep74AskToBurnOpPayload},
	TonCocoonExtProxyCloseRequestSignedOpCode:               {decodeTonCocoonExtProxyCloseRequestSignedOpPayload},
	TonTolkTestsBidaskDammProvideJettonPayloadOpCode:        {decodeTonTolkTestsBidaskDammProvideJettonPayloadOpPayload},
	TonCocoonClientProxyRequestOpCode:                       {decodeTonCocoonClientProxyRequestOpPayload},
	TonStonfiV2StonfiSwapV2JettonPayloadOpCode:              {decodeTonStonfiV2StonfiSwapV2JettonPayloadOpPayload},
	TonCocoonOwnerClientIncreaseStakeOpCode:                 {decodeTonCocoonOwnerClientIncreaseStakeOpPayload},
	TonCocoonUnregisterProxyOpCode:                          {decodeTonCocoonUnregisterProxyOpPayload},
	TonCocoonAddProxyTypeOpCode:                             {decodeTonCocoonAddProxyTypeOpPayload},
	TonTolkTestsBidaskDammProvideOneSideJettonPayloadOpCode: {decodeTonTolkTestsBidaskDammProvideOneSideJettonPayloadOpPayload},
	TonTep74TransferNotificationForRecipientOpCode:          {decodeTonTep74TransferNotificationForRecipientOpPayload},
	TonCocoonExtProxyPayoutRequestOpCode:                    {decodeTonCocoonExtProxyPayoutRequestOpPayload},
	TonTolkTestsStormDepositJettonJettonPayloadOpCode:       {decodeTonTolkTestsStormDepositJettonJettonPayloadOpPayload},
	TonTolkTestsInvoicePayloadJettonPayloadOpCode:           {decodeTonTolkTestsInvoicePayloadJettonPayloadOpPayload},
	TonTep74BurnNotificationForMinterOpCode:                 {decodeTonTep74BurnNotificationForMinterOpPayload},
	TonCocoonOwnerClientChangeSecretHashAndTopUpOpCode:      {decodeTonCocoonOwnerClientChangeSecretHashAndTopUpOpPayload},
	TonTolkTestsTonkeeperRelayerFeeJettonPayloadOpCode:      {decodeTonTolkTestsTonkeeperRelayerFeeJettonPayloadOpPayload},
	TonTolkTestsBidaskSwapV2JettonPayloadOpCode:             {decodeTonTolkTestsBidaskSwapV2JettonPayloadOpPayload},
	TonCocoonDelWorkerTypeOpCode:                            {decodeTonCocoonDelWorkerTypeOpPayload},
	TonCocoonRegisterProxyOpCode:                            {decodeTonCocoonRegisterProxyOpPayload},
	TonCocoonDelModelTypeOpCode:                             {decodeTonCocoonDelModelTypeOpPayload},
	TonTolkTestsMoonBoostPoolJettonPayloadOpCode:            {decodeTonTolkTestsMoonBoostPoolJettonPayloadOpPayload},
	TonTolkTestsBidaskProvideJettonPayloadOpCode:            {decodeTonTolkTestsBidaskProvideJettonPayloadOpPayload},
	TonCocoonExtProxyIncreaseStakeOpCode:                    {decodeTonCocoonExtProxyIncreaseStakeOpPayload},
	TonTolkTestsMoonFillOrderJettonPayloadOpCode:            {decodeTonTolkTestsMoonFillOrderJettonPayloadOpPayload},
	TonCocoonOwnerWalletSendMessageOpCode:                   {decodeTonCocoonOwnerWalletSendMessageOpPayload},
	TonCocoonUpdateProxyOpCode:                              {decodeTonCocoonUpdateProxyOpPayload},
	TonCocoonExtWorkerPayoutRequestSignedOpCode:             {decodeTonCocoonExtWorkerPayoutRequestSignedOpPayload},
	TonCocoonUpgradeContractsOpCode:                         {decodeTonCocoonUpgradeContractsOpPayload},
	TonTolkTestsBidaskDammProvideBothJettonPayloadOpCode:    {decodeTonTolkTestsBidaskDammProvideBothJettonPayloadOpPayload},
	TonCocoonOwnerClientChangeSecretHashOpCode:              {decodeTonCocoonOwnerClientChangeSecretHashOpPayload},
	TonTolkTestsMoonDepositLiquidityJettonPayloadOpCode:     {decodeTonTolkTestsMoonDepositLiquidityJettonPayloadOpPayload},
	TonTolkTestsMoonSwapJettonPayloadOpCode:                 {decodeTonTolkTestsMoonSwapJettonPayloadOpPayload},
	TonCocoonOwnerProxyCloseOpCode:                          {decodeTonCocoonOwnerProxyCloseOpPayload},
	TonTolkTestsCoffeeCrossDexFailureJettonPayloadOpCode:    {decodeTonTolkTestsCoffeeCrossDexFailureJettonPayloadOpPayload},
	TonCocoonExtClientChargeSignedOpCode:                    {decodeTonCocoonExtClientChargeSignedOpPayload},
	TonTolkTestsCoffeeSwapJettonPayloadOpCode:               {decodeTonTolkTestsCoffeeSwapJettonPayloadOpPayload},
	TonTolkTestsCoffeeCreatePoolJettonPayloadOpCode:         {decodeTonTolkTestsCoffeeCreatePoolJettonPayloadOpPayload},
	TonTolkTestsCoffeeDepositLiquidityJettonPayloadOpCode:   {decodeTonTolkTestsCoffeeDepositLiquidityJettonPayloadOpPayload},
	TonTolkTestsCoffeeNotificationJettonPayloadOpCode:       {decodeTonTolkTestsCoffeeNotificationJettonPayloadOpPayload},
	TonCocoonAddModelTypeOpCode:                             {decodeTonCocoonAddModelTypeOpPayload},
	TonCocoonOwnerClientRegisterOpCode:                      {decodeTonCocoonOwnerClientRegisterOpPayload},
	TonTolkTestsMoonSwapFailedJettonPayloadOpCode:           {decodeTonTolkTestsMoonSwapFailedJettonPayloadOpPayload},
	TonCocoonChangeOwnerOpCode:                              {decodeTonCocoonChangeOwnerOpPayload},
	TonCocoonChangeFeesOpCode:                               {decodeTonCocoonChangeFeesOpPayload},
	TonCocoonPayoutOpCode:                                   {decodeTonCocoonPayoutOpPayload},
	TonStonfiV2StonfiSwapOkJettonPayloadOpCode:              {decodeTonStonfiV2StonfiSwapOkJettonPayloadOpPayload},
	TonTolkTestsStormStakeJettonPayloadOpCode:               {decodeTonTolkTestsStormStakeJettonPayloadOpPayload},
	TonTolkTestsWithdrawPayloadJettonPayloadOpCode:          {decodeTonTolkTestsWithdrawPayloadJettonPayloadOpPayload},
	TonTolkTestsMoonSwapSucceedJettonPayloadOpCode:          {decodeTonTolkTestsMoonSwapSucceedJettonPayloadOpPayload},
	TonTep74ResponseWalletAddressOpCode:                     {decodeTonTep74ResponseWalletAddressOpPayload},
	3576854235: {
		decodeTonTep74AboaLisaOpPayload,
		decodeTonCocoonReturnExcessesBackOpPayload,
		decodeTonTep74ReturnExcessesBackOpPayload,
	},
	TonTolkTestsMoonCreateOrderJettonPayloadOpCode:            {decodeTonTolkTestsMoonCreateOrderJettonPayloadOpPayload},
	TonCocoonOwnerClientWithdrawOpCode:                        {decodeTonCocoonOwnerClientWithdrawOpPayload},
	TonTolkTestsBidaskDammSwapJettonPayloadOpCode:             {decodeTonTolkTestsBidaskDammSwapJettonPayloadOpPayload},
	TonCocoonAddWorkerTypeOpCode:                              {decodeTonCocoonAddWorkerTypeOpPayload},
	TonTolkTestsDedustSwapJettonPayloadOpCode:                 {decodeTonTolkTestsDedustSwapJettonPayloadOpPayload},
	TonCocoonExtProxyCloseCompleteRequestSignedOpCode:         {decodeTonCocoonExtProxyCloseCompleteRequestSignedOpPayload},
	TonTolkTestsCoffeeMevProtectFailedSwapJettonPayloadOpCode: {decodeTonTolkTestsCoffeeMevProtectFailedSwapJettonPayloadOpPayload},
	TonCocoonExtClientGrantRefundSignedOpCode:                 {decodeTonCocoonExtClientGrantRefundSignedOpPayload},
	TonCocoonExtClientTopUpOpCode:                             {decodeTonCocoonExtClientTopUpOpPayload},
	TonTolkTestsBidaskSwapJettonPayloadOpCode:                 {decodeTonTolkTestsBidaskSwapJettonPayloadOpPayload},
	TonCocoonExtWorkerLastPayoutRequestSignedOpCode:           {decodeTonCocoonExtWorkerLastPayoutRequestSignedOpPayload},
	TonTolkTestsDepositPayloadJettonPayloadOpCode:             {decodeTonTolkTestsDepositPayloadJettonPayloadOpPayload},
	TonCocoonOwnerClientRequestRefundOpCode:                   {decodeTonCocoonOwnerClientRequestRefundOpPayload},
	TonStonfiV2StonfiProvideLiquidityJettonPayloadOpCode:      {decodeTonStonfiV2StonfiProvideLiquidityJettonPayloadOpPayload},
}

type TonTolkTestsTextComment struct {
	Text tlb.Any
}

type TonCocoonTextCommandPayloadBody = TonCocoonTextCommand

type TonCocoonTextCmdPayloadBody = TonCocoonTextCmd

type TonTep74ChangeMinterAdminPayloadBody = TonTep74ChangeMinterAdmin

type TonTep74ChangeMinterContentPayloadBody = TonTep74ChangeMinterContent

type TonTep74MintNewJettonsPayloadBody = TonTep74MintNewJettons

type TonTolkTestsTegroJettonSwap struct {
	Extract          bool
	MaxIn            tlb.VarUInteger16
	MinOut           tlb.VarUInteger16
	Destination      tlb.MsgAddress
	ErrorDestination tlb.MsgAddress
	Payload          tlb.Any `tlb:"^"`
}

type TonCocoonChangeParamsPayloadBody = TonCocoonChangeParams

type TonTolkTestsCoffeeStakingLock struct {
	PeriodID uint32
}

type TonTep74AskToTransferPayloadBody = TonTep74AskToTransfer

type TonCocoonUpgradeCodePayloadBody = TonCocoonUpgradeCode

type TonTep74InternalTransferStepPayloadBody = TonTep74InternalTransferStep

type TonCoffeeCrossDexResendPayloadBody = TonCoffeeCrossDexResend

type TonTolkTestsEncryptedTextComment struct {
	CipherText tlb.Any
}

type TonStonfiV1StonfiSwap struct {
	TokenWallet     tlb.MsgAddress
	MinOut          tlb.VarUInteger16
	ToAddress       tlb.MsgAddress
	ReferralAddress tlb.MsgAddress
}

type TonCocoonOwnerWorkerRegisterPayloadBody = TonCocoonOwnerWorkerRegister

type TonTolkTestsTegroAddLiquidity struct {
	AmountA tlb.VarUInteger16
	AmountB tlb.VarUInteger16
}

type TonTep74RequestWalletAddressPayloadBody = TonTep74RequestWalletAddress

type TonStonfiV2StonfiProvideLpV2 struct {
	TokenWallet1       tlb.MsgAddress
	RefundAddress      tlb.MsgAddress
	ExcessesAddress    tlb.MsgAddress
	TxDeadline         uint64
	CrossProvideLpBody TonStonfiV2CrossProvideLpBody `tlb:"^"`
}

type TonCocoonDelProxyTypePayloadBody = TonCocoonDelProxyType

type TonTolkTestsBidaskProvideBoth struct {
	TonAmount      tlb.VarUInteger16
	DepositType    tlb.Uint4
	LiquidityDict  tlb.HashmapE[tlb.Uint32, int32]
	RejectPayload  *tlb.Any `tlb:"maybe^"`
	ForwardPayload *tlb.Any `tlb:"maybe^"`
}

type TonTolkTestsDedustDepositLiquidity struct {
	PoolType            TonTolkTestsDedustPoolType
	Asset0              TonTolkTestsDedustAsset
	Asset1              TonTolkTestsDedustAsset
	Asset0TargetBalance tlb.VarUInteger16
	Asset1TargetBalance tlb.VarUInteger16
	FulfillPayload      *tlb.Any `tlb:"maybe^"`
	RejectPayload       *tlb.Any `tlb:"maybe^"`
}

type TonTolkTestsPoolFundAccount struct {
	JettonTarget tlb.MsgAddress
	Enough0      tlb.VarUInteger16
	Enough1      tlb.VarUInteger16
	Liquidity    tlb.Uint128
	TickLower    tlb.Int24
	TickUpper    tlb.Int24
}

type TonStonfiV1StonfiSwapOkRef struct {
}

type TonCocoonWorkerProxyRequestPayloadBody = TonCocoonWorkerProxyRequest

type TonTolkTestsCoffeeCrossDexResend struct {
	Next *tlb.Any `tlb:"maybe^"`
}

type TonCocoonUpgradeFullPayloadBody = TonCocoonUpgradeFull

type TonCocoonResetRootPayloadBody = TonCocoonResetRoot

type TonTep74AskToBurnPayloadBody = TonTep74AskToBurn

type TonCocoonExtProxyCloseRequestSignedPayloadBody = TonCocoonExtProxyCloseRequestSigned

type TonTolkTestsBidaskDammProvide struct {
	Receiver       tlb.MsgAddress
	LockLiquidity  bool
	RejectPayload  *tlb.Any `tlb:"maybe^"`
	ForwardPayload *tlb.Any `tlb:"maybe^"`
}

type TonCocoonClientProxyRequestPayloadBody = TonCocoonClientProxyRequest

type TonStonfiV2StonfiSwapV2 struct {
	TokenWallet1    tlb.MsgAddress
	RefundAddress   tlb.MsgAddress
	ExcessesAddress tlb.MsgAddress
	TxDeadline      uint64
	CrossSwapBody   TonStonfiV2CrossSwapBody `tlb:"^"`
}

type TonCocoonOwnerClientIncreaseStakePayloadBody = TonCocoonOwnerClientIncreaseStake

type TonCocoonUnregisterProxyPayloadBody = TonCocoonUnregisterProxy

type TonCocoonAddProxyTypePayloadBody = TonCocoonAddProxyType

type TonTolkTestsBidaskDammProvideOneSide struct {
	Receiver       tlb.MsgAddress
	LockLiquidity  bool
	RejectPayload  *tlb.Any `tlb:"maybe^"`
	ForwardPayload *tlb.Any `tlb:"maybe^"`
}

type TonTep74TransferNotificationForRecipientPayloadBody = TonTep74TransferNotificationForRecipient

type TonCocoonExtProxyPayoutRequestPayloadBody = TonCocoonExtProxyPayoutRequest

type TonTolkTestsStormDepositJetton struct {
	QueryId         uint64
	ReceiverAddress tlb.MsgAddress
	Init            bool
	KeyInit         TonTolkTestsInitializationRequest
}

type TonTolkTestsInvoicePayload struct {
	Id  tlb.Bits128
	Url TonTolkTestsInvoiceUrl
}

type TonTep74BurnNotificationForMinterPayloadBody = TonTep74BurnNotificationForMinter

type TonCocoonOwnerClientChangeSecretHashAndTopUpPayloadBody = TonCocoonOwnerClientChangeSecretHashAndTopUp

type TonTolkTestsTonkeeperRelayerFee struct {
}

type TonTolkTestsBidaskSwapV2 struct {
	ToAddress      tlb.MsgAddress
	Slippage       tlb.Either[tlb.VarUInteger16, tlb.Uint256]
	ExactOut       tlb.VarUInteger16
	AdditionalData *TonTolkTestsAdditionalData `tlb:"maybe^"`
	RejectPayload  *tlb.Any                    `tlb:"maybe^"`
	ForwardPayload *tlb.Any                    `tlb:"maybe^"`
}

type TonCocoonDelWorkerTypePayloadBody = TonCocoonDelWorkerType

type TonCocoonRegisterProxyPayloadBody = TonCocoonRegisterProxy

type TonCocoonDelModelTypePayloadBody = TonCocoonDelModelType

type TonTolkTestsMoonBoostPool struct {
}

type TonTolkTestsBidaskProvide struct {
	DepositType    tlb.Uint4
	LiquidityDict  tlb.HashmapE[tlb.Uint32, int32]
	RejectPayload  *tlb.Any `tlb:"maybe^"`
	ForwardPayload *tlb.Any `tlb:"maybe^"`
}

type TonCocoonExtProxyIncreaseStakePayloadBody = TonCocoonExtProxyIncreaseStake

type TonTolkTestsMoonFillOrder struct {
	Recipient        tlb.MsgAddress
	RecipientPayload *tlb.Any `tlb:"maybe^"`
	RejectAddress    tlb.MsgAddress
}

type TonCocoonOwnerWalletSendMessagePayloadBody = TonCocoonOwnerWalletSendMessage

type TonCocoonUpdateProxyPayloadBody = TonCocoonUpdateProxy

type TonCocoonExtWorkerPayoutRequestSignedPayloadBody = TonCocoonExtWorkerPayoutRequestSigned

type TonCocoonUpgradeContractsPayloadBody = TonCocoonUpgradeContracts

type TonTolkTestsBidaskDammProvideBoth struct {
	NativeAmount   tlb.VarUInteger16
	Reciever       tlb.MsgAddress
	LockLiquidity  bool
	RejectPayload  *tlb.Any `tlb:"maybe^"`
	ForwardPayload *tlb.Any `tlb:"maybe^"`
}

type TonCocoonOwnerClientChangeSecretHashPayloadBody = TonCocoonOwnerClientChangeSecretHash

type TonTolkTestsMoonDepositLiquidity struct {
	MinLpOut tlb.VarUInteger16
}

type TonTolkTestsMoonSwap struct {
	MoonSwap TonTolkTestsMoonSwapParams
}

type TonCocoonOwnerProxyClosePayloadBody = TonCocoonOwnerProxyClose

type TonTolkTestsCoffeeCrossDexFailure struct {
	QueryId   uint64
	Recipient tlb.MsgAddress
}

type TonCocoonExtClientChargeSignedPayloadBody = TonCocoonExtClientChargeSigned

type TonTolkTestsCoffeeSwap struct {
	Step   TonTolkTestsCoffeeSwapStepParams
	Params TonTolkTestsCoffeeSwapParams `tlb:"^"`
}

type TonTolkTestsCoffeeCreatePool struct {
	Params         TonTolkTestsCoffeePoolParams
	CreationParams TonTolkTestsCoffeePoolCreationParams
}

type TonTolkTestsCoffeeDepositLiquidity struct {
	Params TonTolkTestsCoffeeDepositLiquidityParams
}

type TonTolkTestsCoffeeNotification struct {
	QueryId uint64
	Body    tlb.Any `tlb:"^"`
}

type TonCocoonAddModelTypePayloadBody = TonCocoonAddModelType

type TonCocoonOwnerClientRegisterPayloadBody = TonCocoonOwnerClientRegister

type TonTolkTestsMoonSwapFailed struct {
}

type TonCocoonChangeOwnerPayloadBody = TonCocoonChangeOwner

type TonCocoonChangeFeesPayloadBody = TonCocoonChangeFees

type TonCocoonPayoutPayloadBody = TonCocoonPayout

type TonStonfiV2StonfiSwapOk struct {
}

type TonTolkTestsStormStake struct {
}

type TonTolkTestsWithdrawPayload struct {
	AssetAddress     tlb.MsgAddress
	OracleParams     *tlb.Any `tlb:"maybe^"`
	ForwardTonAmount tlb.VarUInteger16
	ForwardPayload   *tlb.Any `tlb:"maybe^"`
}

type TonTolkTestsMoonSwapSucceed struct {
}

type TonTep74ResponseWalletAddressPayloadBody = TonTep74ResponseWalletAddress

type TonTep74AboaLisaPayloadBody = TonTep74AboaLisa

type TonCocoonReturnExcessesBackPayloadBody = TonCocoonReturnExcessesBack

type TonTep74ReturnExcessesBackPayloadBody = TonTep74ReturnExcessesBack

type TonTolkTestsMoonCreateOrder struct {
	Asset1    tlb.MsgAddress
	Asset2    tlb.MsgAddress
	OrderData TonTolkTestsMoonOrderParams
}

type TonCocoonOwnerClientWithdrawPayloadBody = TonCocoonOwnerClientWithdraw

type TonTolkTestsBidaskDammSwap struct {
	ToAddress      tlb.MsgAddress
	Slippage       tlb.VarUInteger16
	FromAddress    tlb.MsgAddress
	ExactOut       tlb.VarUInteger16
	AdditionalData *tlb.Any `tlb:"maybe^"`
	RejectPayload  *tlb.Any `tlb:"maybe^"`
	ForwardPayload *tlb.Any `tlb:"maybe^"`
}

type TonCocoonAddWorkerTypePayloadBody = TonCocoonAddWorkerType

type TonTolkTestsDedustSwap struct {
	Step       TonTolkTestsDedustSwapStep
	SwapParams TonTolkTestsDedustSwapParams `tlb:"^"`
}

type TonCocoonExtProxyCloseCompleteRequestSignedPayloadBody = TonCocoonExtProxyCloseCompleteRequestSigned

type TonTolkTestsCoffeeMevProtectFailedSwap struct {
	QueryId   uint64
	Recipient tlb.MsgAddress
}

type TonCocoonExtClientGrantRefundSignedPayloadBody = TonCocoonExtClientGrantRefundSigned

type TonCocoonExtClientTopUpPayloadBody = TonCocoonExtClientTopUp

type TonTolkTestsBidaskSwap struct {
	ToAddress      tlb.MsgAddress
	Slippage       tlb.Either[tlb.VarUInteger16, tlb.Uint256]
	ExactOut       tlb.VarUInteger16
	RefAddress     tlb.MsgAddress
	AdditionalData *tlb.Any `tlb:"maybe^"`
	RejectPayload  *tlb.Any `tlb:"maybe^"`
	ForwardPayload *tlb.Any `tlb:"maybe^"`
}

type TonCocoonExtWorkerLastPayoutRequestSignedPayloadBody = TonCocoonExtWorkerLastPayoutRequestSigned

type TonTolkTestsDepositPayload struct {
	OracleParams     *tlb.Any `tlb:"maybe^"`
	ForwardTonAmount tlb.VarUInteger16
	ForwardPayload   *tlb.Any `tlb:"maybe^"`
}

type TonCocoonOwnerClientRequestRefundPayloadBody = TonCocoonOwnerClientRequestRefund

type TonStonfiV2StonfiProvideLiquidity struct {
	TokenWallet tlb.MsgAddress
	MinLpOut    tlb.VarUInteger16
}
