package abi

// Code autogenerated. DO NOT EDIT.

import (
	"fmt"
	"github.com/startfellows/tongo/boc"
	"github.com/startfellows/tongo/tlb"
)

type ContentData struct {
	tlb.SumType
	Snake struct {
		Data tlb.SnakeData
	} `tlbSumType:"#00"`
	Chunks struct {
		Data tlb.ChunkedData
	} `tlbSumType:"#01"`
}

type FullContent struct {
	tlb.SumType
	Onchain struct {
		Data tlb.HashmapE[tlb.Bits256, tlb.Ref[ContentData]]
	} `tlbSumType:"#00"`
	Offchain struct {
		Uri tlb.Text
	} `tlbSumType:"#01"`
}

type ConditionalPayment struct {
	Amount    tlb.Grams
	Condition tlb.Any
}

type SemiChannelBody struct {
	Seqno        uint64
	Sent         tlb.Grams
	Conditionals tlb.HashmapE[tlb.Uint32, ConditionalPayment]
}

type SemiChannel struct {
	Magic            tlb.Magic `tlb:"#43685374"`
	ChannelId        tlb.Uint128
	Data             SemiChannelBody
	CounterpartyData tlb.Maybe[tlb.Ref[SemiChannelBody]]
}

type SignedSemiChannel struct {
	Signature tlb.Bits512
	State     SemiChannel
}

type QuarantinedState struct {
	StateA           SemiChannelBody
	StateB           SemiChannelBody
	QuarantineStarts uint32
	StateCommitedByA bool
}

type ClosingConfig struct {
	QuarantinDuration        uint32
	MisbehaviorFine          tlb.Grams
	ConditionalCloseDuration uint32
}

type PaymentConfig struct {
	ExcessFee tlb.Grams
	DestA     tlb.MsgAddress
	DestB     tlb.MsgAddress
}

type Storage struct {
	BalanceA       tlb.Grams
	BalanceB       tlb.Grams
	KeyA           tlb.Uint256
	KeyB           tlb.Uint256
	ChannelId      tlb.Uint128
	Config         tlb.Ref[ClosingConfig]
	CommitedSeqnoA uint32
	CommitedSeqnoB uint32
	Quarantin      tlb.Maybe[tlb.Ref[QuarantinedState]]
	Payments       tlb.Ref[PaymentConfig]
}

type TextCommentTextCommentInternalMsgBody struct {
	Text tlb.Text
}

type PaymentChannelSettleConditionalsInternalMsgBody struct {
	FromA                bool
	Signature            tlb.Bits512
	Tag                  uint32
	ChannelId            tlb.Uint128
	ConditionalsToSettle tlb.HashmapE[tlb.Uint32, tlb.Any]
}

type Tep85SbtProveOwnershipInternalMsgBody struct {
	QueryId        uint64
	Dest           tlb.MsgAddress
	ForwardPayload tlb.Ref[tlb.Any]
	WithContent    bool
}

type Tep62NftItemOwnershipAssignedInternalMsgBody struct {
	QueryId        uint64
	PrevOwner      tlb.MsgAddress
	ForwardPayload tlb.EitherRef[tlb.Any]
}

type Tep85SbtOwnershipProofInternalMsgBody struct {
	QueryId   uint64
	ItemId    tlb.Uint256
	Owner     tlb.MsgAddress
	Data      tlb.Ref[tlb.Any]
	RevokedAt uint64
	Content   tlb.Maybe[tlb.Ref[tlb.Any]]
}

type Tep85SbtOwnerInfoInternalMsgBody struct {
	QueryId   uint64
	ItemId    tlb.Uint256
	Initiator tlb.MsgAddress
	Owner     tlb.MsgAddress
	Data      tlb.Ref[tlb.Any]
	RevokedAt uint64
	Content   tlb.Maybe[tlb.Ref[tlb.Any]]
}

type PaymentChannelCooperativeCloseInternalMsgBody struct {
	SigA      tlb.Ref[tlb.Bits512]
	SigB      tlb.Ref[tlb.Bits512]
	Tag       uint32
	ChannelId tlb.Uint128
	BalanceA  tlb.Grams
	BalanceB  tlb.Grams
	SeqnoA    uint64
	SeqnoB    uint64
}

type Tep74JettonWalletTransferInternalMsgBody struct {
	QueryId             uint64
	Amount              tlb.VarUInteger16
	Destination         tlb.MsgAddress
	ResponseDestination tlb.MsgAddress
	CustomPayload       tlb.Maybe[tlb.Ref[tlb.Any]]
	ForwardTonAmount    tlb.VarUInteger16
	ForwardPayload      tlb.EitherRef[tlb.Any]
}

type Tep85SbtDestroyInternalMsgBody struct {
	QueryId uint64
}

type PaymentChannelFinishUncooperativeCloseInternalMsgBody struct{}

type Tep62NftItemGetStaticDataInternalMsgBody struct {
	QueryId uint64
}

type PaymentChannelInitChannelInternalMsgBody struct {
	IsA       bool
	Signature tlb.Bits512
	Tag       uint32
	ChannelId tlb.Uint128
	BalanceA  tlb.Grams
	BalanceB  tlb.Grams
}

type Tep74JettonWalletBurnInternalMsgBody struct {
	QueryId             uint64
	Amount              tlb.VarUInteger16
	ResponseDestination tlb.MsgAddress
	CustomPayload       tlb.Maybe[tlb.Ref[tlb.Any]]
}

type Tep62NftItemTransferInternalMsgBody struct {
	QueryId             uint64
	NewOwner            tlb.MsgAddress
	ResponseDestination tlb.MsgAddress
	CustomPayload       tlb.Maybe[tlb.Ref[tlb.Any]]
	ForwardAmount       tlb.VarUInteger16
	ForwardPayload      tlb.EitherRef[tlb.Any]
}

type PaymentChannelTopUpBalanceInternalMsgBody struct {
	AddA tlb.Grams
	AddB tlb.Grams
}

type Tep66NftRoyaltyGetRoyaltyParamsInternalMsgBody struct {
	QueryId uint64
}

type Tep85SbtRevokeInternalMsgBody struct {
	QueryId uint64
}

type Tep74JettonWalletTransferNotificationInternalMsgBody struct {
	QueryId        uint64
	Amount         tlb.VarUInteger16
	Sender         tlb.MsgAddress
	ForwardPayload tlb.EitherRef[tlb.Any]
}

type Tep62NftItemReportStaticDataInternalMsgBody struct {
	QueryId    uint64
	Index      tlb.Uint256
	Collection tlb.MsgAddress
}

type Tep66NftRoyaltyReportRoyaltyParamsInternalMsgBody struct {
	QueryId     uint64
	Numerator   uint16
	Denominator uint16
	Destination tlb.MsgAddress
}

type PaymentChannelChallengeQuarantinedStateInternalMsgBody struct {
	ChallengedByA bool
	Signature     tlb.Bits512
	Tag           uint32
	ChannelId     tlb.Uint128
	SchA          tlb.Ref[SignedSemiChannel]
	SchB          tlb.Ref[SignedSemiChannel]
}

type PaymentChannelStartUncooperativeCloseInternalMsgBody struct {
	SignedByA bool
	Signature tlb.Bits512
	Tag       uint32
	ChannelId tlb.Uint128
	SchA      tlb.Ref[SignedSemiChannel]
	SchB      tlb.Ref[SignedSemiChannel]
}

type PaymentChannelCooperativeCommitInternalMsgBody struct {
	SigA      tlb.Ref[tlb.Bits512]
	SigB      tlb.Ref[tlb.Bits512]
	Tag       uint32
	ChannelId tlb.Uint128
	SeqnoA    uint64
	SeqnoB    uint64
}

type Tep85SbtRequestOwnerInternalMsgBody struct {
	QueryId        uint64
	Dest           tlb.MsgAddress
	ForwardPayload tlb.Ref[tlb.Any]
	WithContent    bool
}

type ExcessesInternalMsgBody struct {
	QueryId uint64
}

type PaymentChannelChannelClosedInternalMsgBody struct {
	ChannelId tlb.Uint128
}

func MessageDecoder(cell *boc.Cell) (string, any, error) {
	tag, err := cell.ReadUint(32)
	if err != nil {
		return "", nil, err
	}
	switch tag {
	case 0x0:
		var res TextCommentTextCommentInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "TextCommentTextComment", res, err
	case 0x4291097:
		var res PaymentChannelSettleConditionalsInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "PaymentChannelSettleConditionals", res, err
	case 0x4ded148:
		var res Tep85SbtProveOwnershipInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep85SbtProveOwnership", res, err
	case 0x5138d91:
		var res Tep62NftItemOwnershipAssignedInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep62NftItemOwnershipAssigned", res, err
	case 0x524c7ae:
		var res Tep85SbtOwnershipProofInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep85SbtOwnershipProof", res, err
	case 0xdd607e3:
		var res Tep85SbtOwnerInfoInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep85SbtOwnerInfo", res, err
	case 0xdf395b9:
		var res PaymentChannelCooperativeCloseInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "PaymentChannelCooperativeClose", res, err
	case 0xf8a7ea5:
		var res Tep74JettonWalletTransferInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep74JettonWalletTransfer", res, err
	case 0x1f04537a:
		var res Tep85SbtDestroyInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep85SbtDestroy", res, err
	case 0x25432a91:
		var res PaymentChannelFinishUncooperativeCloseInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "PaymentChannelFinishUncooperativeClose", res, err
	case 0x2fcb26a2:
		var res Tep62NftItemGetStaticDataInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep62NftItemGetStaticData", res, err
	case 0x56103bba:
		var res PaymentChannelInitChannelInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "PaymentChannelInitChannel", res, err
	case 0x595f07bc:
		var res Tep74JettonWalletBurnInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep74JettonWalletBurn", res, err
	case 0x5fcc3d14:
		var res Tep62NftItemTransferInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep62NftItemTransfer", res, err
	case 0x67c7d281:
		var res PaymentChannelTopUpBalanceInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "PaymentChannelTopUpBalance", res, err
	case 0x693d3950:
		var res Tep66NftRoyaltyGetRoyaltyParamsInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep66NftRoyaltyGetRoyaltyParams", res, err
	case 0x6f89f5e3:
		var res Tep85SbtRevokeInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep85SbtRevoke", res, err
	case 0x7362d09c:
		var res Tep74JettonWalletTransferNotificationInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep74JettonWalletTransferNotification", res, err
	case 0x8b771735:
		var res Tep62NftItemReportStaticDataInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep62NftItemReportStaticData", res, err
	case 0xa8cb00ad:
		var res Tep66NftRoyaltyReportRoyaltyParamsInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep66NftRoyaltyReportRoyaltyParams", res, err
	case 0xab15bc6a:
		var res PaymentChannelChallengeQuarantinedStateInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "PaymentChannelChallengeQuarantinedState", res, err
	case 0xb942f428:
		var res PaymentChannelStartUncooperativeCloseInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "PaymentChannelStartUncooperativeClose", res, err
	case 0xcf19aff5:
		var res PaymentChannelCooperativeCommitInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "PaymentChannelCooperativeCommit", res, err
	case 0xd0c3bfea:
		var res Tep85SbtRequestOwnerInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Tep85SbtRequestOwner", res, err
	case 0xd53276db:
		var res ExcessesInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "Excesses", res, err
	case 0xdddc88ba:
		var res PaymentChannelChannelClosedInternalMsgBody
		err = tlb.Unmarshal(cell, &res)
		return "PaymentChannelChannelClosed", res, err
	}
	return "", nil, fmt.Errorf("invalid message tag")
}
