package abi

// Code autogenerated. DO NOT EDIT.

import (
	"github.com/tonkeeper/tongo/tlb"
)

var (
	// 0x00000000
	inMsgDecodeFuncTextComment = decodeMsg(tlb.Tag{Val: 0x00000000, Len: 32}, TextCommentMsgOp, TextCommentMsgBody{})
	// 0x04ded148
	inMsgDecodeFuncProveOwnership = decodeMsg(tlb.Tag{Val: 0x04ded148, Len: 32}, ProveOwnershipMsgOp, ProveOwnershipMsgBody{})
	// 0x05138d91
	inMsgDecodeFuncNftOwnershipAssigned = decodeMsg(tlb.Tag{Val: 0x05138d91, Len: 32}, NftOwnershipAssignedMsgOp, NftOwnershipAssignedMsgBody{})
	// 0x0524c7ae
	inMsgDecodeFuncOwnershipProof = decodeMsg(tlb.Tag{Val: 0x0524c7ae, Len: 32}, OwnershipProofMsgOp, OwnershipProofMsgBody{})
	// 0x088eaa32
	inMsgDecodeFuncChallengeQuarantinedChannelState = decodeMsg(tlb.Tag{Val: 0x088eaa32, Len: 32}, ChallengeQuarantinedChannelStateMsgOp, ChallengeQuarantinedChannelStateMsgBody{})
	// 0x0a77535c
	inMsgDecodeFuncTonstakePoolWithdrawal = decodeMsg(tlb.Tag{Val: 0x0a77535c, Len: 32}, TonstakePoolWithdrawalMsgOp, TonstakePoolWithdrawalMsgBody{})
	// 0x0dd607e3
	inMsgDecodeFuncSbtOwnerInfo = decodeMsg(tlb.Tag{Val: 0x0dd607e3, Len: 32}, SbtOwnerInfoMsgOp, SbtOwnerInfoMsgBody{})
	// 0x0e0620c2
	inMsgDecodeFuncInitPaymentChannel = decodeMsg(tlb.Tag{Val: 0x0e0620c2, Len: 32}, InitPaymentChannelMsgOp, InitPaymentChannelMsgBody{})
	// 0x0f8a7ea5
	inMsgDecodeFuncJettonTransfer = decodeMsg(tlb.Tag{Val: 0x0f8a7ea5, Len: 32}, JettonTransferMsgOp, JettonTransferMsgBody{})
	// 0x107c49ef
	inMsgDecodeFuncOfferStorageContract = decodeMsg(tlb.Tag{Val: 0x107c49ef, Len: 32}, OfferStorageContractMsgOp, OfferStorageContractMsgBody{})
	// 0x132f9a45
	inMsgDecodeFuncTonstakeNftInit = decodeMsg(tlb.Tag{Val: 0x132f9a45, Len: 32}, TonstakeNftInitMsgOp, TonstakeNftInitMsgBody{})
	// 0x139a1b4e
	inMsgDecodeFuncTonstakeControllerPoolHalt = decodeMsg(tlb.Tag{Val: 0x139a1b4e, Len: 32}, TonstakeControllerPoolHaltMsgOp, TonstakeControllerPoolHaltMsgBody{})
	// 0x1596920c
	inMsgDecodeFuncWhalesNominatorsForceKick = decodeMsg(tlb.Tag{Val: 0x1596920c, Len: 32}, WhalesNominatorsForceKickMsgOp, WhalesNominatorsForceKickMsgBody{})
	// 0x1690c604
	inMsgDecodeFuncTonstakeControllerCredit = decodeMsg(tlb.Tag{Val: 0x1690c604, Len: 32}, TonstakeControllerCreditMsgOp, TonstakeControllerCreditMsgBody{})
	// 0x178d4519
	inMsgDecodeFuncJettonInternalTransfer = decodeMsg(tlb.Tag{Val: 0x178d4519, Len: 32}, JettonInternalTransferMsgOp, JettonInternalTransferMsgBody{})
	// 0x1d1715bf
	inMsgDecodeFuncWhalesNominatorsWithdrawUnownedResponse = decodeMsg(tlb.Tag{Val: 0x1d1715bf, Len: 32}, WhalesNominatorsWithdrawUnownedResponseMsgOp, WhalesNominatorsWithdrawUnownedResponseMsgBody{})
	// 0x1f04537a
	inMsgDecodeFuncSbtDestroy = decodeMsg(tlb.Tag{Val: 0x1f04537a, Len: 32}, SbtDestroyMsgOp, SbtDestroyMsgBody{})
	// 0x1f151acf
	inMsgDecodeFuncStartUncooperativeChannelClose = decodeMsg(tlb.Tag{Val: 0x1f151acf, Len: 32}, StartUncooperativeChannelCloseMsgOp, StartUncooperativeChannelCloseMsgBody{})
	// 0x2167da4b
	inMsgDecodeFuncEncryptedTextComment = decodeMsg(tlb.Tag{Val: 0x2167da4b, Len: 32}, EncryptedTextCommentMsgOp, EncryptedTextCommentMsgBody{})
	// 0x23d421e1
	inMsgDecodeFuncWhalesNominatorsStakeWithdrawCompleted = decodeMsg(tlb.Tag{Val: 0x23d421e1, Len: 32}, WhalesNominatorsStakeWithdrawCompletedMsgOp, WhalesNominatorsStakeWithdrawCompletedMsgBody{})
	// 0x251d6a98
	inMsgDecodeFuncWhalesNominatorsWithdrawUnowned = decodeMsg(tlb.Tag{Val: 0x251d6a98, Len: 32}, WhalesNominatorsWithdrawUnownedMsgOp, WhalesNominatorsWithdrawUnownedMsgBody{})
	// 0x25432a91
	inMsgDecodeFuncFinishUncooperativeChannelClose = decodeMsg(tlb.Tag{Val: 0x25432a91, Len: 32}, FinishUncooperativeChannelCloseMsgOp, FinishUncooperativeChannelCloseMsgBody{})
	// 0x25938561
	inMsgDecodeFuncStonfiSwap = decodeMsg(tlb.Tag{Val: 0x25938561, Len: 32}, StonfiSwapMsgOp, StonfiSwapMsgBody{})
	// 0x270695fb
	inMsgDecodeFuncTonstakeControllerPoolSendMessage = decodeMsg(tlb.Tag{Val: 0x270695fb, Len: 32}, TonstakeControllerPoolSendMessageMsgOp, TonstakeControllerPoolSendMessageMsgBody{})
	// 0x299a3e15
	inMsgDecodeFuncTeleitemDeploy = decodeMsg(tlb.Tag{Val: 0x299a3e15, Len: 32}, TeleitemDeployMsgOp, TeleitemDeployMsgBody{})
	// 0x2aaa96a0
	inMsgDecodeFuncTonstakePoolSetGovernanceFee = decodeMsg(tlb.Tag{Val: 0x2aaa96a0, Len: 32}, TonstakePoolSetGovernanceFeeMsgOp, TonstakePoolSetGovernanceFeeMsgBody{})
	// 0x2fcb26a2
	inMsgDecodeFuncGetStaticData = decodeMsg(tlb.Tag{Val: 0x2fcb26a2, Len: 32}, GetStaticDataMsgOp, GetStaticDataMsgBody{})
	// 0x30026327
	inMsgDecodeFuncTonstakeControllerValidatorWithdrawal = decodeMsg(tlb.Tag{Val: 0x30026327, Len: 32}, TonstakeControllerValidatorWithdrawalMsgOp, TonstakeControllerValidatorWithdrawalMsgBody{})
	// 0x319b0cdc
	inMsgDecodeFuncTonstakePoolWithdraw = decodeMsg(tlb.Tag{Val: 0x319b0cdc, Len: 32}, TonstakePoolWithdrawMsgOp, TonstakePoolWithdrawMsgBody{})
	// 0x370fec51
	inMsgDecodeFuncAuctionFillUp = decodeMsg(tlb.Tag{Val: 0x370fec51, Len: 32}, AuctionFillUpMsgOp, AuctionFillUpMsgBody{})
	// 0x371638ae
	inMsgDecodeFuncTeleitemCancelAuction = decodeMsg(tlb.Tag{Val: 0x371638ae, Len: 32}, TeleitemCancelAuctionMsgOp, TeleitemCancelAuctionMsgBody{})
	// 0x419d5d4d
	inMsgDecodeFuncProofStorage = decodeMsg(tlb.Tag{Val: 0x419d5d4d, Len: 32}, ProofStorageMsgOp, ProofStorageMsgBody{})
	// 0x44beae41
	inMsgDecodeFuncProcessGovernanceDecision = decodeMsg(tlb.Tag{Val: 0x44beae41, Len: 32}, ProcessGovernanceDecisionMsgOp, ProcessGovernanceDecisionMsgBody{})
	// 0x4637289a
	inMsgDecodeFuncTelemintDeploy = decodeMsg(tlb.Tag{Val: 0x4637289a, Len: 32}, TelemintDeployMsgOp, TelemintDeployMsgBody{})
	// 0x4637289b
	inMsgDecodeFuncTelemintDeployV2 = decodeMsg(tlb.Tag{Val: 0x4637289b, Len: 32}, TelemintDeployV2MsgOp, TelemintDeployV2MsgBody{})
	// 0x46ed2e94
	inMsgDecodeFuncStorageWithdraw = decodeMsg(tlb.Tag{Val: 0x46ed2e94, Len: 32}, StorageWithdrawMsgOp, StorageWithdrawMsgBody{})
	// 0x474f86cf
	inMsgDecodeFuncDedustPayout = decodeMsg(tlb.Tag{Val: 0x474f86cf, Len: 32}, DedustPayoutMsgOp, DedustPayoutMsgBody{})
	// 0x47657424
	inMsgDecodeFuncElectorRecoverStakeRequest = decodeMsg(tlb.Tag{Val: 0x47657424, Len: 32}, ElectorRecoverStakeRequestMsgOp, ElectorRecoverStakeRequestMsgBody{})
	// 0x47d54391
	inMsgDecodeFuncTonstakePoolDeposit = decodeMsg(tlb.Tag{Val: 0x47d54391, Len: 32}, TonstakePoolDepositMsgOp, TonstakePoolDepositMsgBody{})
	// 0x487a8e81
	inMsgDecodeFuncTeleitemStartAuction = decodeMsg(tlb.Tag{Val: 0x487a8e81, Len: 32}, TeleitemStartAuctionMsgOp, TeleitemStartAuctionMsgBody{})
	// 0x4bc7c2df
	inMsgDecodeFuncTonstakePoolTouch = decodeMsg(tlb.Tag{Val: 0x4bc7c2df, Len: 32}, TonstakePoolTouchMsgOp, TonstakePoolTouchMsgBody{})
	// 0x4e73744b
	inMsgDecodeFuncElectorNewStake = decodeMsg(tlb.Tag{Val: 0x4e73744b, Len: 32}, ElectorNewStakeMsgOp, ElectorNewStakeMsgBody{})
	//DeleteDnsRecord, ChangeDnsRecord,
	inMsgDecodeFunc0x4eb1f0f9 = decodeMultipleMsgs(tlb.Tag{Val: 0x4eb1f0f9, Len: 32}, []MsgOpName{DeleteDnsRecordMsgOp, ChangeDnsRecordMsgOp}, []any{DeleteDnsRecordMsgBody{}, ChangeDnsRecordMsgBody{}})
	// 0x4ed14b65
	inMsgDecodeFuncDnsBalanceRelease = decodeMsg(tlb.Tag{Val: 0x4ed14b65, Len: 32}, DnsBalanceReleaseMsgOp, DnsBalanceReleaseMsgBody{})
	// 0x53f34cd6
	inMsgDecodeFuncUpdatePubkey = decodeMsg(tlb.Tag{Val: 0x53f34cd6, Len: 32}, UpdatePubkeyMsgOp, UpdatePubkeyMsgBody{})
	// 0x54cbf19b
	inMsgDecodeFuncUpdateStorageParams = decodeMsg(tlb.Tag{Val: 0x54cbf19b, Len: 32}, UpdateStorageParamsMsgOp, UpdateStorageParamsMsgBody{})
	// 0x54d37487
	inMsgDecodeFuncTonstakeImanagerOperationFee = decodeMsg(tlb.Tag{Val: 0x54d37487, Len: 32}, TonstakeImanagerOperationFeeMsgOp, TonstakeImanagerOperationFeeMsgBody{})
	// 0x5577587e
	inMsgDecodeFuncChannelCooperativeClose = decodeMsg(tlb.Tag{Val: 0x5577587e, Len: 32}, ChannelCooperativeCloseMsgOp, ChannelCooperativeCloseMsgBody{})
	// 0x557cea20
	inMsgDecodeFuncOutbidNotification = decodeMsg(tlb.Tag{Val: 0x557cea20, Len: 32}, OutbidNotificationMsgOp, OutbidNotificationMsgBody{})
	// 0x55c26cd5
	inMsgDecodeFuncTonstakeControllerReturnAvailableFunds = decodeMsg(tlb.Tag{Val: 0x55c26cd5, Len: 32}, TonstakeControllerReturnAvailableFundsMsgOp, TonstakeControllerReturnAvailableFundsMsgBody{})
	// 0x595f07bc
	inMsgDecodeFuncJettonBurn = decodeMsg(tlb.Tag{Val: 0x595f07bc, Len: 32}, JettonBurnMsgOp, JettonBurnMsgBody{})
	// 0x5e517f36
	inMsgDecodeFuncTonstakePoolSetRoles = decodeMsg(tlb.Tag{Val: 0x5e517f36, Len: 32}, TonstakePoolSetRolesMsgOp, TonstakePoolSetRolesMsgBody{})
	// 0x5fcc3d14
	inMsgDecodeFuncNftTransfer = decodeMsg(tlb.Tag{Val: 0x5fcc3d14, Len: 32}, NftTransferMsgOp, NftTransferMsgBody{})
	// 0x600c00fd
	inMsgDecodeFuncTegroSwapTon = decodeMsg(tlb.Tag{Val: 0x600c00fd, Len: 32}, TegroSwapTonMsgOp, TegroSwapTonMsgBody{})
	// 0x61ee542d
	inMsgDecodeFuncDedustSwapExternal = decodeMsg(tlb.Tag{Val: 0x61ee542d, Len: 32}, DedustSwapExternalMsgOp, DedustSwapExternalMsgBody{})
	// 0x6335b11a
	inMsgDecodeFuncTonstakeControllerSendRequestLoan = decodeMsg(tlb.Tag{Val: 0x6335b11a, Len: 32}, TonstakeControllerSendRequestLoanMsgOp, TonstakeControllerSendRequestLoanMsgBody{})
	// 0x64737472
	inMsgDecodeFuncWalletPluginDestruct = decodeMsg(tlb.Tag{Val: 0x64737472, Len: 32}, WalletPluginDestructMsgOp, WalletPluginDestructMsgBody{})
	// 0x66f6f069
	inMsgDecodeFuncSettleChannelConditionals = decodeMsg(tlb.Tag{Val: 0x66f6f069, Len: 32}, SettleChannelConditionalsMsgOp, SettleChannelConditionalsMsgBody{})
	// 0x67c7d281
	inMsgDecodeFuncTopUpChannelBalance = decodeMsg(tlb.Tag{Val: 0x67c7d281, Len: 32}, TopUpChannelBalanceMsgOp, TopUpChannelBalanceMsgBody{})
	// 0x693d3950
	inMsgDecodeFuncGetRoyaltyParams = decodeMsg(tlb.Tag{Val: 0x693d3950, Len: 32}, GetRoyaltyParamsMsgOp, GetRoyaltyParamsMsgBody{})
	// 0x6f89f5e3
	inMsgDecodeFuncSbtRevoke = decodeMsg(tlb.Tag{Val: 0x6f89f5e3, Len: 32}, SbtRevokeMsgOp, SbtRevokeMsgBody{})
	// 0x706c7567
	inMsgDecodeFuncPaymentRequest = decodeMsg(tlb.Tag{Val: 0x706c7567, Len: 32}, PaymentRequestMsgOp, PaymentRequestMsgBody{})
	// 0x7247e7a5
	inMsgDecodeFuncTonstakeControllerPoolUnhalt = decodeMsg(tlb.Tag{Val: 0x7247e7a5, Len: 32}, TonstakeControllerPoolUnhaltMsgOp, TonstakeControllerPoolUnhaltMsgBody{})
	// 0x72aca8aa
	inMsgDecodeFuncDedustSwapPeer = decodeMsg(tlb.Tag{Val: 0x72aca8aa, Len: 32}, DedustSwapPeerMsgOp, DedustSwapPeerMsgBody{})
	// 0x7362d09c
	inMsgDecodeFuncJettonNotify = decodeMsg(tlb.Tag{Val: 0x7362d09c, Len: 32}, JettonNotifyMsgOp, JettonNotifyMsgBody{})
	// 0x73756273
	inMsgDecodeFuncSubscriptionPayment = decodeMsg(tlb.Tag{Val: 0x73756273, Len: 32}, SubscriptionPaymentMsgOp, SubscriptionPaymentMsgBody{})
	// 0x74bb3427
	inMsgDecodeFuncWhalesNominatorsStakeWithdrawDelayed = decodeMsg(tlb.Tag{Val: 0x74bb3427, Len: 32}, WhalesNominatorsStakeWithdrawDelayedMsgOp, WhalesNominatorsStakeWithdrawDelayedMsgBody{})
	// 0x77a33521
	inMsgDecodeFuncMegatonWtonMint = decodeMsg(tlb.Tag{Val: 0x77a33521, Len: 32}, MegatonWtonMintMsgOp, MegatonWtonMintMsgBody{})
	// 0x79a126ef
	inMsgDecodeFuncChannelCooperativeCommit = decodeMsg(tlb.Tag{Val: 0x79a126ef, Len: 32}, ChannelCooperativeCommitMsgOp, ChannelCooperativeCommitMsgBody{})
	// 0x79e7c016
	inMsgDecodeFuncTonstakeControllerPoolSetSudoer = decodeMsg(tlb.Tag{Val: 0x79e7c016, Len: 32}, TonstakeControllerPoolSetSudoerMsgOp, TonstakeControllerPoolSetSudoerMsgBody{})
	// 0x79f937ea
	inMsgDecodeFuncCloseStorageContract = decodeMsg(tlb.Tag{Val: 0x79f937ea, Len: 32}, CloseStorageContractMsgOp, CloseStorageContractMsgBody{})
	// 0x7a361688
	inMsgDecodeFuncAcceptStorageContract = decodeMsg(tlb.Tag{Val: 0x7a361688, Len: 32}, AcceptStorageContractMsgOp, AcceptStorageContractMsgBody{})
	// 0x7b4b42e6
	inMsgDecodeFuncTonstakeControllerApprove = decodeMsg(tlb.Tag{Val: 0x7b4b42e6, Len: 32}, TonstakeControllerApproveMsgOp, TonstakeControllerApproveMsgBody{})
	// 0x7bcd1fef
	inMsgDecodeFuncWhalesNominatorsDeposit = decodeMsg(tlb.Tag{Val: 0x7bcd1fef, Len: 32}, WhalesNominatorsDepositMsgOp, WhalesNominatorsDepositMsgBody{})
	// 0x7bdd97de
	inMsgDecodeFuncJettonBurnNotification = decodeMsg(tlb.Tag{Val: 0x7bdd97de, Len: 32}, JettonBurnNotificationMsgOp, JettonBurnNotificationMsgBody{})
	// 0x8b771735
	inMsgDecodeFuncReportStaticData = decodeMsg(tlb.Tag{Val: 0x8b771735, Len: 32}, ReportStaticDataMsgOp, ReportStaticDataMsgBody{})
	// 0x8efed779
	inMsgDecodeFuncTonstakeControllerWithdrawValidator = decodeMsg(tlb.Tag{Val: 0x8efed779, Len: 32}, TonstakeControllerWithdrawValidatorMsgOp, TonstakeControllerWithdrawValidatorMsgBody{})
	// 0x96e7f528
	inMsgDecodeFuncTonstakeControllerPoolUpgrade = decodeMsg(tlb.Tag{Val: 0x96e7f528, Len: 32}, TonstakeControllerPoolUpgradeMsgOp, TonstakeControllerPoolUpgradeMsgBody{})
	// 0x9971881c
	inMsgDecodeFuncTonstakePoolPrepareGovernanceMigration = decodeMsg(tlb.Tag{Val: 0x9971881c, Len: 32}, TonstakePoolPrepareGovernanceMigrationMsgOp, TonstakePoolPrepareGovernanceMigrationMsgBody{})
	// 0x99a811fb
	inMsgDecodeFuncWhalesNominatorsAcceptStake = decodeMsg(tlb.Tag{Val: 0x99a811fb, Len: 32}, WhalesNominatorsAcceptStakeMsgOp, WhalesNominatorsAcceptStakeMsgBody{})
	// 0x9bf5561c
	inMsgDecodeFuncTonstakePoolSetDepositSettings = decodeMsg(tlb.Tag{Val: 0x9bf5561c, Len: 32}, TonstakePoolSetDepositSettingsMsgOp, TonstakePoolSetDepositSettingsMsgBody{})
	// 0xa19fd934
	inMsgDecodeFuncWhalesNominatorsAcceptWithdraws = decodeMsg(tlb.Tag{Val: 0xa19fd934, Len: 32}, WhalesNominatorsAcceptWithdrawsMsgOp, WhalesNominatorsAcceptWithdrawsMsgBody{})
	// 0xa2065f2c
	inMsgDecodeFuncWhalesNominatorsSendStake = decodeMsg(tlb.Tag{Val: 0xa2065f2c, Len: 32}, WhalesNominatorsSendStakeMsgOp, WhalesNominatorsSendStakeMsgBody{})
	// 0xa37a0983
	inMsgDecodeFuncTeleitemOk = decodeMsg(tlb.Tag{Val: 0xa37a0983, Len: 32}, TeleitemOkMsgOp, TeleitemOkMsgBody{})
	// 0xa43227e1
	inMsgDecodeFuncTeleitemReturnBid = decodeMsg(tlb.Tag{Val: 0xa43227e1, Len: 32}, TeleitemReturnBidMsgOp, TeleitemReturnBidMsgBody{})
	// 0xa8cb00ad
	inMsgDecodeFuncReportRoyaltyParams = decodeMsg(tlb.Tag{Val: 0xa8cb00ad, Len: 32}, ReportRoyaltyParamsMsgOp, ReportRoyaltyParamsMsgBody{})
	// 0xa91baf56
	inMsgDecodeFuncStorageRewardWithdrawal = decodeMsg(tlb.Tag{Val: 0xa91baf56, Len: 32}, StorageRewardWithdrawalMsgOp, StorageRewardWithdrawalMsgBody{})
	// 0xad4eb6f5
	inMsgDecodeFuncDedustPayoutFromPool = decodeMsg(tlb.Tag{Val: 0xad4eb6f5, Len: 32}, DedustPayoutFromPoolMsgOp, DedustPayoutFromPoolMsgBody{})
	// 0xb1ebae06
	inMsgDecodeFuncTonstakeImanagerRequestNotification = decodeMsg(tlb.Tag{Val: 0xb1ebae06, Len: 32}, TonstakeImanagerRequestNotificationMsgOp, TonstakeImanagerRequestNotificationMsgBody{})
	// 0xb27edcad
	inMsgDecodeFuncTonstakePoolDeployController = decodeMsg(tlb.Tag{Val: 0xb27edcad, Len: 32}, TonstakePoolDeployControllerMsgOp, TonstakePoolDeployControllerMsgBody{})
	// 0xb56b9598
	inMsgDecodeFuncDedustDepositLiquidityAll = decodeMsg(tlb.Tag{Val: 0xb56b9598, Len: 32}, DedustDepositLiquidityAllMsgOp, DedustDepositLiquidityAllMsgBody{})
	// 0xb6236d63
	inMsgDecodeFuncStorageContractTerminated = decodeMsg(tlb.Tag{Val: 0xb6236d63, Len: 32}, StorageContractTerminatedMsgOp, StorageContractTerminatedMsgBody{})
	// 0xc1344900
	inMsgDecodeFuncTonstakeImanagerStats = decodeMsg(tlb.Tag{Val: 0xc1344900, Len: 32}, TonstakeImanagerStatsMsgOp, TonstakeImanagerStatsMsgBody{})
	// 0xc9f04485
	inMsgDecodeFuncTonstakeImanagerSetInterest = decodeMsg(tlb.Tag{Val: 0xc9f04485, Len: 32}, TonstakeImanagerSetInterestMsgOp, TonstakeImanagerSetInterestMsgBody{})
	// 0xd0c3bfea
	inMsgDecodeFuncSbtRequestOwner = decodeMsg(tlb.Tag{Val: 0xd0c3bfea, Len: 32}, SbtRequestOwnerMsgOp, SbtRequestOwnerMsgBody{})
	// 0xd372158c
	inMsgDecodeFuncTonstakeControllerTopUp = decodeMsg(tlb.Tag{Val: 0xd372158c, Len: 32}, TonstakeControllerTopUpMsgOp, TonstakeControllerTopUpMsgBody{})
	// 0xd4caedcd
	inMsgDecodeFuncStorageContractConfirmed = decodeMsg(tlb.Tag{Val: 0xd4caedcd, Len: 32}, StorageContractConfirmedMsgOp, StorageContractConfirmedMsgBody{})
	// 0xd53276db
	inMsgDecodeFuncExcess = decodeMsg(tlb.Tag{Val: 0xd53276db, Len: 32}, ExcessMsgOp, ExcessMsgBody{})
	// 0xda803efd
	inMsgDecodeFuncWhalesNominatorsWithdraw = decodeMsg(tlb.Tag{Val: 0xda803efd, Len: 32}, WhalesNominatorsWithdrawMsgOp, WhalesNominatorsWithdrawMsgBody{})
	// 0xdb3b8abd
	inMsgDecodeFuncTonstakeNftPayout = decodeMsg(tlb.Tag{Val: 0xdb3b8abd, Len: 32}, TonstakeNftPayoutMsgOp, TonstakeNftPayoutMsgBody{})
	// 0xdddc88ba
	inMsgDecodeFuncChannelClosed = decodeMsg(tlb.Tag{Val: 0xdddc88ba, Len: 32}, ChannelClosedMsgOp, ChannelClosedMsgBody{})
	// 0xdfdca27b
	inMsgDecodeFuncTonstakePoolLoanRepayment = decodeMsg(tlb.Tag{Val: 0xdfdca27b, Len: 32}, TonstakePoolLoanRepaymentMsgOp, TonstakePoolLoanRepaymentMsgBody{})
	// 0xe4737472
	inMsgDecodeFuncWalletPluginDestructResponse = decodeMsg(tlb.Tag{Val: 0xe4737472, Len: 32}, WalletPluginDestructResponseMsgOp, WalletPluginDestructResponseMsgBody{})
	// 0xe4748df1
	inMsgDecodeFuncDeployStorageContract = decodeMsg(tlb.Tag{Val: 0xe4748df1, Len: 32}, DeployStorageContractMsgOp, DeployStorageContractMsgBody{})
	// 0xe642c965
	inMsgDecodeFuncTonstakePoolRequestLoan = decodeMsg(tlb.Tag{Val: 0xe642c965, Len: 32}, TonstakePoolRequestLoanMsgOp, TonstakePoolRequestLoanMsgBody{})
	// 0xe8a0abfe
	inMsgDecodeFuncTonstakeControllerDisapprove = decodeMsg(tlb.Tag{Val: 0xe8a0abfe, Len: 32}, TonstakeControllerDisapproveMsgOp, TonstakeControllerDisapproveMsgBody{})
	// 0xea06185d
	inMsgDecodeFuncDedustSwap = decodeMsg(tlb.Tag{Val: 0xea06185d, Len: 32}, DedustSwapMsgOp, DedustSwapMsgBody{})
	// 0xeb373a05
	inMsgDecodeFuncTonstakeControllerRecoverStake = decodeMsg(tlb.Tag{Val: 0xeb373a05, Len: 32}, TonstakeControllerRecoverStakeMsgOp, TonstakeControllerRecoverStakeMsgBody{})
	// 0xed58b0b2
	inMsgDecodeFuncTonstakeNftBurnNotification = decodeMsg(tlb.Tag{Val: 0xed58b0b2, Len: 32}, TonstakeNftBurnNotificationMsgOp, TonstakeNftBurnNotificationMsgBody{})
	// 0xed7378a6
	inMsgDecodeFuncTonstakeControllerReturnUnusedLoan = decodeMsg(tlb.Tag{Val: 0xed7378a6, Len: 32}, TonstakeControllerReturnUnusedLoanMsgOp, TonstakeControllerReturnUnusedLoanMsgBody{})
	// 0xf06c7567
	inMsgDecodeFuncPaymentRequestResponse = decodeMsg(tlb.Tag{Val: 0xf06c7567, Len: 32}, PaymentRequestResponseMsgOp, PaymentRequestResponseMsgBody{})
	// 0xf0fd2250
	inMsgDecodeFuncTonstakeControllerUpdateValidatorHash = decodeMsg(tlb.Tag{Val: 0xf0fd2250, Len: 32}, TonstakeControllerUpdateValidatorHashMsgOp, TonstakeControllerUpdateValidatorHashMsgBody{})
	// 0xf127fe4e
	inMsgDecodeFuncTonstakeNftBurn = decodeMsg(tlb.Tag{Val: 0xf127fe4e, Len: 32}, TonstakeNftBurnMsgOp, TonstakeNftBurnMsgBody{})
	// 0xf374484c
	inMsgDecodeFuncElectorNewStakeConfirmation = decodeMsg(tlb.Tag{Val: 0xf374484c, Len: 32}, ElectorNewStakeConfirmationMsgOp, ElectorNewStakeConfirmationMsgBody{})
	// 0xf93bb43f
	inMsgDecodeFuncStonfiPaymentRequest = decodeMsg(tlb.Tag{Val: 0xf93bb43f, Len: 32}, StonfiPaymentRequestMsgOp, StonfiPaymentRequestMsgBody{})
	// 0xf96f7324
	inMsgDecodeFuncElectorRecoverStakeResponse = decodeMsg(tlb.Tag{Val: 0xf96f7324, Len: 32}, ElectorRecoverStakeResponseMsgOp, ElectorRecoverStakeResponseMsgBody{})
	// 0xffffffff
	inMsgDecodeFuncBounce = decodeMsg(tlb.Tag{Val: 0xffffffff, Len: 32}, BounceMsgOp, BounceMsgBody{})
)

var opcodedInternalMessageDecodeFunctions = map[uint32]msgDecoderFunc{
	// 0x00000000
	TextCommentMsgOpCode: inMsgDecodeFuncTextComment,
	// 0x04ded148
	ProveOwnershipMsgOpCode: inMsgDecodeFuncProveOwnership,
	// 0x05138d91
	NftOwnershipAssignedMsgOpCode: inMsgDecodeFuncNftOwnershipAssigned,
	// 0x0524c7ae
	OwnershipProofMsgOpCode: inMsgDecodeFuncOwnershipProof,
	// 0x088eaa32
	ChallengeQuarantinedChannelStateMsgOpCode: inMsgDecodeFuncChallengeQuarantinedChannelState,
	// 0x0a77535c
	TonstakePoolWithdrawalMsgOpCode: inMsgDecodeFuncTonstakePoolWithdrawal,
	// 0x0dd607e3
	SbtOwnerInfoMsgOpCode: inMsgDecodeFuncSbtOwnerInfo,
	// 0x0e0620c2
	InitPaymentChannelMsgOpCode: inMsgDecodeFuncInitPaymentChannel,
	// 0x0f8a7ea5
	JettonTransferMsgOpCode: inMsgDecodeFuncJettonTransfer,
	// 0x107c49ef
	OfferStorageContractMsgOpCode: inMsgDecodeFuncOfferStorageContract,
	// 0x132f9a45
	TonstakeNftInitMsgOpCode: inMsgDecodeFuncTonstakeNftInit,
	// 0x139a1b4e
	TonstakeControllerPoolHaltMsgOpCode: inMsgDecodeFuncTonstakeControllerPoolHalt,
	// 0x1596920c
	WhalesNominatorsForceKickMsgOpCode: inMsgDecodeFuncWhalesNominatorsForceKick,
	// 0x1690c604
	TonstakeControllerCreditMsgOpCode: inMsgDecodeFuncTonstakeControllerCredit,
	// 0x178d4519
	JettonInternalTransferMsgOpCode: inMsgDecodeFuncJettonInternalTransfer,
	// 0x1d1715bf
	WhalesNominatorsWithdrawUnownedResponseMsgOpCode: inMsgDecodeFuncWhalesNominatorsWithdrawUnownedResponse,
	// 0x1f04537a
	SbtDestroyMsgOpCode: inMsgDecodeFuncSbtDestroy,
	// 0x1f151acf
	StartUncooperativeChannelCloseMsgOpCode: inMsgDecodeFuncStartUncooperativeChannelClose,
	// 0x2167da4b
	EncryptedTextCommentMsgOpCode: inMsgDecodeFuncEncryptedTextComment,
	// 0x23d421e1
	WhalesNominatorsStakeWithdrawCompletedMsgOpCode: inMsgDecodeFuncWhalesNominatorsStakeWithdrawCompleted,
	// 0x251d6a98
	WhalesNominatorsWithdrawUnownedMsgOpCode: inMsgDecodeFuncWhalesNominatorsWithdrawUnowned,
	// 0x25432a91
	FinishUncooperativeChannelCloseMsgOpCode: inMsgDecodeFuncFinishUncooperativeChannelClose,
	// 0x25938561
	StonfiSwapMsgOpCode: inMsgDecodeFuncStonfiSwap,
	// 0x270695fb
	TonstakeControllerPoolSendMessageMsgOpCode: inMsgDecodeFuncTonstakeControllerPoolSendMessage,
	// 0x299a3e15
	TeleitemDeployMsgOpCode: inMsgDecodeFuncTeleitemDeploy,
	// 0x2aaa96a0
	TonstakePoolSetGovernanceFeeMsgOpCode: inMsgDecodeFuncTonstakePoolSetGovernanceFee,
	// 0x2fcb26a2
	GetStaticDataMsgOpCode: inMsgDecodeFuncGetStaticData,
	// 0x30026327
	TonstakeControllerValidatorWithdrawalMsgOpCode: inMsgDecodeFuncTonstakeControllerValidatorWithdrawal,
	// 0x319b0cdc
	TonstakePoolWithdrawMsgOpCode: inMsgDecodeFuncTonstakePoolWithdraw,
	// 0x370fec51
	AuctionFillUpMsgOpCode: inMsgDecodeFuncAuctionFillUp,
	// 0x371638ae
	TeleitemCancelAuctionMsgOpCode: inMsgDecodeFuncTeleitemCancelAuction,
	// 0x419d5d4d
	ProofStorageMsgOpCode: inMsgDecodeFuncProofStorage,
	// 0x44beae41
	ProcessGovernanceDecisionMsgOpCode: inMsgDecodeFuncProcessGovernanceDecision,
	// 0x4637289a
	TelemintDeployMsgOpCode: inMsgDecodeFuncTelemintDeploy,
	// 0x4637289b
	TelemintDeployV2MsgOpCode: inMsgDecodeFuncTelemintDeployV2,
	// 0x46ed2e94
	StorageWithdrawMsgOpCode: inMsgDecodeFuncStorageWithdraw,
	// 0x474f86cf
	DedustPayoutMsgOpCode: inMsgDecodeFuncDedustPayout,
	// 0x47657424
	ElectorRecoverStakeRequestMsgOpCode: inMsgDecodeFuncElectorRecoverStakeRequest,
	// 0x47d54391
	TonstakePoolDepositMsgOpCode: inMsgDecodeFuncTonstakePoolDeposit,
	// 0x487a8e81
	TeleitemStartAuctionMsgOpCode: inMsgDecodeFuncTeleitemStartAuction,
	// 0x4bc7c2df
	TonstakePoolTouchMsgOpCode: inMsgDecodeFuncTonstakePoolTouch,
	// 0x4e73744b
	ElectorNewStakeMsgOpCode: inMsgDecodeFuncElectorNewStake,
	//DeleteDnsRecord, ChangeDnsRecord,
	0x4eb1f0f9: inMsgDecodeFunc0x4eb1f0f9,
	// 0x4ed14b65
	DnsBalanceReleaseMsgOpCode: inMsgDecodeFuncDnsBalanceRelease,
	// 0x53f34cd6
	UpdatePubkeyMsgOpCode: inMsgDecodeFuncUpdatePubkey,
	// 0x54cbf19b
	UpdateStorageParamsMsgOpCode: inMsgDecodeFuncUpdateStorageParams,
	// 0x54d37487
	TonstakeImanagerOperationFeeMsgOpCode: inMsgDecodeFuncTonstakeImanagerOperationFee,
	// 0x5577587e
	ChannelCooperativeCloseMsgOpCode: inMsgDecodeFuncChannelCooperativeClose,
	// 0x557cea20
	OutbidNotificationMsgOpCode: inMsgDecodeFuncOutbidNotification,
	// 0x55c26cd5
	TonstakeControllerReturnAvailableFundsMsgOpCode: inMsgDecodeFuncTonstakeControllerReturnAvailableFunds,
	// 0x595f07bc
	JettonBurnMsgOpCode: inMsgDecodeFuncJettonBurn,
	// 0x5e517f36
	TonstakePoolSetRolesMsgOpCode: inMsgDecodeFuncTonstakePoolSetRoles,
	// 0x5fcc3d14
	NftTransferMsgOpCode: inMsgDecodeFuncNftTransfer,
	// 0x600c00fd
	TegroSwapTonMsgOpCode: inMsgDecodeFuncTegroSwapTon,
	// 0x61ee542d
	DedustSwapExternalMsgOpCode: inMsgDecodeFuncDedustSwapExternal,
	// 0x6335b11a
	TonstakeControllerSendRequestLoanMsgOpCode: inMsgDecodeFuncTonstakeControllerSendRequestLoan,
	// 0x64737472
	WalletPluginDestructMsgOpCode: inMsgDecodeFuncWalletPluginDestruct,
	// 0x66f6f069
	SettleChannelConditionalsMsgOpCode: inMsgDecodeFuncSettleChannelConditionals,
	// 0x67c7d281
	TopUpChannelBalanceMsgOpCode: inMsgDecodeFuncTopUpChannelBalance,
	// 0x693d3950
	GetRoyaltyParamsMsgOpCode: inMsgDecodeFuncGetRoyaltyParams,
	// 0x6f89f5e3
	SbtRevokeMsgOpCode: inMsgDecodeFuncSbtRevoke,
	// 0x706c7567
	PaymentRequestMsgOpCode: inMsgDecodeFuncPaymentRequest,
	// 0x7247e7a5
	TonstakeControllerPoolUnhaltMsgOpCode: inMsgDecodeFuncTonstakeControllerPoolUnhalt,
	// 0x72aca8aa
	DedustSwapPeerMsgOpCode: inMsgDecodeFuncDedustSwapPeer,
	// 0x7362d09c
	JettonNotifyMsgOpCode: inMsgDecodeFuncJettonNotify,
	// 0x73756273
	SubscriptionPaymentMsgOpCode: inMsgDecodeFuncSubscriptionPayment,
	// 0x74bb3427
	WhalesNominatorsStakeWithdrawDelayedMsgOpCode: inMsgDecodeFuncWhalesNominatorsStakeWithdrawDelayed,
	// 0x77a33521
	MegatonWtonMintMsgOpCode: inMsgDecodeFuncMegatonWtonMint,
	// 0x79a126ef
	ChannelCooperativeCommitMsgOpCode: inMsgDecodeFuncChannelCooperativeCommit,
	// 0x79e7c016
	TonstakeControllerPoolSetSudoerMsgOpCode: inMsgDecodeFuncTonstakeControllerPoolSetSudoer,
	// 0x79f937ea
	CloseStorageContractMsgOpCode: inMsgDecodeFuncCloseStorageContract,
	// 0x7a361688
	AcceptStorageContractMsgOpCode: inMsgDecodeFuncAcceptStorageContract,
	// 0x7b4b42e6
	TonstakeControllerApproveMsgOpCode: inMsgDecodeFuncTonstakeControllerApprove,
	// 0x7bcd1fef
	WhalesNominatorsDepositMsgOpCode: inMsgDecodeFuncWhalesNominatorsDeposit,
	// 0x7bdd97de
	JettonBurnNotificationMsgOpCode: inMsgDecodeFuncJettonBurnNotification,
	// 0x8b771735
	ReportStaticDataMsgOpCode: inMsgDecodeFuncReportStaticData,
	// 0x8efed779
	TonstakeControllerWithdrawValidatorMsgOpCode: inMsgDecodeFuncTonstakeControllerWithdrawValidator,
	// 0x96e7f528
	TonstakeControllerPoolUpgradeMsgOpCode: inMsgDecodeFuncTonstakeControllerPoolUpgrade,
	// 0x9971881c
	TonstakePoolPrepareGovernanceMigrationMsgOpCode: inMsgDecodeFuncTonstakePoolPrepareGovernanceMigration,
	// 0x99a811fb
	WhalesNominatorsAcceptStakeMsgOpCode: inMsgDecodeFuncWhalesNominatorsAcceptStake,
	// 0x9bf5561c
	TonstakePoolSetDepositSettingsMsgOpCode: inMsgDecodeFuncTonstakePoolSetDepositSettings,
	// 0xa19fd934
	WhalesNominatorsAcceptWithdrawsMsgOpCode: inMsgDecodeFuncWhalesNominatorsAcceptWithdraws,
	// 0xa2065f2c
	WhalesNominatorsSendStakeMsgOpCode: inMsgDecodeFuncWhalesNominatorsSendStake,
	// 0xa37a0983
	TeleitemOkMsgOpCode: inMsgDecodeFuncTeleitemOk,
	// 0xa43227e1
	TeleitemReturnBidMsgOpCode: inMsgDecodeFuncTeleitemReturnBid,
	// 0xa8cb00ad
	ReportRoyaltyParamsMsgOpCode: inMsgDecodeFuncReportRoyaltyParams,
	// 0xa91baf56
	StorageRewardWithdrawalMsgOpCode: inMsgDecodeFuncStorageRewardWithdrawal,
	// 0xad4eb6f5
	DedustPayoutFromPoolMsgOpCode: inMsgDecodeFuncDedustPayoutFromPool,
	// 0xb1ebae06
	TonstakeImanagerRequestNotificationMsgOpCode: inMsgDecodeFuncTonstakeImanagerRequestNotification,
	// 0xb27edcad
	TonstakePoolDeployControllerMsgOpCode: inMsgDecodeFuncTonstakePoolDeployController,
	// 0xb56b9598
	DedustDepositLiquidityAllMsgOpCode: inMsgDecodeFuncDedustDepositLiquidityAll,
	// 0xb6236d63
	StorageContractTerminatedMsgOpCode: inMsgDecodeFuncStorageContractTerminated,
	// 0xc1344900
	TonstakeImanagerStatsMsgOpCode: inMsgDecodeFuncTonstakeImanagerStats,
	// 0xc9f04485
	TonstakeImanagerSetInterestMsgOpCode: inMsgDecodeFuncTonstakeImanagerSetInterest,
	// 0xd0c3bfea
	SbtRequestOwnerMsgOpCode: inMsgDecodeFuncSbtRequestOwner,
	// 0xd372158c
	TonstakeControllerTopUpMsgOpCode: inMsgDecodeFuncTonstakeControllerTopUp,
	// 0xd4caedcd
	StorageContractConfirmedMsgOpCode: inMsgDecodeFuncStorageContractConfirmed,
	// 0xd53276db
	ExcessMsgOpCode: inMsgDecodeFuncExcess,
	// 0xda803efd
	WhalesNominatorsWithdrawMsgOpCode: inMsgDecodeFuncWhalesNominatorsWithdraw,
	// 0xdb3b8abd
	TonstakeNftPayoutMsgOpCode: inMsgDecodeFuncTonstakeNftPayout,
	// 0xdddc88ba
	ChannelClosedMsgOpCode: inMsgDecodeFuncChannelClosed,
	// 0xdfdca27b
	TonstakePoolLoanRepaymentMsgOpCode: inMsgDecodeFuncTonstakePoolLoanRepayment,
	// 0xe4737472
	WalletPluginDestructResponseMsgOpCode: inMsgDecodeFuncWalletPluginDestructResponse,
	// 0xe4748df1
	DeployStorageContractMsgOpCode: inMsgDecodeFuncDeployStorageContract,
	// 0xe642c965
	TonstakePoolRequestLoanMsgOpCode: inMsgDecodeFuncTonstakePoolRequestLoan,
	// 0xe8a0abfe
	TonstakeControllerDisapproveMsgOpCode: inMsgDecodeFuncTonstakeControllerDisapprove,
	// 0xea06185d
	DedustSwapMsgOpCode: inMsgDecodeFuncDedustSwap,
	// 0xeb373a05
	TonstakeControllerRecoverStakeMsgOpCode: inMsgDecodeFuncTonstakeControllerRecoverStake,
	// 0xed58b0b2
	TonstakeNftBurnNotificationMsgOpCode: inMsgDecodeFuncTonstakeNftBurnNotification,
	// 0xed7378a6
	TonstakeControllerReturnUnusedLoanMsgOpCode: inMsgDecodeFuncTonstakeControllerReturnUnusedLoan,
	// 0xf06c7567
	PaymentRequestResponseMsgOpCode: inMsgDecodeFuncPaymentRequestResponse,
	// 0xf0fd2250
	TonstakeControllerUpdateValidatorHashMsgOpCode: inMsgDecodeFuncTonstakeControllerUpdateValidatorHash,
	// 0xf127fe4e
	TonstakeNftBurnMsgOpCode: inMsgDecodeFuncTonstakeNftBurn,
	// 0xf374484c
	ElectorNewStakeConfirmationMsgOpCode: inMsgDecodeFuncElectorNewStakeConfirmation,
	// 0xf93bb43f
	StonfiPaymentRequestMsgOpCode: inMsgDecodeFuncStonfiPaymentRequest,
	// 0xf96f7324
	ElectorRecoverStakeResponseMsgOpCode: inMsgDecodeFuncElectorRecoverStakeResponse,
	// 0xffffffff
	BounceMsgOpCode: inMsgDecodeFuncBounce,
}

const (
	TextCommentMsgOp                             MsgOpName = "TextComment"
	ProveOwnershipMsgOp                          MsgOpName = "ProveOwnership"
	NftOwnershipAssignedMsgOp                    MsgOpName = "NftOwnershipAssigned"
	OwnershipProofMsgOp                          MsgOpName = "OwnershipProof"
	ChallengeQuarantinedChannelStateMsgOp        MsgOpName = "ChallengeQuarantinedChannelState"
	TonstakePoolWithdrawalMsgOp                  MsgOpName = "TonstakePoolWithdrawal"
	SbtOwnerInfoMsgOp                            MsgOpName = "SbtOwnerInfo"
	InitPaymentChannelMsgOp                      MsgOpName = "InitPaymentChannel"
	JettonTransferMsgOp                          MsgOpName = "JettonTransfer"
	OfferStorageContractMsgOp                    MsgOpName = "OfferStorageContract"
	TonstakeNftInitMsgOp                         MsgOpName = "TonstakeNftInit"
	TonstakeControllerPoolHaltMsgOp              MsgOpName = "TonstakeControllerPoolHalt"
	WhalesNominatorsForceKickMsgOp               MsgOpName = "WhalesNominatorsForceKick"
	TonstakeControllerCreditMsgOp                MsgOpName = "TonstakeControllerCredit"
	JettonInternalTransferMsgOp                  MsgOpName = "JettonInternalTransfer"
	WhalesNominatorsWithdrawUnownedResponseMsgOp MsgOpName = "WhalesNominatorsWithdrawUnownedResponse"
	SbtDestroyMsgOp                              MsgOpName = "SbtDestroy"
	StartUncooperativeChannelCloseMsgOp          MsgOpName = "StartUncooperativeChannelClose"
	EncryptedTextCommentMsgOp                    MsgOpName = "EncryptedTextComment"
	WhalesNominatorsStakeWithdrawCompletedMsgOp  MsgOpName = "WhalesNominatorsStakeWithdrawCompleted"
	WhalesNominatorsWithdrawUnownedMsgOp         MsgOpName = "WhalesNominatorsWithdrawUnowned"
	FinishUncooperativeChannelCloseMsgOp         MsgOpName = "FinishUncooperativeChannelClose"
	StonfiSwapMsgOp                              MsgOpName = "StonfiSwap"
	TonstakeControllerPoolSendMessageMsgOp       MsgOpName = "TonstakeControllerPoolSendMessage"
	TeleitemDeployMsgOp                          MsgOpName = "TeleitemDeploy"
	TonstakePoolSetGovernanceFeeMsgOp            MsgOpName = "TonstakePoolSetGovernanceFee"
	GetStaticDataMsgOp                           MsgOpName = "GetStaticData"
	TonstakeControllerValidatorWithdrawalMsgOp   MsgOpName = "TonstakeControllerValidatorWithdrawal"
	TonstakePoolWithdrawMsgOp                    MsgOpName = "TonstakePoolWithdraw"
	AuctionFillUpMsgOp                           MsgOpName = "AuctionFillUp"
	TeleitemCancelAuctionMsgOp                   MsgOpName = "TeleitemCancelAuction"
	ProofStorageMsgOp                            MsgOpName = "ProofStorage"
	ProcessGovernanceDecisionMsgOp               MsgOpName = "ProcessGovernanceDecision"
	TelemintDeployMsgOp                          MsgOpName = "TelemintDeploy"
	TelemintDeployV2MsgOp                        MsgOpName = "TelemintDeployV2"
	StorageWithdrawMsgOp                         MsgOpName = "StorageWithdraw"
	DedustPayoutMsgOp                            MsgOpName = "DedustPayout"
	ElectorRecoverStakeRequestMsgOp              MsgOpName = "ElectorRecoverStakeRequest"
	TonstakePoolDepositMsgOp                     MsgOpName = "TonstakePoolDeposit"
	TeleitemStartAuctionMsgOp                    MsgOpName = "TeleitemStartAuction"
	TonstakePoolTouchMsgOp                       MsgOpName = "TonstakePoolTouch"
	ElectorNewStakeMsgOp                         MsgOpName = "ElectorNewStake"
	DeleteDnsRecordMsgOp                         MsgOpName = "DeleteDnsRecord"
	ChangeDnsRecordMsgOp                         MsgOpName = "ChangeDnsRecord"
	DnsBalanceReleaseMsgOp                       MsgOpName = "DnsBalanceRelease"
	UpdatePubkeyMsgOp                            MsgOpName = "UpdatePubkey"
	UpdateStorageParamsMsgOp                     MsgOpName = "UpdateStorageParams"
	TonstakeImanagerOperationFeeMsgOp            MsgOpName = "TonstakeImanagerOperationFee"
	ChannelCooperativeCloseMsgOp                 MsgOpName = "ChannelCooperativeClose"
	OutbidNotificationMsgOp                      MsgOpName = "OutbidNotification"
	TonstakeControllerReturnAvailableFundsMsgOp  MsgOpName = "TonstakeControllerReturnAvailableFunds"
	JettonBurnMsgOp                              MsgOpName = "JettonBurn"
	TonstakePoolSetRolesMsgOp                    MsgOpName = "TonstakePoolSetRoles"
	NftTransferMsgOp                             MsgOpName = "NftTransfer"
	TegroSwapTonMsgOp                            MsgOpName = "TegroSwapTon"
	DedustSwapExternalMsgOp                      MsgOpName = "DedustSwapExternal"
	TonstakeControllerSendRequestLoanMsgOp       MsgOpName = "TonstakeControllerSendRequestLoan"
	WalletPluginDestructMsgOp                    MsgOpName = "WalletPluginDestruct"
	SettleChannelConditionalsMsgOp               MsgOpName = "SettleChannelConditionals"
	TopUpChannelBalanceMsgOp                     MsgOpName = "TopUpChannelBalance"
	GetRoyaltyParamsMsgOp                        MsgOpName = "GetRoyaltyParams"
	SbtRevokeMsgOp                               MsgOpName = "SbtRevoke"
	PaymentRequestMsgOp                          MsgOpName = "PaymentRequest"
	TonstakeControllerPoolUnhaltMsgOp            MsgOpName = "TonstakeControllerPoolUnhalt"
	DedustSwapPeerMsgOp                          MsgOpName = "DedustSwapPeer"
	JettonNotifyMsgOp                            MsgOpName = "JettonNotify"
	SubscriptionPaymentMsgOp                     MsgOpName = "SubscriptionPayment"
	WhalesNominatorsStakeWithdrawDelayedMsgOp    MsgOpName = "WhalesNominatorsStakeWithdrawDelayed"
	MegatonWtonMintMsgOp                         MsgOpName = "MegatonWtonMint"
	ChannelCooperativeCommitMsgOp                MsgOpName = "ChannelCooperativeCommit"
	TonstakeControllerPoolSetSudoerMsgOp         MsgOpName = "TonstakeControllerPoolSetSudoer"
	CloseStorageContractMsgOp                    MsgOpName = "CloseStorageContract"
	AcceptStorageContractMsgOp                   MsgOpName = "AcceptStorageContract"
	TonstakeControllerApproveMsgOp               MsgOpName = "TonstakeControllerApprove"
	WhalesNominatorsDepositMsgOp                 MsgOpName = "WhalesNominatorsDeposit"
	JettonBurnNotificationMsgOp                  MsgOpName = "JettonBurnNotification"
	ReportStaticDataMsgOp                        MsgOpName = "ReportStaticData"
	TonstakeControllerWithdrawValidatorMsgOp     MsgOpName = "TonstakeControllerWithdrawValidator"
	TonstakeControllerPoolUpgradeMsgOp           MsgOpName = "TonstakeControllerPoolUpgrade"
	TonstakePoolPrepareGovernanceMigrationMsgOp  MsgOpName = "TonstakePoolPrepareGovernanceMigration"
	WhalesNominatorsAcceptStakeMsgOp             MsgOpName = "WhalesNominatorsAcceptStake"
	TonstakePoolSetDepositSettingsMsgOp          MsgOpName = "TonstakePoolSetDepositSettings"
	WhalesNominatorsAcceptWithdrawsMsgOp         MsgOpName = "WhalesNominatorsAcceptWithdraws"
	WhalesNominatorsSendStakeMsgOp               MsgOpName = "WhalesNominatorsSendStake"
	TeleitemOkMsgOp                              MsgOpName = "TeleitemOk"
	TeleitemReturnBidMsgOp                       MsgOpName = "TeleitemReturnBid"
	ReportRoyaltyParamsMsgOp                     MsgOpName = "ReportRoyaltyParams"
	StorageRewardWithdrawalMsgOp                 MsgOpName = "StorageRewardWithdrawal"
	DedustPayoutFromPoolMsgOp                    MsgOpName = "DedustPayoutFromPool"
	TonstakeImanagerRequestNotificationMsgOp     MsgOpName = "TonstakeImanagerRequestNotification"
	TonstakePoolDeployControllerMsgOp            MsgOpName = "TonstakePoolDeployController"
	DedustDepositLiquidityAllMsgOp               MsgOpName = "DedustDepositLiquidityAll"
	StorageContractTerminatedMsgOp               MsgOpName = "StorageContractTerminated"
	TonstakeImanagerStatsMsgOp                   MsgOpName = "TonstakeImanagerStats"
	TonstakeImanagerSetInterestMsgOp             MsgOpName = "TonstakeImanagerSetInterest"
	SbtRequestOwnerMsgOp                         MsgOpName = "SbtRequestOwner"
	TonstakeControllerTopUpMsgOp                 MsgOpName = "TonstakeControllerTopUp"
	StorageContractConfirmedMsgOp                MsgOpName = "StorageContractConfirmed"
	ExcessMsgOp                                  MsgOpName = "Excess"
	WhalesNominatorsWithdrawMsgOp                MsgOpName = "WhalesNominatorsWithdraw"
	TonstakeNftPayoutMsgOp                       MsgOpName = "TonstakeNftPayout"
	ChannelClosedMsgOp                           MsgOpName = "ChannelClosed"
	TonstakePoolLoanRepaymentMsgOp               MsgOpName = "TonstakePoolLoanRepayment"
	WalletPluginDestructResponseMsgOp            MsgOpName = "WalletPluginDestructResponse"
	DeployStorageContractMsgOp                   MsgOpName = "DeployStorageContract"
	TonstakePoolRequestLoanMsgOp                 MsgOpName = "TonstakePoolRequestLoan"
	TonstakeControllerDisapproveMsgOp            MsgOpName = "TonstakeControllerDisapprove"
	DedustSwapMsgOp                              MsgOpName = "DedustSwap"
	TonstakeControllerRecoverStakeMsgOp          MsgOpName = "TonstakeControllerRecoverStake"
	TonstakeNftBurnNotificationMsgOp             MsgOpName = "TonstakeNftBurnNotification"
	TonstakeControllerReturnUnusedLoanMsgOp      MsgOpName = "TonstakeControllerReturnUnusedLoan"
	PaymentRequestResponseMsgOp                  MsgOpName = "PaymentRequestResponse"
	TonstakeControllerUpdateValidatorHashMsgOp   MsgOpName = "TonstakeControllerUpdateValidatorHash"
	TonstakeNftBurnMsgOp                         MsgOpName = "TonstakeNftBurn"
	ElectorNewStakeConfirmationMsgOp             MsgOpName = "ElectorNewStakeConfirmation"
	StonfiPaymentRequestMsgOp                    MsgOpName = "StonfiPaymentRequest"
	ElectorRecoverStakeResponseMsgOp             MsgOpName = "ElectorRecoverStakeResponse"
	BounceMsgOp                                  MsgOpName = "Bounce"
)

const (
	TextCommentMsgOpCode                             MsgOpCode = 0x00000000
	ProveOwnershipMsgOpCode                          MsgOpCode = 0x04ded148
	NftOwnershipAssignedMsgOpCode                    MsgOpCode = 0x05138d91
	OwnershipProofMsgOpCode                          MsgOpCode = 0x0524c7ae
	ChallengeQuarantinedChannelStateMsgOpCode        MsgOpCode = 0x088eaa32
	TonstakePoolWithdrawalMsgOpCode                  MsgOpCode = 0x0a77535c
	SbtOwnerInfoMsgOpCode                            MsgOpCode = 0x0dd607e3
	InitPaymentChannelMsgOpCode                      MsgOpCode = 0x0e0620c2
	JettonTransferMsgOpCode                          MsgOpCode = 0x0f8a7ea5
	OfferStorageContractMsgOpCode                    MsgOpCode = 0x107c49ef
	TonstakeNftInitMsgOpCode                         MsgOpCode = 0x132f9a45
	TonstakeControllerPoolHaltMsgOpCode              MsgOpCode = 0x139a1b4e
	WhalesNominatorsForceKickMsgOpCode               MsgOpCode = 0x1596920c
	TonstakeControllerCreditMsgOpCode                MsgOpCode = 0x1690c604
	JettonInternalTransferMsgOpCode                  MsgOpCode = 0x178d4519
	WhalesNominatorsWithdrawUnownedResponseMsgOpCode MsgOpCode = 0x1d1715bf
	SbtDestroyMsgOpCode                              MsgOpCode = 0x1f04537a
	StartUncooperativeChannelCloseMsgOpCode          MsgOpCode = 0x1f151acf
	EncryptedTextCommentMsgOpCode                    MsgOpCode = 0x2167da4b
	WhalesNominatorsStakeWithdrawCompletedMsgOpCode  MsgOpCode = 0x23d421e1
	WhalesNominatorsWithdrawUnownedMsgOpCode         MsgOpCode = 0x251d6a98
	FinishUncooperativeChannelCloseMsgOpCode         MsgOpCode = 0x25432a91
	StonfiSwapMsgOpCode                              MsgOpCode = 0x25938561
	TonstakeControllerPoolSendMessageMsgOpCode       MsgOpCode = 0x270695fb
	TeleitemDeployMsgOpCode                          MsgOpCode = 0x299a3e15
	TonstakePoolSetGovernanceFeeMsgOpCode            MsgOpCode = 0x2aaa96a0
	GetStaticDataMsgOpCode                           MsgOpCode = 0x2fcb26a2
	TonstakeControllerValidatorWithdrawalMsgOpCode   MsgOpCode = 0x30026327
	TonstakePoolWithdrawMsgOpCode                    MsgOpCode = 0x319b0cdc
	AuctionFillUpMsgOpCode                           MsgOpCode = 0x370fec51
	TeleitemCancelAuctionMsgOpCode                   MsgOpCode = 0x371638ae
	ProofStorageMsgOpCode                            MsgOpCode = 0x419d5d4d
	ProcessGovernanceDecisionMsgOpCode               MsgOpCode = 0x44beae41
	TelemintDeployMsgOpCode                          MsgOpCode = 0x4637289a
	TelemintDeployV2MsgOpCode                        MsgOpCode = 0x4637289b
	StorageWithdrawMsgOpCode                         MsgOpCode = 0x46ed2e94
	DedustPayoutMsgOpCode                            MsgOpCode = 0x474f86cf
	ElectorRecoverStakeRequestMsgOpCode              MsgOpCode = 0x47657424
	TonstakePoolDepositMsgOpCode                     MsgOpCode = 0x47d54391
	TeleitemStartAuctionMsgOpCode                    MsgOpCode = 0x487a8e81
	TonstakePoolTouchMsgOpCode                       MsgOpCode = 0x4bc7c2df
	ElectorNewStakeMsgOpCode                         MsgOpCode = 0x4e73744b
	DeleteDnsRecordMsgOpCode                         MsgOpCode = 0x4eb1f0f9
	ChangeDnsRecordMsgOpCode                         MsgOpCode = 0x4eb1f0f9
	DnsBalanceReleaseMsgOpCode                       MsgOpCode = 0x4ed14b65
	UpdatePubkeyMsgOpCode                            MsgOpCode = 0x53f34cd6
	UpdateStorageParamsMsgOpCode                     MsgOpCode = 0x54cbf19b
	TonstakeImanagerOperationFeeMsgOpCode            MsgOpCode = 0x54d37487
	ChannelCooperativeCloseMsgOpCode                 MsgOpCode = 0x5577587e
	OutbidNotificationMsgOpCode                      MsgOpCode = 0x557cea20
	TonstakeControllerReturnAvailableFundsMsgOpCode  MsgOpCode = 0x55c26cd5
	JettonBurnMsgOpCode                              MsgOpCode = 0x595f07bc
	TonstakePoolSetRolesMsgOpCode                    MsgOpCode = 0x5e517f36
	NftTransferMsgOpCode                             MsgOpCode = 0x5fcc3d14
	TegroSwapTonMsgOpCode                            MsgOpCode = 0x600c00fd
	DedustSwapExternalMsgOpCode                      MsgOpCode = 0x61ee542d
	TonstakeControllerSendRequestLoanMsgOpCode       MsgOpCode = 0x6335b11a
	WalletPluginDestructMsgOpCode                    MsgOpCode = 0x64737472
	SettleChannelConditionalsMsgOpCode               MsgOpCode = 0x66f6f069
	TopUpChannelBalanceMsgOpCode                     MsgOpCode = 0x67c7d281
	GetRoyaltyParamsMsgOpCode                        MsgOpCode = 0x693d3950
	SbtRevokeMsgOpCode                               MsgOpCode = 0x6f89f5e3
	PaymentRequestMsgOpCode                          MsgOpCode = 0x706c7567
	TonstakeControllerPoolUnhaltMsgOpCode            MsgOpCode = 0x7247e7a5
	DedustSwapPeerMsgOpCode                          MsgOpCode = 0x72aca8aa
	JettonNotifyMsgOpCode                            MsgOpCode = 0x7362d09c
	SubscriptionPaymentMsgOpCode                     MsgOpCode = 0x73756273
	WhalesNominatorsStakeWithdrawDelayedMsgOpCode    MsgOpCode = 0x74bb3427
	MegatonWtonMintMsgOpCode                         MsgOpCode = 0x77a33521
	ChannelCooperativeCommitMsgOpCode                MsgOpCode = 0x79a126ef
	TonstakeControllerPoolSetSudoerMsgOpCode         MsgOpCode = 0x79e7c016
	CloseStorageContractMsgOpCode                    MsgOpCode = 0x79f937ea
	AcceptStorageContractMsgOpCode                   MsgOpCode = 0x7a361688
	TonstakeControllerApproveMsgOpCode               MsgOpCode = 0x7b4b42e6
	WhalesNominatorsDepositMsgOpCode                 MsgOpCode = 0x7bcd1fef
	JettonBurnNotificationMsgOpCode                  MsgOpCode = 0x7bdd97de
	ReportStaticDataMsgOpCode                        MsgOpCode = 0x8b771735
	TonstakeControllerWithdrawValidatorMsgOpCode     MsgOpCode = 0x8efed779
	TonstakeControllerPoolUpgradeMsgOpCode           MsgOpCode = 0x96e7f528
	TonstakePoolPrepareGovernanceMigrationMsgOpCode  MsgOpCode = 0x9971881c
	WhalesNominatorsAcceptStakeMsgOpCode             MsgOpCode = 0x99a811fb
	TonstakePoolSetDepositSettingsMsgOpCode          MsgOpCode = 0x9bf5561c
	WhalesNominatorsAcceptWithdrawsMsgOpCode         MsgOpCode = 0xa19fd934
	WhalesNominatorsSendStakeMsgOpCode               MsgOpCode = 0xa2065f2c
	TeleitemOkMsgOpCode                              MsgOpCode = 0xa37a0983
	TeleitemReturnBidMsgOpCode                       MsgOpCode = 0xa43227e1
	ReportRoyaltyParamsMsgOpCode                     MsgOpCode = 0xa8cb00ad
	StorageRewardWithdrawalMsgOpCode                 MsgOpCode = 0xa91baf56
	DedustPayoutFromPoolMsgOpCode                    MsgOpCode = 0xad4eb6f5
	TonstakeImanagerRequestNotificationMsgOpCode     MsgOpCode = 0xb1ebae06
	TonstakePoolDeployControllerMsgOpCode            MsgOpCode = 0xb27edcad
	DedustDepositLiquidityAllMsgOpCode               MsgOpCode = 0xb56b9598
	StorageContractTerminatedMsgOpCode               MsgOpCode = 0xb6236d63
	TonstakeImanagerStatsMsgOpCode                   MsgOpCode = 0xc1344900
	TonstakeImanagerSetInterestMsgOpCode             MsgOpCode = 0xc9f04485
	SbtRequestOwnerMsgOpCode                         MsgOpCode = 0xd0c3bfea
	TonstakeControllerTopUpMsgOpCode                 MsgOpCode = 0xd372158c
	StorageContractConfirmedMsgOpCode                MsgOpCode = 0xd4caedcd
	ExcessMsgOpCode                                  MsgOpCode = 0xd53276db
	WhalesNominatorsWithdrawMsgOpCode                MsgOpCode = 0xda803efd
	TonstakeNftPayoutMsgOpCode                       MsgOpCode = 0xdb3b8abd
	ChannelClosedMsgOpCode                           MsgOpCode = 0xdddc88ba
	TonstakePoolLoanRepaymentMsgOpCode               MsgOpCode = 0xdfdca27b
	WalletPluginDestructResponseMsgOpCode            MsgOpCode = 0xe4737472
	DeployStorageContractMsgOpCode                   MsgOpCode = 0xe4748df1
	TonstakePoolRequestLoanMsgOpCode                 MsgOpCode = 0xe642c965
	TonstakeControllerDisapproveMsgOpCode            MsgOpCode = 0xe8a0abfe
	DedustSwapMsgOpCode                              MsgOpCode = 0xea06185d
	TonstakeControllerRecoverStakeMsgOpCode          MsgOpCode = 0xeb373a05
	TonstakeNftBurnNotificationMsgOpCode             MsgOpCode = 0xed58b0b2
	TonstakeControllerReturnUnusedLoanMsgOpCode      MsgOpCode = 0xed7378a6
	PaymentRequestResponseMsgOpCode                  MsgOpCode = 0xf06c7567
	TonstakeControllerUpdateValidatorHashMsgOpCode   MsgOpCode = 0xf0fd2250
	TonstakeNftBurnMsgOpCode                         MsgOpCode = 0xf127fe4e
	ElectorNewStakeConfirmationMsgOpCode             MsgOpCode = 0xf374484c
	StonfiPaymentRequestMsgOpCode                    MsgOpCode = 0xf93bb43f
	ElectorRecoverStakeResponseMsgOpCode             MsgOpCode = 0xf96f7324
	BounceMsgOpCode                                  MsgOpCode = 0xffffffff
)

var KnownMsgTypes = map[string]any{
	TextCommentMsgOp:                             TextCommentMsgBody{},
	ProveOwnershipMsgOp:                          ProveOwnershipMsgBody{},
	NftOwnershipAssignedMsgOp:                    NftOwnershipAssignedMsgBody{},
	OwnershipProofMsgOp:                          OwnershipProofMsgBody{},
	ChallengeQuarantinedChannelStateMsgOp:        ChallengeQuarantinedChannelStateMsgBody{},
	TonstakePoolWithdrawalMsgOp:                  TonstakePoolWithdrawalMsgBody{},
	SbtOwnerInfoMsgOp:                            SbtOwnerInfoMsgBody{},
	InitPaymentChannelMsgOp:                      InitPaymentChannelMsgBody{},
	JettonTransferMsgOp:                          JettonTransferMsgBody{},
	OfferStorageContractMsgOp:                    OfferStorageContractMsgBody{},
	TonstakeNftInitMsgOp:                         TonstakeNftInitMsgBody{},
	TonstakeControllerPoolHaltMsgOp:              TonstakeControllerPoolHaltMsgBody{},
	WhalesNominatorsForceKickMsgOp:               WhalesNominatorsForceKickMsgBody{},
	TonstakeControllerCreditMsgOp:                TonstakeControllerCreditMsgBody{},
	JettonInternalTransferMsgOp:                  JettonInternalTransferMsgBody{},
	WhalesNominatorsWithdrawUnownedResponseMsgOp: WhalesNominatorsWithdrawUnownedResponseMsgBody{},
	SbtDestroyMsgOp:                              SbtDestroyMsgBody{},
	StartUncooperativeChannelCloseMsgOp:          StartUncooperativeChannelCloseMsgBody{},
	EncryptedTextCommentMsgOp:                    EncryptedTextCommentMsgBody{},
	WhalesNominatorsStakeWithdrawCompletedMsgOp:  WhalesNominatorsStakeWithdrawCompletedMsgBody{},
	WhalesNominatorsWithdrawUnownedMsgOp:         WhalesNominatorsWithdrawUnownedMsgBody{},
	FinishUncooperativeChannelCloseMsgOp:         FinishUncooperativeChannelCloseMsgBody{},
	StonfiSwapMsgOp:                              StonfiSwapMsgBody{},
	TonstakeControllerPoolSendMessageMsgOp:       TonstakeControllerPoolSendMessageMsgBody{},
	TeleitemDeployMsgOp:                          TeleitemDeployMsgBody{},
	TonstakePoolSetGovernanceFeeMsgOp:            TonstakePoolSetGovernanceFeeMsgBody{},
	GetStaticDataMsgOp:                           GetStaticDataMsgBody{},
	TonstakeControllerValidatorWithdrawalMsgOp:   TonstakeControllerValidatorWithdrawalMsgBody{},
	TonstakePoolWithdrawMsgOp:                    TonstakePoolWithdrawMsgBody{},
	AuctionFillUpMsgOp:                           AuctionFillUpMsgBody{},
	TeleitemCancelAuctionMsgOp:                   TeleitemCancelAuctionMsgBody{},
	ProofStorageMsgOp:                            ProofStorageMsgBody{},
	ProcessGovernanceDecisionMsgOp:               ProcessGovernanceDecisionMsgBody{},
	TelemintDeployMsgOp:                          TelemintDeployMsgBody{},
	TelemintDeployV2MsgOp:                        TelemintDeployV2MsgBody{},
	StorageWithdrawMsgOp:                         StorageWithdrawMsgBody{},
	DedustPayoutMsgOp:                            DedustPayoutMsgBody{},
	ElectorRecoverStakeRequestMsgOp:              ElectorRecoverStakeRequestMsgBody{},
	TonstakePoolDepositMsgOp:                     TonstakePoolDepositMsgBody{},
	TeleitemStartAuctionMsgOp:                    TeleitemStartAuctionMsgBody{},
	TonstakePoolTouchMsgOp:                       TonstakePoolTouchMsgBody{},
	ElectorNewStakeMsgOp:                         ElectorNewStakeMsgBody{},
	DeleteDnsRecordMsgOp:                         DeleteDnsRecordMsgBody{},
	ChangeDnsRecordMsgOp:                         ChangeDnsRecordMsgBody{},
	DnsBalanceReleaseMsgOp:                       DnsBalanceReleaseMsgBody{},
	UpdatePubkeyMsgOp:                            UpdatePubkeyMsgBody{},
	UpdateStorageParamsMsgOp:                     UpdateStorageParamsMsgBody{},
	TonstakeImanagerOperationFeeMsgOp:            TonstakeImanagerOperationFeeMsgBody{},
	ChannelCooperativeCloseMsgOp:                 ChannelCooperativeCloseMsgBody{},
	OutbidNotificationMsgOp:                      OutbidNotificationMsgBody{},
	TonstakeControllerReturnAvailableFundsMsgOp:  TonstakeControllerReturnAvailableFundsMsgBody{},
	JettonBurnMsgOp:                              JettonBurnMsgBody{},
	TonstakePoolSetRolesMsgOp:                    TonstakePoolSetRolesMsgBody{},
	NftTransferMsgOp:                             NftTransferMsgBody{},
	TegroSwapTonMsgOp:                            TegroSwapTonMsgBody{},
	DedustSwapExternalMsgOp:                      DedustSwapExternalMsgBody{},
	TonstakeControllerSendRequestLoanMsgOp:       TonstakeControllerSendRequestLoanMsgBody{},
	WalletPluginDestructMsgOp:                    WalletPluginDestructMsgBody{},
	SettleChannelConditionalsMsgOp:               SettleChannelConditionalsMsgBody{},
	TopUpChannelBalanceMsgOp:                     TopUpChannelBalanceMsgBody{},
	GetRoyaltyParamsMsgOp:                        GetRoyaltyParamsMsgBody{},
	SbtRevokeMsgOp:                               SbtRevokeMsgBody{},
	PaymentRequestMsgOp:                          PaymentRequestMsgBody{},
	TonstakeControllerPoolUnhaltMsgOp:            TonstakeControllerPoolUnhaltMsgBody{},
	DedustSwapPeerMsgOp:                          DedustSwapPeerMsgBody{},
	JettonNotifyMsgOp:                            JettonNotifyMsgBody{},
	SubscriptionPaymentMsgOp:                     SubscriptionPaymentMsgBody{},
	WhalesNominatorsStakeWithdrawDelayedMsgOp:    WhalesNominatorsStakeWithdrawDelayedMsgBody{},
	MegatonWtonMintMsgOp:                         MegatonWtonMintMsgBody{},
	ChannelCooperativeCommitMsgOp:                ChannelCooperativeCommitMsgBody{},
	TonstakeControllerPoolSetSudoerMsgOp:         TonstakeControllerPoolSetSudoerMsgBody{},
	CloseStorageContractMsgOp:                    CloseStorageContractMsgBody{},
	AcceptStorageContractMsgOp:                   AcceptStorageContractMsgBody{},
	TonstakeControllerApproveMsgOp:               TonstakeControllerApproveMsgBody{},
	WhalesNominatorsDepositMsgOp:                 WhalesNominatorsDepositMsgBody{},
	JettonBurnNotificationMsgOp:                  JettonBurnNotificationMsgBody{},
	ReportStaticDataMsgOp:                        ReportStaticDataMsgBody{},
	TonstakeControllerWithdrawValidatorMsgOp:     TonstakeControllerWithdrawValidatorMsgBody{},
	TonstakeControllerPoolUpgradeMsgOp:           TonstakeControllerPoolUpgradeMsgBody{},
	TonstakePoolPrepareGovernanceMigrationMsgOp:  TonstakePoolPrepareGovernanceMigrationMsgBody{},
	WhalesNominatorsAcceptStakeMsgOp:             WhalesNominatorsAcceptStakeMsgBody{},
	TonstakePoolSetDepositSettingsMsgOp:          TonstakePoolSetDepositSettingsMsgBody{},
	WhalesNominatorsAcceptWithdrawsMsgOp:         WhalesNominatorsAcceptWithdrawsMsgBody{},
	WhalesNominatorsSendStakeMsgOp:               WhalesNominatorsSendStakeMsgBody{},
	TeleitemOkMsgOp:                              TeleitemOkMsgBody{},
	TeleitemReturnBidMsgOp:                       TeleitemReturnBidMsgBody{},
	ReportRoyaltyParamsMsgOp:                     ReportRoyaltyParamsMsgBody{},
	StorageRewardWithdrawalMsgOp:                 StorageRewardWithdrawalMsgBody{},
	DedustPayoutFromPoolMsgOp:                    DedustPayoutFromPoolMsgBody{},
	TonstakeImanagerRequestNotificationMsgOp:     TonstakeImanagerRequestNotificationMsgBody{},
	TonstakePoolDeployControllerMsgOp:            TonstakePoolDeployControllerMsgBody{},
	DedustDepositLiquidityAllMsgOp:               DedustDepositLiquidityAllMsgBody{},
	StorageContractTerminatedMsgOp:               StorageContractTerminatedMsgBody{},
	TonstakeImanagerStatsMsgOp:                   TonstakeImanagerStatsMsgBody{},
	TonstakeImanagerSetInterestMsgOp:             TonstakeImanagerSetInterestMsgBody{},
	SbtRequestOwnerMsgOp:                         SbtRequestOwnerMsgBody{},
	TonstakeControllerTopUpMsgOp:                 TonstakeControllerTopUpMsgBody{},
	StorageContractConfirmedMsgOp:                StorageContractConfirmedMsgBody{},
	ExcessMsgOp:                                  ExcessMsgBody{},
	WhalesNominatorsWithdrawMsgOp:                WhalesNominatorsWithdrawMsgBody{},
	TonstakeNftPayoutMsgOp:                       TonstakeNftPayoutMsgBody{},
	ChannelClosedMsgOp:                           ChannelClosedMsgBody{},
	TonstakePoolLoanRepaymentMsgOp:               TonstakePoolLoanRepaymentMsgBody{},
	WalletPluginDestructResponseMsgOp:            WalletPluginDestructResponseMsgBody{},
	DeployStorageContractMsgOp:                   DeployStorageContractMsgBody{},
	TonstakePoolRequestLoanMsgOp:                 TonstakePoolRequestLoanMsgBody{},
	TonstakeControllerDisapproveMsgOp:            TonstakeControllerDisapproveMsgBody{},
	DedustSwapMsgOp:                              DedustSwapMsgBody{},
	TonstakeControllerRecoverStakeMsgOp:          TonstakeControllerRecoverStakeMsgBody{},
	TonstakeNftBurnNotificationMsgOp:             TonstakeNftBurnNotificationMsgBody{},
	TonstakeControllerReturnUnusedLoanMsgOp:      TonstakeControllerReturnUnusedLoanMsgBody{},
	PaymentRequestResponseMsgOp:                  PaymentRequestResponseMsgBody{},
	TonstakeControllerUpdateValidatorHashMsgOp:   TonstakeControllerUpdateValidatorHashMsgBody{},
	TonstakeNftBurnMsgOp:                         TonstakeNftBurnMsgBody{},
	ElectorNewStakeConfirmationMsgOp:             ElectorNewStakeConfirmationMsgBody{},
	StonfiPaymentRequestMsgOp:                    StonfiPaymentRequestMsgBody{},
	ElectorRecoverStakeResponseMsgOp:             ElectorRecoverStakeResponseMsgBody{},
	BounceMsgOp:                                  BounceMsgBody{},
}
